#!/bin/sh -e

ar x opensnitch*amd64.deb
tar -xf data.tar.xz -C "$1/"

ar x python3-opensnitch-ui*.deb

tar -xf data.tar.xz -C "$1/"

# remove sysvinit compat files
rm -rf $1/etc/init.d

# remove ebpf modules since we build them manually
rm $1/usr/lib/opensnitchd/ebpf/*
