#!/bin/sh -e

mkdir obj
cd    obj

CC=gcc CXX=g++ \
sh ../js/src/configure.in --prefix=/usr            \
                          --with-intl-api          \
                          --with-system-zlib       \
                          --with-system-icu        \
                          --disable-jemalloc       \
                          --disable-debug-symbols  \
                          --enable-readline
make
make DESTDIR="$1" install

rm -v $1/usr/lib/libjs_static.ajs
sed -i '/@NSPR_CFLAGS@/d' $1/usr/bin/js91-config
