#!/bin/sh -e

CFLAGS+=" -ffat-lto-objects"

cmake -B build -G Ninja \
    -D CMAKE_BUILD_TYPE=None \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D SDL_STATIC=OFF \
    -D SDL_RPATH=OFF

cmake --build build
DESTDIR=$1 cmake --install build

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
export CC='gcc -m32'
export CXX='g++ -m32'
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
CFLAGS+=" -ffat-lto-objects"
cmake -B build -G Ninja \
      -D CMAKE_BUILD_TYPE=None \
      -D CMAKE_INSTALL_PREFIX=/usr \
      -D CMAKE_INSTALL_LIBDIR=lib32 \
      -D SDL_STATIC=OFF \
      -D SDL_RPATH=OFF

cmake --build build
DESTDIR=tmp32dir cmake --install build
rm -rf tmp32dir/usr/{bin,include,share}
rsync -a tmp32dir/* $1/
fi
