#!/bin/bash -e

CFLAGS+=" -ffat-lto-objects"

cmake -B build -G Ninja          \
    -D CMAKE_BUILD_TYPE=None     \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D SDL_TEST_LIBRARY=OFF      \
    -D SDL_STATIC=OFF            \
    -D SDL_RPATH=OFF

cmake --build build
DESTDIR=$1 cmake --install build

if [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf build
export CC='gcc -m32'
export CXX='g++ -m32'
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
CFLAGS+=" -ffat-lto-objects"
cmake -B build -G Ninja             \
      -D CMAKE_BUILD_TYPE=None      \
      -D CMAKE_INSTALL_PREFIX=/usr  \
      -D CMAKE_INSTALL_LIBDIR=lib32 \
      -D SDL_TEST_LIBRARY=OFF       \
      -D SDL_STATIC=OFF             \
      -D SDL_RPATH=OFF

cmake --build build
DESTDIR=tmp32dir cmake --install build
rm -rf tmp32dir/usr/{bin,include,share}
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
rsync -a tmp32dir/* $dest_dir/
fi
