#!/bin/sh -e

./configure --prefix=/usr                \
            --enable-hashes=strong,glibc \
            --enable-obsolete-api=no     \
            --disable-static             \
            --disable-failure-tokens

make
make DESTDIR=$1 install

if [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
CC="gcc -m32" \
./configure --prefix=/usr                \
            --host=i686-pc-linux-gnu     \
            --libdir=/usr/lib32          \
            --enable-hashes=strong,glibc \
            --enable-obsolete-api=glibc  \
            --disable-static             \
            --disable-failure-tokens
make
install -d $1/usr/lib32
cp -av .libs/libcrypt.so* $1/usr/lib32/
make DESTDIR=$1 install-pkgconfigDATA
ln -svf libxcrypt.pc $1/usr/lib32/pkgconfig/libcrypt.pc
fi
