#!/bin/sh -e

# Use CROSS_PREFIX if set (defaults to /usr in hokuto)
PREFIX="${CROSS_PREFIX:-/usr}"

# Define host triplet if cross-compiling
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    # Canonicalize known architectures
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure --prefix="$PREFIX"           \
            --libdir="$PREFIX/lib"       \
            --enable-hashes=strong,glibc \
            --enable-obsolete-api=no     \
            --disable-static             \
            --disable-failure-tokens     \
            $CROSS_OPTS

make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
CC="gcc -m32" \
./configure --prefix=/usr                \
            --host=i686-pc-linux-gnu     \
            --libdir=/usr/lib32          \
            --enable-hashes=strong,glibc \
            --enable-obsolete-api=glibc  \
            --disable-static             \
            --disable-failure-tokens
make
install -d $1/usr/lib32
cp -av .libs/libcrypt.so* $1/usr/lib32/
make DESTDIR=$1 install-pkgconfigDATA
ln -svf libxcrypt.pc $1/usr/lib32/pkgconfig/libcrypt.pc
fi
