#!/bin/sh -e

#git submodule update --init
make fixwlr
cd subprojects/wlroots
meson build/ --prefix=/usr --buildtype=release
ninja -C build
#ninja -C build/ install
cd ..
cd udis86 && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -H./ -B./build -G Ninja && cmake --build ./build --config Release --target all -j$(shell nproc)
cd ../..
make protocols
make release
cd hyprctl
make all
cd ..

mkdir -p "$1/usr/share/wayland-sessions"
mkdir -p "$1/usr/share/hyprland"
install -Dm755 build/Hyprland -t "$1/usr/bin"
install -Dm755 hyprctl/hyprctl -t "$1/usr/bin"
install -Dm644 assets/*.png -t "$1/usr/share/hyprland"
install -Dm644 example/hyprland.desktop -t "$1/usr/share/wayland-sessions"
install -Dm644 example/hyprland.conf -t "$1/usr/share/hyprland"
install -Dm755 subprojects/wlroots/build/libwlroots.so.12032 -t "$1/usr/lib"
