#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure \
    --prefix="$PREFIX" \
    $CROSS_OPTS

make
make DESTDIR=$1 install

if [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
CC="gcc -m32" CXX="g++ -m32"         \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --disable-static

make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
