#!/bin/sh -e

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"

    # Fix ncurses detection for cross-compilation
    if [ -d "/usr/${HOST_TRIPLET}/include/ncursesw" ]; then
        export CPPFLAGS="$CPPFLAGS -I/usr/${HOST_TRIPLET}/include/ncursesw"
    fi
    export LDFLAGS="$LDFLAGS -L/usr/${HOST_TRIPLET}/lib"
fi

./configure --prefix="$PREFIX" \
    --disable-static  \
    --libexecdir="$PREFIX/lib" \
    $CROSS_OPTS

make
make DESTDIR=$1 install
