#!/bin/sh -e

./configure                        \
  --prefix=/usr                    \
  --sysconfdir=/etc                \
  --libexecdir=/usr/lib/resolvconf \
  --sbindir=/usr/bin

make
make DESTDIR=$1 install
