#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi

autoreconf -fvi
./configure --prefix="$PREFIX" --without-libclang "${CROSS_OPTS[@]}"
make
make DESTDIR=$1 install
