#!/bin/sh -e

if [ "${HOKUTO_CROSS_SYSTEM:-0}" = "1" ]; then
TARGET_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
# Do not run fixincludes
sed -i 's@\./fixinc\.sh@-c true@' gcc/Makefile.in
sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" libiberty/configure

mkdir gcc-build
cd gcc-build

../configure \
    --prefix=/usr \
    --program-prefix="${TARGET_TRIPLET}-" \
    --with-local-prefix="$CROSS_PREFIX" \
    --with-sysroot="$CROSS_PREFIX" \
    --with-build-sysroot="/usr/${TARGET_TRIPLET}" \
    --with-native-system-header-dir=/include \
    --libdir=/usr/lib \
    --libexecdir=/usr/lib \
    --target="${TARGET_TRIPLET}" \
    --host="$(gcc -dumpmachine)" \
    --build="$(gcc -dumpmachine)" \
    --disable-nls \
    --enable-default-pie \
    --enable-languages=c,c++ \
    --enable-shared \
    --enable-threads=posix \
    --with-system-zlib \
    --with-isl \
    --enable-__cxa_atexit \
    --disable-libunwind-exceptions \
    --enable-clocale=gnu \
    --disable-libstdcxx-pch \
    --disable-libssp \
    --enable-gnu-unique-object \
    --enable-linker-build-id \
    --enable-lto \
    --enable-plugin \
    --enable-install-libiberty \
    --with-linker-hash-style=gnu \
    --enable-gnu-indirect-function \
    --disable-multilib \
    --disable-werror \
    --enable-checking=release

make
make DESTDIR="$1" install-gcc install-target-{libgcc,libstdc++-v3,libgomp,libquadmath,libatomic}

if [ "$CROSS_PREFIX" = "/usr/${TARGET_TRIPLET}" ]; then
# Remove files that conflict with host gcc package
rm -r "$1"/usr/share/man/man7
rm -r "$1"/usr/share/info
rm -r "$1"/usr/share/gcc-$2
fi

else

# Use lib not lib64 by default.
sed -e '/m64=/s/lib64/lib/' \
    -e '/m32=/s/m32=.*/m32=..\/lib32$(call if_multiarch,:i386-linux-gnu)/' \
    -i.orig gcc/config/i386/t-linux64

# Default plugin setting
PLUGIN_OPT="--enable-plugin"

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # Cross-native build: Build on x86, Host on ARM64, Target ARM64
    TARGET_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    HOST_OPT="--build=$(gcc -dumpmachine) --host=${TARGET_TRIPLET} --target=${TARGET_TRIPLET}"
    
    # Isolate Build (x86) from Host (ARM64) configuration
    export CC_FOR_BUILD="gcc"
    export CXX_FOR_BUILD="g++"
    export CFLAGS_FOR_BUILD="-O2"
    export CXXFLAGS_FOR_BUILD="-O2"
    export LDFLAGS_FOR_BUILD=""
    
    # Capture Host flags and clear environment to prevent leakage
    HOST_CFLAGS="$CFLAGS"
    HOST_CXXFLAGS="$CXXFLAGS"
    export CPPFLAGS_FOR_BUILD="-O2"
    HOST_CPPFLAGS="$CPPFLAGS"
    export CPPFLAGS_FOR_BUILD="-O2"
    HOST_CPPFLAGS="$CPPFLAGS"
    unset CC CXX CFLAGS CXXFLAGS LDFLAGS CPPFLAGS
    # Autoconf sometimes misses these if not explicitly set in environment for cross-builds
    
    # We are building for a different arch, so we can't assume i386 config applies effectively,
    # but strictly speaking the source being patched is for i386 which might not be used.
    # However, we DO need to ensure we don't try strict multilib for x86 if we are arm64
    MULTILIB_DISABLE="1"
    
    # Workaround: Disable plugins explicitly for cross-native build
    PLUGIN_OPT="--disable-plugin"
else
    MULTILIB_DISABLE="0"
fi

# Make -mstackrealign a default for 32bit objects
sed '/STACK_REALIGN_DEFAULT/s/0/(!TARGET_64BIT \&\& TARGET_SSE)/' \
      -i gcc/config/i386/i386.h

# Do not run fixincludes
sed -i 's@\./fixinc\.sh@-c true@' gcc/Makefile.in

# Build must happen outside of gcc source.
mkdir -p gcc-build
cd gcc-build

if [ "$MULTILIB" = "1" ] && [ "${MULTILIB_DISABLE:-0}" = "0" ]; then
    multilib_opt="--enable-multilib --with-multilib-list=m64,m32"
else
    multilib_opt="--disable-multilib"
fi

../configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    $HOST_OPT \
    $multilib_opt \
    CC_FOR_BUILD="gcc" \
    CXX_FOR_BUILD="g++" \
    CFLAGS_FOR_BUILD="-O2" \
    CXXFLAGS_FOR_BUILD="-O2" \
    LDFLAGS_FOR_BUILD="" \
    --disable-werror \
    --enable-__cxa_atexit \
    --enable-default-pie \
    --enable-default-ssp \
    --enable-shared \
    --enable-threads \
    --enable-tls \
    --enable-languages=c,c++ \
    --enable-checking=release \
    --enable-initfini-array \
    --without-included-gettext \
    --with-system-zlib \
    --enable-link-serialization=1 \
    --enable-linker-build-id \
    --enable-lto \
    $PLUGIN_OPT \
    --disable-bootstrap

make
make DESTDIR="$1" install
fi
# Save 35MB.
find "$1" -name libgtkpeer.a  -exec rm -f {} +
find "$1" -name libgjsmalsa.a -exec rm -f {} +
find "$1" -name libgij.a      -exec rm -f {} +

# Some legacy programs will expect cc
ln -s gcc "$1/usr/bin/cc"

# POSIX compliance.
install -Dm755 ../c99 "$1/usr/bin/c99"

# Symlink for LTO.
{
mkdir -p "$1/usr/lib/bfd-plugins"

ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/$2/liblto_plugin.so \
        $1/usr/lib/bfd-plugins/
}

if [ "$CROSS_PREFIX" = "/usr/${TARGET_TRIPLET}" ]; then
# Remove files that conflict with host gcc package
rm -rf "$1"/usr/share/man
rm -rf "$1"/usr/share/info
rm -rf "$1"/usr/share/gcc-$2
rm -rf "$1"/usr/bin/cc
rm -rf "$1"/usr/bin/c99
rm -rf "$1"/usr/lib/bfd-plugins
fi
