#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
cmake -B build \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DDISABLE_EXTRA_LIBS=ON \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DBUILD_TESTING=OFF \
    $CROSS_OPTS

cmake --build   build
DESTDIR=$1 cmake --install build

