#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
cmake -B build \
    -D CMAKE_INSTALL_PREFIX="$PREFIX" \
    -D CMAKE_INSTALL_LIBDIR=lib       \
    -D CMAKE_BUILD_TYPE=Release       \
    -D BUILD_STATIC_LIBS=OFF          \
    -D ENABLE_THREADING=ON            \
    -D DISABLE_EXTRA_LIBS=ON          \
    -D CMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -D BUILD_TESTING=OFF \
    $CROSS_OPTS

cmake --build   build
DESTDIR=$1 cmake --install build
