#!/bin/bash -e

cmake -B build -D CMAKE_BUILD_TYPE=None             \
    -D CMAKE_INSTALL_PREFIX=/usr                    \
    -D FLUID_DAEMON_ENV_FILE=/etc/conf.d/fluidsynth \
    -D LIB_SUFFIX=""                                \
    -D enable-ladspa=ON                             \
    -D enable-portaudio=ON                          \
    -W no-dev

cmake --build build
DESTDIR=$1 cmake --install build

if [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf build
export CC='gcc -m32'
export CXX='g++ -m32'
export PKG_CONFIG_PATH='/usr/lib32/pkgconfig'
cmake -B build                    \
    -D CMAKE_BUILD_TYPE=None      \
    -D CMAKE_INSTALL_LIBDIR=lib32 \
    -D CMAKE_INSTALL_PREFIX=/usr  \
    -D FLUID_DAEMON_ENV_FILE=/etc/conf.d/fluidsynth \
    -W no-dev
cmake --build build
DESTDIR=tmp32dir cmake --install build
rm -rf tmp32dir/usr/{include,share,bin}
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
rsync -a tmp32dir/* $dest_dir/
fi

# soundfounts split package
destdir_fat="$HOKUTO_SPLIT_DIR/fluidsynth-soundfont-fatboy"
destdir_fluid="$HOKUTO_SPLIT_DIR/fluidsynth-soundfont-fluidr3"
install -d "$destdir_fat/usr/share/sounds/sf2"
install -d "$destdir_fluid/usr/share/sounds/sf2"
7z x soundfonts.7z.001
install -Dm 644 FatBoy-v0.790.sf2 "$destdir_fat/usr/share/sounds/sf2/FatBoy-v0.790.sf2"
install -Dm 644 FluidR3_GM.sf2 "$destdir_fluid/usr/share/sounds/sf2/FluidR3_GM.sf2"
ln -s FatBoy-v0.790.sf2  "$destdir_fat/usr/share/sounds/sf2/default.sf2"
