#!/bin/sh -e

sed -i "s/if not version_info.contains('git')/if version_info.length() >= 4/" server/meson.build
sed -i "/meson-dist/d" meson.build

meson setup build --prefix=/usr \
      -D gstreamer=no
meson compile -C build
DESTDIR=$1 meson install -C build
