#!/bin/sh -e

# Default background color.
sed 's/0.25f, 0.25f, 0.25f/0.929, 0.870, 0.678/' \
    sway/desktop/render.c > _
mv -f _ sway/desktop/render.c

meson \
    --prefix=/usr \
    . build

ninja -C build
ninja -C build install

rm -rf \
    "$1/usr/share/fish" \
    "$1/usr/share/bash-completion" \
    "$1/usr/share/backgrounds" \
    "$1/usr/share/zsh"
