#!/bin/bash -e

local cmake_options=(
    -D CMAKE_INSTALL_PREFIX=/usr
    -D CMAKE_BUILD_TYPE=None
    -D ENABLE_STATIC=OFF
    -D ENABLE_TESTING=ON
)

cmake -B build "${cmake_options[@]}"
cmake --build build
DESTDIR="${1}" cmake --install build
