#!/bin/sh -e

export CFLAGS="$CFLAGS -DSYS_BASHRC='\"/etc/bash/bashrc\"'"

for p in bash53-*; do
    patch -Np0 -i "$p";
done

./configure \
    --prefix=/usr \
    --with-installed-readline

make
make DESTDIR="$1" install

ln -s bash "$1/usr/bin/sh"

