#!/bin/sh -e

export CFLAGS="$CFLAGS -DSYS_BASHRC='\"/etc/bash/bashrc\"'"

for i in {001..008}; do
    patch -Np0 -i bash53-$i
done

./configure \
    --prefix=/usr \
    --with-installed-readline

make
make DESTDIR="$1" install


ln -s bash "$1/usr/bin/sh"

