#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddocs=false \
    -Dgtk4=false \
    -Dgnutls=true \
    -Dvapi=false \
    . output

ninja -C output
DESTDIR=$1 ninja -C output install
