#!/bin/sh -e

meson setup build \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -D docs=false \
    -D gtk4=false \
    -D gnutls=true \
    -D vapi=false

meson compile -C build
meson install -C build --destdir=$1
