#!/bin/sh -e

#python 3.12+ fix

sed -i 's/re.sub(/re.sub(r/'         itstool.in
sed -i 's/re.compile(/re.compile(r/' itstool.in


PYTHON=/usr/bin/python3 ./configure --prefix=/usr
make
make DESTDIR=$1 install
