#!/bin/sh -e

autoreconf -fiv

if [ "$HOKUTO_CROSS" = "1" ]; then
./configure --prefix=/usr \
  --host=$HOKUTO_ARCH \
  --sbindir=/usr/bin \
  --sysconfdir=/etc

else
./configure --prefix=/usr \
  --sbindir=/usr/bin \
  --sysconfdir=/etc
fi

make
make DESTDIR=$1 install

install -Dm0644 examples/systemd/vnstat.service -t "$1"/usr/lib/systemd/system
