#!/bin/sh -e

# autotools fix
touch NEWS
autoreconf -fvi
CONFIGURE_ARGS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CONFIGURE_ARGS="--host=$HOKUTO_ARCH-linux-gnu"
fi

./configure --prefix=${CROSS_PREFIX:-/usr} $CONFIGURE_ARGS

make
make DESTDIR=$1 install
