#!/bin/sh -e
:> nostrip

cd ebpf_prog
CLANG="clang -fno-stack-protector" CFLAGS="" CXXFLAGS="" KERNEL_DIR=/usr/src/linux/ KERNEL_HEADERS=/usr/src/linux make

install -d -m 755 $1/usr/lib/opensnitchd/ebpf

install -m 644 opensnitch.o $1/usr/lib/opensnitchd/ebpf/
install -m 644 opensnitch-dns.o $1/usr/lib/opensnitchd/ebpf/
install -m 644 opensnitch-procs.o $1/usr/lib/opensnitchd/ebpf/
