#!/bin/sh -e

ar x $3-linux-x64-$2.deb
tar xvf data.tar.xz -C $1/
# Delete locales and lintian
find $1/usr/lib/exodus/locales/ -maxdepth 1 -type f ! -name 'en*' -exec rm {} +
rm -rf $1/usr/share/lintian
