#!/bin/bash -e

if hokuto check glycin; then
    glycin_opt=enabled
else
    glycin_opt=disabled
fi

# The cross glib is built without introspection, so gobject-introspection-1.0
# is absent from the sysroot. Leaving introspection enabled makes meson fall
# back to the glib wrap and build a whole second glib. glycin is probed on the
# host, which says nothing about the target.
introspection_opt=enabled
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    introspection_opt=disabled
    glycin_opt=disabled
fi

hokuto-meson build           \
    -D android=disabled      \
    -D builtin_loaders=all   \
    -D documentation=false   \
    -D gif=disabled          \
    -D glycin=$glycin_opt    \
    -D gtk_doc=false         \
    -D installed_tests=false \
    -D introspection=$introspection_opt \
    -D jpeg=disabled         \
    -D man=false             \
    -D others=enabled        \
    -D png=disabled          \
    -D thumbnailer=disabled  \
    -D tiff=disabled

meson compile -C build
meson install -C build --destdir=$1

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
rm -rf build
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
meson_options=(
    -D android=disabled
    -D builtin_loaders=all
    -D documentation=false
    -D gif=enabled
    -D glycin=disabled
    -D gtk_doc=false
    -D installed_tests=false
    -D introspection=disabled
    -D jpeg=enabled
    -D legacy_xpm=enabled
    -D man=false
    -D others=enabled
    -D png=enabled
    -D thumbnailer=disabled
    -D tiff=enabled
  )
hokuto-meson-32 build "${meson_options[@]}"
meson compile -C build
meson install -C build --destdir "$pkgdir"
rm -rf "$pkgdir"/usr/{include,lib,share}
find "$pkgdir/usr/bin" -type f -not -name gdk-pixbuf-query-loaders -delete
mv "$pkgdir"/usr/bin/gdk-pixbuf-query-loaders{,-32}
fi

