#!/bin/sh -e

if hokuto check glycin; then
    glycin_opt=enabled
else
    glycin_opt=disabled
fi

meson setup build            \
      --prefix=/usr          \
      --buildtype=release    \
    -D android=disabled      \
    -D builtin_loaders=all   \
    -D documentation=false   \
    -D gif=disabled          \
    -D glycin=$glycin_opt    \
    -D gtk_doc=false         \
    -D installed_tests=false \
    -D introspection=enabled \
    -D jpeg=disabled         \
    -D man=false             \
    -D others=enabled        \
    -D png=disabled          \
    -D thumbnailer=disabled  \
    -D tiff=disabled

meson compile -C build
meson install -C build --destdir=$1
