#!/bin/bash -e

if hokuto check glycin; then
    glycin_opt=enabled
else
    glycin_opt=disabled
fi

# glycin decodes images for gdk-pixbuf, which is why the built-in loaders stay
# off. It has to be enabled for the target too: with both switched off, the
# cross built gdk-pixbuf cannot read jpeg, png, gif or tiff at all, and
# icewmbg reports "cannot load <file>" for every image.
loaders_opt=disabled
introspection_opt=enabled
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
introspection_opt=disabled
if hokuto check aarch64-glycin; then
    glycin_opt=enabled
else
    glycin_opt=disabled
fi
fi

hokuto-meson build           \
    --debug \
    -D android=disabled      \
    -D builtin_loaders=all   \
    -D documentation=false   \
    -D gif=$loaders_opt          \
    -D glycin=$glycin_opt    \
    -D gtk_doc=false         \
    -D installed_tests=false \
    -D introspection=$introspection_opt \
    -D jpeg=$loaders_opt         \
    -D man=false             \
    -D others=enabled        \
    -D png=$loaders_opt          \
    -D thumbnailer=disabled  \
    -D tiff=$loaders_opt

meson compile -C build
meson install -C build --destdir=$1

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
rm -rf build
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
meson_options=(
    -D android=disabled
    -D builtin_loaders=all
    -D documentation=false
    -D gif=enabled
    -D glycin=disabled
    -D gtk_doc=false
    -D installed_tests=false
    -D introspection=disabled
    -D jpeg=enabled
    -D legacy_xpm=enabled
    -D man=false
    -D others=enabled
    -D png=enabled
    -D thumbnailer=disabled
    -D tiff=enabled
  )
hokuto-meson-32 build "${meson_options[@]}"
meson compile -C build
meson install -C build --destdir "$pkgdir"
rm -rf "$pkgdir"/usr/{include,lib,share}
find "$pkgdir/usr/bin" -type f -not -name gdk-pixbuf-query-loaders -delete
mv "$pkgdir"/usr/bin/gdk-pixbuf-query-loaders{,-32}
fi

