#!/bin/bash -e

autoreconf --force --install

mkdir build
cd build

../configure \
  --prefix=/usr \
  --sbindir=/usr/bin \
  --libexec=/usr/lib \
  --enable-dco \
  --enable-plugins \
  --enable-systemd \
  --enable-x509-alt-username
make

# Install openvpn
make DESTDIR="${1}" install

# Install sysusers and tmpfiles files
install -D -m0644 ../openvpn.sysusers "${1}"/usr/lib/sysusers.d/openvpn.conf
install -D -m0644 ../openvpn.tmpfiles "${1}"/usr/lib/tmpfiles.d/openvpn.conf

cd ..

# Install examples
install -d -m0755 "${1}"/usr/share/openvpn
cp -r sample/sample-config-files "${1}"/usr/share/openvpn/examples

# Install contrib
for FILE in $(find contrib -type f); do
  case "$(file --brief --mime-type --no-sandbox "${FILE}")" in
    "text/x-shellscript")
      install -D -m0755 "${FILE}" "${1}/usr/share/openvpn/${FILE}" ;;
    *)
      install -D -m0644 "${FILE}" "${1}/usr/share/openvpn/${FILE}" ;;
  esac
done

