#!/bin/sh
# don't build big packages in ram
BIG_PKGS="llvm firefox qt6 webkit2gtk-4.1"

if [ "$1" = "b" ] && echo "$BIG_PKGS" | grep -qw "$2"; then
    echo "[INFO] Setting KISS_TMPDIR=/var/tmpdir for $2"
    KISS_TMPDIR=/var/tmpdir exec kisss "$@"
else
    exec kisss "$@"
fi
