#!/bin/sh -e

install -d $1/usr/lib/jdk-$2
install -d $1/usr/bin
cp -a * $1/usr/lib/jdk-$2

ln -s /usr/lib/jdk-$2/bin/java    $1/usr/bin/java
ln -s /usr/lib/jdk-$2/bin/javac   $1/usr/bin/javac
ln -s /usr/lib/jdk-$2/bin/jar     $1/usr/bin/jar
ln -s /usr/lib/jdk-$2/bin/javadoc $1/usr/bin/javadoc
ln -s /usr/lib/jdk-$2/bin/javap   $1/usr/bin/javap

