#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure --prefix="$PREFIX" \
            --disable-static   \
            $CROSS_OPTS

make
make DESTDIR=$1 install

# gdb looks for the auto-load script under auto-load/<absolute libdir>, which
# follows the install prefix.
install -d "$1$PREFIX/share/gdb/auto-load$PREFIX/lib"
mv -v "$1$PREFIX"/lib/libisl*gdb.py "$1$PREFIX/share/gdb/auto-load$PREFIX/lib"
