#!/bin/sh -e

sed -i 's/cp -p/cp/' build/make/Makefile

mkdir bld
cd bld
sh ../configure \
    --prefix=/usr \
    --target=x86_64-linux-gcc \
    --enable-vp8 \
    --enable-vp9 \
    --enable-experimental \
    --enable-runtime-cpu-detect \
    --enable-shared \
    --enable-postproc \
    --enable-pic \
    --disable-tools \
    --disable-examples \
    --disable-docs \
    --disable-unit-tests \
    --disable-install-docs \
    --disable-install-srcs \
    --disable-install-bins \
    --as=nasm

make
make DESTDIR=$1 install

#32bit

rm -rf *
CC="gcc -m32" CXX="g++ -m32"          \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig  \
../configure --prefix=/usr            \
             --libdir=/usr/lib32      \
             --target=x86-linux-gcc   \
             --enable-shared          \
             --disable-static         \
             --disable-examples       \
             --disable-unit-tests

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
