#!/bin/bash -e

sed -i 's/cp -p/cp/' build/make/Makefile

PREFIX="${CROSS_PREFIX:-/usr}"

# libvpx spells aarch64 "arm64" in its target triples, and takes the toolchain
# as a CROSS prefix. nasm is x86-only -- the arm64 build uses its own NEON
# assembly and must not be pointed at it.
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    export CROSS="${HOKUTO_ARCH}-linux-gnu-"
    VPX_TARGET="arm64-linux-gcc"
    VPX_AS=()
else
    VPX_TARGET="x86_64-linux-gcc"
    VPX_AS=(--as=nasm)
fi

mkdir bld
cd bld
sh ../configure \
    --prefix="$PREFIX" \
    --target="$VPX_TARGET" \
    --enable-vp8 \
    --enable-vp9 \
    --enable-experimental \
    --enable-runtime-cpu-detect \
    --enable-shared \
    --enable-postproc \
    --enable-pic \
    --disable-tools \
    --disable-examples \
    --disable-docs \
    --disable-unit-tests \
    --disable-install-docs \
    --disable-install-srcs \
    --disable-install-bins \
    "${VPX_AS[@]}"

make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf *
CC="gcc -m32" CXX="g++ -m32"          \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig  \
../configure --prefix=/usr            \
             --libdir=/usr/lib32      \
             --target=x86-linux-gcc   \
             --enable-shared          \
             --disable-static         \
             --disable-examples       \
             --disable-unit-tests

make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
