#!/bin/sh -e

cd cdemu-daemon

cmake -B build \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D CMAKE_BUILD_TYPE=Release

cmake --build build
DESTDIR=$1 cmake --install build

install -Dt "$1/usr/lib/systemd/user" -m644 \
  service-example/cdemu-daemon.service
install -Dt "$1/usr/share/dbus-1/services" -m644 \
  service-example/net.sf.cdemu.CDEmuDaemon.service

install -Dm644 /dev/stdin "$1/usr/lib/udev/rules.d/60-cdemu.rules" <<END
ACTION=="add", KERNEL=="vhba_ctl", SUBSYSTEM=="misc", TAG+="uaccess", TAG+="seat", ENV{ID_FOR_SEAT}="seat0"
END

echo 'g cdemu - -' | install -Dm644 /dev/stdin "$1/usr/lib/sysusers.d/cdemu.conf"
echo vhba | install -Dm644 /dev/stdin "$1/usr/lib/modules-load.d/cdemu.conf"


cd ../cdemu-client

cmake -B build \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D CMAKE_BUILD_TYPE=Release

cmake --build build
DESTDIR=$1 cmake --install build

cd ../gcdemu

cmake -B build \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D CMAKE_BUILD_TYPE=Release

cmake --build build
DESTDIR=$1 cmake --install build

