#!/bin/sh -e

meson setup build --prefix=/usr \
            -D mangoapp=true    \
            -D mangohudctl=true

meson compile -C build
DESTDIR=$1 meson install -C build

#32bit
export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export LLVM_CONFIG="/usr/bin/llvm-config32"

meson setup build32       \
     -D include_doc=false \
     --libdir lib32       \
     --prefix=/usr

meson compile -C build32
meson install -C build32 --destdir tmp32
rm -rf build32/tmp32/usr/bin
cp -r build32/tmp32/* $1/
