#!/bin/bash -e

hokuto-meson build \
  -D mangoapp=true \
  -D mangohudctl=true

meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit split package
hokuto-meson-32 build32 \
  -D include_doc=false

meson compile -C build32
meson install -C build32 --destdir tmp32
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
rm -rf build32/tmp32/usr/bin
cp -r build32/tmp32/* $dest_dir/
fi
