#!/bin/sh -e

# Build fails in with clang due to
# -Werror -> -Wsign-compare.
export CFLAGS="-Wno-error $CFLAGS"

meson setup build         \
  --prefix=/usr           \
  --buildtype=plain       \
  -D default_library=both \
  -D server=enabled       \
  -D libseat-logind=systemd

meson compile -C build
meson install -C build --destdir=$1

install -Dm644 seatd.service "$1/usr/lib/systemd/system/seatd.service"
