#!/bin/sh -e

# Build fails in with clang due to
# -Werror -> -Wsign-compare.
export CFLAGS="-Wno-error $CFLAGS"

meson setup build         \
  --prefix=/usr           \
  --buildtype=plain       \
  -D default_library=both \
  -D server=enabled       \
  -D libseat-logind=systemd

meson compile -C build
meson install -C build --destdir=$1

# Allow users in the "seat" group to access seatd, and provide a service
# that will be necessary for e.g. wlroots-based seat management
install -Dm 644 "contrib/systemd/seatd.service" \
  -t "$1/usr/lib/systemd/system/"
install -Dm 644 "sysuser.conf" "$1/usr/lib/sysusers.d/seatd.conf"
