#!/bin/sh -e

# remove nag screen
patch -Np1 -i nag-screen1.patch

# additional content
cp {cheats.zip,patches.zip} data/resources

# unbreak the build
sed -i '/#ifdef __linux__/,/#endif/d' src/core/system.cpp
mv DuckStationDependencies.cmake CMakeModules/
sed -i 's/Qt6::Gui Qt6::Widgets/Qt6::Gui Qt6::GuiPrivate Qt6::Widgets/' src/duckstation-qt/CMakeLists.txt
# always build qt_frontend (conditional breaks cmake script)
sed -i '79d;90d' CMakeModules/DuckStationDependencies.cmake

# only build required deps with custom script/version file
mkdir -pv scripts/deps/patches
cp {versions,build-dependencies-linux.sh} scripts/deps/
cp libpng-1.6.56-apng.patch scripts/deps/patches/
scripts/deps/build-dependencies-linux.sh deps
cd deps
mv lib/* lib64/
rmdir lib
ln -s lib64 lib
mkdir -pv ../dep/prebuilt/linux-x64
cp -r * ../dep/prebuilt/linux-x64/
cd ..

# build duckstation
cmake -B build-release                              \
  -D CMAKE_C_COMPILER=clang                         \
  -D CMAKE_CXX_COMPILER=clang++                     \
  -D CMAKE_EXE_LINKER_FLAGS_INIT="-fuse-ld=lld"     \
  -D CMAKE_MODULE_LINKER_FLAGS_INIT="-fuse-ld=lld"  \
  -D CMAKE_SHARED_LINKER_FLAGS_INIT="-fuse-ld=lld"  \
  -D CMAKE_BUILD_TYPE=Release                       \
  -D CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON          \

cmake --build build-release

# Install everything into /usr/lib/duckstation
install -m 755 -d "${1}/usr/lib"
cp -drv --no-preserve='ownership' build-release/bin "${1}/usr/lib/duckstation"
# Install bundled libraries
find "deps/lib64/" -name '*.so*' -exec cp -dv --no-preserve='ownership' '{}' "${1}/usr/lib/duckstation/" \;

# patch rpath
patchelf --force-rpath --set-rpath "/usr/lib/duckstation" "${1}/usr/lib/duckstation/duckstation-qt"

install -d $1/usr/bin
ln -s /usr/lib/duckstation/duckstation-qt $1/usr/bin/duckstation-qt
install -Dvm644 "duckstation-qt.desktop" "${1}/usr/share/applications/duckstation-qt.desktop"
install -Dvm644 "${1}/usr/lib/duckstation/resources/images/duck.png" "${1}/usr/share/icons/hicolor/64x64/apps/duckstation-qt.png"
