#!/bin/bash -e

./configure --prefix=/usr  \
  --sysconfdir=/etc \
  --sbindir=/usr/bin \
  --localstatedir=/var \
  --disable-mutool

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make DESTDIR="${1}/" install
