#!/bin/sh -e

cmake  -B build \
       -D CMAKE_BUILD_TYPE=Release   \
       -D CMAKE_INSTALL_PREFIX=/usr  \
       -D TESTDATADIR=$PWD/testfiles \
       -D ENABLE_UNSTABLE_API_ABI_HEADERS=ON

cmake --build build
DESTDIR=$1 cmake --install build
