#!/bin/sh -e

./configure --prefix=/usr                        \
	    --bindir=/usr/bin			 \
            --sbindir=/usr/bin	                 \
            --sysconfdir=/etc                    \
            --disable-setuid                     \
            --enable-cache-owner=bin             \
            --with-browser=/usr/bin/links        \
            --with-vgrind=/usr/bin/vgrind        \
            --with-grap=/usr/bin/grap

make
make DESTDIR="$1" install
