#!/bin/sh -e

install -dm 755 "${1}"/usr/{bin,lib,share/dotnet}
cp -dr --no-preserve='ownership' dotnet host "${1}"/usr/share/dotnet/
cp -dr --no-preserve='ownership' shared "${1}"/usr/share/dotnet/
ln -sf /usr/share/dotnet/dotnet "${1}"/usr/bin/dotnet
ln -sf /usr/share/dotnet/host/fxr/"${_runtimever}"/libhostfxr.so "${1}"/usr/lib/libhostfxr.so
install -Dm 644 dotnet.sh -t "${1}"/etc/profile.d/
