#!/bin/sh -e
./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --disable-gtk-doc \
    --disable-gtk2 \
    --disable-nls

make
make DESTDIR="$1" install
