#!/bin/sh -e

make prefix=/usr release
make DESTDIR="$1" prefix=/usr install-common install-shared

#fix missing version in pkgconfig file
sed -i '3s/.*/Version: 1.3.1/' "$1/usr/lib/pkgconfig/mujs.pc"
