#!/bin/sh -e

./configure --libdir=/usr/lib            \
            --with-system-groups=lpadmin

make
make install

mkdir -pv $1/etc/cups/
echo "ServerName /run/cups/cups.sock" > $1/etc/cups/client.conf

install -Dm 0644 cups.pam $1/etc/pam.d/cups
