#!/bin/sh -e

sudo useradd -c "Print Service User" -d /var/spool/cups -g lp -s /bin/false -u 9 lp
sudo groupadd -g 19 lpadmin

echo "******************************"
echo "******************************"
echo "add your used to lpadmin group"
echo "******************************"
echo "******************************"
