#!/bin/bash -e

# libtorrent 2.1 support (merged upstream after 5.2.x)
patch -Np1 -i 23953.patch

cmake -B build \
  -D CMAKE_INSTALL_PREFIX=/usr

cmake --build build
DESTDIR=$1 cmake --install build
