#!/bin/sh -e

# use /usr/lib instead of /usr/libexec: https://gitlab.com/virtio-fs/virtiofsd/-/issues/86
sed 's/libexec/lib/' -i 50-virtiofsd.json

cargo fetch --locked --target "$(rustc -vV | sed -n 's/host: //p')"
export RUSTUP_TOOLCHAIN=stable
export CARGO_TARGET_DIR=target
cargo build --frozen --release
install -vDm 755 target/release/virtiofsd -t "$1/usr/lib/"
install -vDm 644 50-virtiofsd.json -t "$1/usr/share/qemu/vhost-user/"
