#!/bin/bash -e

# fonts-liberation
pushd liberation
destdir=$HOKUTO_SPLIT_DIR/fonts-liberation
install -d $destdir/usr/share/fonts/TTF/
install -Dm644 *.ttf -t "$destdir"/usr/share/fonts/TTF/
popd

# fonts-croscore
destdir=$HOKUTO_SPLIT_DIR/fonts-croscore
install -d $destdir/usr/share/fonts/TTF/
install -Dm644 arimo/fonts/ttf/*.ttf -t "$destdir"/usr/share/fonts/TTF/
install -Dm644 cousine/fonts/ttf/*.ttf -t "$destdir"/usr/share/fonts/TTF/
install -Dm644 tinos/fonts/ttf/*.ttf -t "$destdir"/usr/share/fonts/TTF/

# fonts-helvetica-lucida-vera
pushd helvetica-lucida-vera
destdir=$HOKUTO_SPLIT_DIR/fonts-helvetica-lucida-vera
install -d "$destdir/usr/share/fonts/TTF"
install -Dm644 *.ttf *.otf -t "$destdir/usr/share/fonts/TTF/"
popd

# fonts-noto-traditional-chinese
pushd noto-sans-traditional-chinese
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-traditional-chinese
install -d "$destdir/usr/share/fonts/OTF"
install -Dm644 *.otf -t "$destdir/usr/share/fonts/OTF/"
popd

# fonts-noto-simplified-chinese
pushd noto-sans-simplified-chinese
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-simplified-chinese
install -d "$destdir/usr/share/fonts/OTF"
install -Dm644 *.otf -t "$destdir/usr/share/fonts/OTF/"
popd

# fonts-noto-korean
pushd noto-sans-korean
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-korean
install -d "$destdir/usr/share/fonts/OTF"
install -Dm644 *.otf -t "$destdir/usr/share/fonts/OTF/"
popd

# fonts-noto-japanese
pushd noto-sans-japanese
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-japanese
install -d "$destdir/usr/share/fonts/OTF"
install -Dm644 *.otf -t "$destdir/usr/share/fonts/OTF/"
popd

# Noto hinted static fonts, split by writing system. Hokuto places the Git
# checkout at the build root.
while read -r subpackage families; do
    destdir=$HOKUTO_SPLIT_DIR/$subpackage
    install -d "$destdir/usr/share/fonts/noto"
    for family in $families; do
        install -Dm644 "fonts/$family/hinted/ttf/"*.ttf \
            -t "$destdir/usr/share/fonts/noto/"
    done
done < noto-splits

# fonts-noto-emoji
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-emoji
install -d "$destdir/usr/share/fonts/noto"
install -Dm644 NotoColorEmoji.ttf -t "$destdir/usr/share/fonts/noto/"

# fonts-microsoft
pushd ms-fonts
destdir=$HOKUTO_SPLIT_DIR/fonts-microsoft
install -d "$destdir"/usr/share/fonts/truetype
install -Dm644 arial*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 calibri*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 cambria*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 candara*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 comic*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 consola*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 corbel*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 cour*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 impact*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 lucon*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 marlett*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 segmdl2*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 segoe*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 symbol*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 tahoma*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 times*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 verdana*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 webdings*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 wingding*.ttf -t "$destdir"/usr/share/fonts/truetype/
# fonts-microsoft-extra
destdir=$HOKUTO_SPLIT_DIR/fonts-microsoft-extra
install -d "$destdir"/usr/share/fonts/truetype
install -Dm644 *.ttf -t "$destdir"/usr/share/fonts/truetype/
popd
