#!/bin/bash -e

# fonts-liberation
pushd liberation
destdir=$HOKUTO_SPLIT_DIR/fonts-liberation
install -d $destdir/usr/share/fonts/TTF/
install -Dm644 *.ttf -t "$destdir"/usr/share/fonts/TTF/
popd

# fonts-croscore
pushd noto-fonts
destdir=$HOKUTO_SPLIT_DIR/fonts-croscore
install -d $destdir/usr/share/fonts/TTF/
install -Dm644 Arimo* -t "$destdir"/usr/share/fonts/TTF/
install -Dm644 Cousine* -t "$destdir"/usr/share/fonts/TTF/
install -Dm644 Tinos* -t "$destdir"/usr/share/fonts/TTF/

# fonts-noto-emoji
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-emoji
install -d $destdir/usr/share/fonts/TTF/
install -Dm644 NotoColorEmoji* -t "$destdir"/usr/share/fonts/TTF/

# fonts-noto-traditional-chinese
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-traditional-chinese
install -d $destdir/usr/share/fonts/TTF/
install -Dm644 NotoSansTC* -t "$destdir"/usr/share/fonts/TTF/

# fonts-noto-simplified-chinese
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-simplified-chinese
install -d $destdir/usr/share/fonts/TTF/
install -Dm644 NotoSansSC* -t "$destdir"/usr/share/fonts/TTF/

# fonts-noto-korean
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-korean
install -d $destdir/usr/share/fonts/TTF/
install -Dm644 NotoSansKR* -t "$destdir"/usr/share/fonts/TTF/

# fonts-noto-japanese
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-japanese
install -d $destdir/usr/share/fonts/TTF/
install -Dm644 NotoSansJP* -t "$destdir"/usr/share/fonts/TTF/

# fonts-noto-symbols
destdir=$HOKUTO_SPLIT_DIR/fonts-noto-symbols
install -d $destdir/usr/share/fonts/TTF/
install -Dm644 NotoSansSymbol* -t "$destdir"/usr/share/fonts/TTF/

# fonts-noto
destdir=$HOKUTO_SPLIT_DIR/fonts-noto
install -d $destdir/usr/share/fonts/TTF/
for font in *.ttf; do
    case $font in
        Arimo*|Cousine*|Tinos*) continue ;;
    esac
    install -Dm644 "$font" -t "$destdir"/usr/share/fonts/TTF/
done
popd

# fonts-microsoft
pushd ms-fonts
destdir=$HOKUTO_SPLIT_DIR/fonts-microsoft
install -d "$destdir"/usr/share/fonts/truetype
install -Dm644 arial*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 calibri*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 cambria*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 candara*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 comic*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 consola*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 corbel*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 cour*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 impact*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 lucon*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 marlett*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 segmdl2*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 segoe*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 symbol*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 tahoma*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 times*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 verdana*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 webdings*.ttf -t "$destdir"/usr/share/fonts/truetype/
install -Dm644 wingding*.ttf -t "$destdir"/usr/share/fonts/truetype/
# fonts-microsoft-extra
destdir=$HOKUTO_SPLIT_DIR/fonts-microsoft-extra
install -d "$destdir"/usr/share/fonts/truetype
install -Dm644 *.ttf -t "$destdir"/usr/share/fonts/truetype/
popd
