#!/bin/bash -e

fonts='
0xProto
3270
AdwaitaMono
Agave
AnonymousPro
Arimo
AtkinsonHyperlegibleMono
AurulentSansMono
BigBlueTerminal
BitstreamVeraSansMono
CascadiaCode
CascadiaMono
CodeNewRoman
ComicShannsMono
CommitMono
Cousine
D2Coding
DaddyTimeMono
DejaVuSansMono
DepartureMono
DroidSansMono
EnvyCodeR
FantasqueSansMono
FiraCode
FiraMono
GeistMono
Go-Mono
Gohu
Hack
Hasklig
HeavyData
Hermit
iA-Writer
IBMPlexMono
Inconsolata
InconsolataGo
InconsolataLGC
IntelOneMono
Iosevka
IosevkaTerm
IosevkaTermSlab
JetBrainsMono
Lekton
LiberationMono
Lilex
MartianMono
Meslo
Monaspace
Monofur
Monoid
Mononoki
MPlus
NerdFontsSymbolsOnly
Noto
OpenDyslexic
Overpass
ProFont
ProggyClean
Recursive
RobotoMono
ShareTechMono
SourceCodePro
SpaceMono
Terminus
Tinos
Ubuntu
UbuntuMono
UbuntuSans
VictorMono
ZedMono
'

for font in $fonts; do
    srcdir=$font
    pkgdir=$HOKUTO_SPLIT_DIR/fonts-nerd-fonts-$font
    fontdir=$pkgdir/usr/share/fonts/TTF

    if [ ! -d "$srcdir" ]; then
        echo "missing extracted source directory: $srcdir" >&2
        exit 1
    fi

    if ! find "$srcdir" -type f \( -iname '*.ttf' -o -iname '*.otf' -o -iname '*.ttc' -o -iname '*.otc' \) -print -quit | grep -q .; then
        echo "no font files found in $srcdir" >&2
        exit 1
    fi

    install -d "$fontdir"
    find "$srcdir" -type f \( -iname '*.ttf' -o -iname '*.otf' -o -iname '*.ttc' -o -iname '*.otc' \) \
        -exec install -Dm644 {} -t "$fontdir" \;
done
