#!/bin/sh -e

    meson \
        --prefix=/usr \
        -Ddefault_library=both \
        -Dfreetype=enabled \
        -Dgobject=enabled \
        -Dicu=disabled \
        -Dbenchmark=disabled \
        -Dtests=disabled \
        . output

    ninja -C output
    ninja -C output install

