#!/bin/bash -e

# A cross-system build installs into the target sysroot rather than the host's
# /usr, and configure needs --host so it stops probing the build machine.
PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS="--host=${HOKUTO_ARCH}-linux-gnu"
fi

./configure --prefix="$PREFIX" \
  --disable-static \
  $CROSS_OPTS

make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make clean
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"

./configure --prefix=/usr \
--libdir=/usr/lib32

make
make DESTDIR="${pkgdir}" install
rm -rf "${pkgdir}"/usr/{include,share,bin}
fi
