#!/bin/bash -e

# exit if not root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root!" >&2
    exit 1
fi
# Check if $LFS is set and not empty
if [ -z "$LFS" ]; then
    echo "Error: \$LFS environment variable is not set!" >&2
    exit 1
fi

echo "changing ownership of $LFS to root"
chown -vR root:root $LFS/*

echo "mounting virtual kernel file systems"
mount -v --bind /dev $LFS/dev
mount -vt devpts devpts -o gid=5,mode=0620 $LFS/dev/pts
mount -vt proc proc $LFS/proc
mount -vt sysfs sysfs $LFS/sys
mount -vt tmpfs tmpfs $LFS/run
if [ -h $LFS/dev/shm ]; then
  install -v -d -m 1777 $LFS$(realpath /dev/shm)
else
  mount -vt tmpfs -o nosuid,nodev tmpfs $LFS/dev/shm
fi

echo "mounting sources directory in chroot"
mkdir -vp $LFS/var/cache/kiss/sources
mount --bind /var/cache/kiss/sources $LFS/var/cache/kiss/sources

echo "copying repo to chroot"
cp -a /repo/sauzeros $LFS/repo/

cleanup() {
    echo "Unmounting virtual filesystems..."
    umount -v "$LFS/dev/shm" || true
    umount -v "$LFS/run" || true
    umount -v "$LFS/sys" || true
    umount -v "$LFS/proc" || true
    umount -v "$LFS/dev/pts" || true
    umount -v "$LFS/dev" || true
    umount -v "$LFS/var/cache/kiss/sources" || true
}
trap cleanup EXIT

echo "entering chroot"
chroot "$LFS" /usr/bin/env -i   \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='(lfs chroot) \u:\w\$ ' \
    PATH=/usr/bin               \
    MAKEFLAGS="-j$(nproc)"      \
    LOGNAME=root                \
    USER=root                   \
    KISS_PATH=/repo/sauzeros/core \
    KISS_DIRS=/var/cache/kiss   \
    KISS_COMPRESS=zst           \
    KISS_TMPDIR=/tmp            \
    /bin/bash --login
