#!/bin/sh -e

if hokuto check mpg123;
then CONFIG_MPG123="--enable-mp3rtp"
else
CONFIG_MPG123="--disable-mp3rtp --disable-decoder"
fi

# Disable HTML documentation.
sed 's/html man/man/' doc/Makefile.in > _
mv -f _ doc/Makefile.in

# fix
chmod +x configure

export CFLAGS+=" -Wno-implicit-function-declaration -Wno-incompatible-pointer-types"
./configure      \
  --prefix=/usr  \
  --enable-nasm  \
  $CONFIG_MPG123 \
  --enable-shared

make
make DESTDIR=$1 install
