[sauzeros]
description = "sauzerOS minimal install"
depends = [
"bash",
"coreutils",
"file",
"findutils",
"glibc",
"gzip",
"hokuto",
"iproute2",
"libgcc",
"libstdc++",
"nano",
"procps-ng",
"psmisc",
"sauzeros-base",
"shadow",
"systemd-libs",
"util-linux-libs",
]
[base-devel]
description = "base devel packages"
depends = [
"autoconf",
"automake",
"binutils",
"bison",
"file",
"findutils",
"flex",
"gawk",
"gcc",
"gettext",
"grep",
"gzip",
"libtool",
"m4",
"make",
"patch",
"pkgconf",
"sed",
"texinfo",
"which",
]
[kde-desktop]
description = "KDE Plasma"
depends = [
"aurorae",
"bluedevil",
"breeze",
"breeze-gtk",
"drkonqi",
"flatpak-kcm",
"kactivitymanagerd",
"kde-cli-tools",
"kde-gtk-config",
"kdecoration",
"kdeplasma-addons",
"kglobalacceld",
"kinfocenter",
"kmenuedit",
"knighttime",
"kpipewire",
"krdp",
"kscreen",
"kscreenlocker",
"ksshaskpass",
"ksystemstats",
"kwallet-pam",
"kwayland",
"kwin",
"kwrited",
"layer-shell-qt",
"libkscreen",
"libksysguard",
"libplasma",
"milou",
"ocean-sound-theme",
"oxygen",
"oxygen-sounds",
"plasma-activities",
"plasma-activities-stats",
"plasma-desktop",
"plasma-disks",
"plasma-firewall",
"plasma-integration",
"plasma-keyboard",
"plasma-login-manager",
"plasma-nm",
"plasma-pa",
"plasma-systemmonitor",
"plasma-thunderbolt",
"plasma-vault",
"plasma-welcome",
"plasma-workspace",
"polkit-kde-agent",
"powerdevil",
"print-manager",
"spectacle",
"systemsettings",
"xdg-desktop-portal-kde",
]
suggests = [
"breeze-plymouth suggest Breeze theme for Plymouth",
"kgamma suggest Adjust gamma settings on X",
"kwin-x11 suggest X11 window manager",
"plasma-workspace-wallpapers suggest Additional wallpapers",
"plasma-x11-session suggest Plasma X11 session",
"plymouth-kcm suggest Configure Plymouth from systemsettings",
"sddm-kcm suggest SDDM configuration module",
]
