[sauzeros]
description = "sauzerOS minimal install"
depends = [
"bash",
"coreutils",
"file",
"findutils",
"glibc",
"hokuto",
"iproute2",
"libgcc",
"libstdc++",
"nano",
"procps-ng",
"psmisc",
"sauzeros-base",
"shadow",
"systemd-libs",
"util-linux-libs",
]
[base-devel]
description = "base devel packages"
depends = [
"autoconf",
"automake",
"binutils",
"bison",
"file",
"findutils",
"flex",
"gawk",
"gcc",
"gettext",
"grep",
"gzip",
"libtool",
"m4",
"make",
"patch",
"pkgconf",
"sed",
"texinfo",
"which",
]
