#!/bin/sh -e

python -m build --wheel --no-isolation
python -m installer --destdir="$1" dist/*.whl

cd pydantic-core
python -m build --wheel --no-isolation
python -m installer --destdir="$1" dist/*.whl

