#!/bin/sh -e

CONFIGURE_ARGS=(
    --prefix="$CROSS_PREFIX"
    --enable-ipv6
    --enable-unix-sockets
    --enable-hidden-symbols
    --disable-manual
    --disable-ldap
    --disable-ares
    --with-openssl
    --with-pic
    --with-ca-fallback
    --without-librtmp
    --without-libidn
)

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CONFIGURE_ARGS+=( "--with-sysroot=/$HOKUTO_ARCH-linux-gnu" )
    CONFIGURE_ARGS+=( "--host=$HOKUTO_ARCH-linux-gnu" )
    CONFIGURE_ARGS+=( "--without-libpsl" )

fi

./configure \
    "${CONFIGURE_ARGS[@]}"

make
make DESTDIR="$1" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
CC="gcc -m32" CXX="g++ -m32"           \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig   \
./configure \
    --prefix=/usr \
    --host=i686-pc-linux-gnu \
    --libdir=/usr/lib32 \
    --enable-ipv6 \
    --enable-unix-sockets \
    --enable-hidden-symbols \
    --disable-manual \
    --disable-ldap \
    --disable-ares \
    --with-openssl \
    --with-pic \
    --with-ca-fallback \
    --without-librtmp \
    --without-libidn \
    --without-libidn2

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
fi
