#!/bin/sh -e

# Don't use bash
sed 's/SHELL = bash -o pipefail/SHELL = sh/g' Makefile > _
mv -f _ Makefile

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib/qemu \
    --disable-werror \
    --disable-tcg-interpreter \
    --enable-pie \
    --audio-drv-list=alsa \
    --enable-alsa \
    --enable-bzip2 \
    --enable-curl \
    --enable-curses \
    --disable-docs \
    --enable-kvm \
    --enable-libudev \
    --enable-libusb \
    --disable-linux-aio \
    --enable-linux-io-uring \
    --enable-opengl \
    --enable-png \
    --enable-sdl \
    --disable-sdl-image \
    --enable-virglrenderer \
    --disable-vnc-jpeg \
    --enable-xkbcommon \
    --enable-zstd \
    --enable-system \
    --enable-linux-user \
    --disable-debug-info

make
make PREFIX=/usr install
