#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib/qemu \
    --disable-werror \
    --disable-tcg-interpreter \
    --enable-pie \
    --audio-drv-list=alsa,pa,pipewire,sdl \
    --enable-bzip2 \
    --enable-curl \
    --enable-curses \
    --disable-docs \
    --enable-kvm \
    --enable-libudev \
    --enable-libusb \
    --disable-linux-aio \
    --enable-linux-io-uring \
    --enable-opengl \
    --enable-png \
    --enable-sdl \
    --enable-slirp \
    --disable-sdl-image \
    --enable-virglrenderer \
    --disable-vnc-jpeg \
    --enable-xkbcommon \
    --enable-zstd \
    --enable-system \
    --enable-linux-user \
    --disable-debug-info

meson compile -C build
meson install -C build --destdir=$1

install -vdm 755 "$1/usr/lib/binfmt.d/"
scripts/qemu-binfmt-conf.sh          \
  --systemd ALL                      \
  --exportdir "$1/usr/lib/binfmt.d/" \
  --qemu-path "/usr/bin"             \
  --persistent yes                   \
  --preserve-argv0 yes

install -vDm 644 bridge.conf -t "$1/etc/qemu/"
install -vDm 644 qemu.sasl "$1/etc/sasl2/qemu.conf"
install -vDm 644 qemu-sysusers.conf "$1/usr/lib/sysusers.d/qemu.conf"
install -vDm 644 99-qemu-guest-agent.rules -t "$1/usr/lib/udev/rules.d/"
install -vDm 644 qemu-ga.conf -t "$1/etc/$pkgbase/"
