#!/bin/sh -e

cmake -DCMAKE_BUILD_TYPE='None'        \
      -DCMAKE_INSTALL_PREFIX=/usr      \
      -DCMAKE_INSTALL_LIBEXECDIR='lib' \
      -DMOLD_LTO=ON                    \
      -B build

cmake --build build
DESTDIR=$1 cmake --build build --target install

