#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

cmake -B build -D BUILD_ICD=OFF \
      -D CMAKE_BUILD_TYPE=Release \
      -D CMAKE_INSTALL_PREFIX="$PREFIX"

cmake --build build
DESTDIR=$1 cmake --install build
