#!/bin/bash -e

# Build phase
cmake \
  -G 'Unix Makefiles' \
  -B build \
  -D CMAKE_BUILD_TYPE:STRING='None' \
  -D CMAKE_INSTALL_PREFIX:PATH='/usr' \
  -D CODE_COVERAGE:BOOL='OFF' \
  -W no-dev
cmake --build build
DESTDIR="${1}" cmake --install build
