#!/bin/sh -e

patch -p1 < rootless_modesetting.patch
patch -Np1 -i xf86-video-ati-19.1.0-upstream_fixes-1.patch

export LDFLAGS="$LDFLAGS -Wl,-z,lazy"
export CFLAGS="$CFLAGS -fcommon"

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install
