#!/bin/sh -e

sed 's/^FLAGS.*=/FLAGS = -static /' programs/Makefile > _
mv -f _ programs/Makefile

MAKE_ARGS="prefix=$CROSS_PREFIX CC=${CC:-gcc} AR=${AR:-ar}"

# Optimization logic for zstd
if echo "$CPUFLAGS" | grep -q "avx2"; then
    export CFLAGS="$CFLAGS -mavx2"
fi

make $MAKE_ARGS
make prefix="$CROSS_PREFIX" DESTDIR="$1" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit
make clean
CC="gcc -m32" make prefix=/usr
make prefix=/usr DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32/pkgconfig
cp -Rv DESTDIR/usr/lib/* $1/usr/lib32/
sed -e "/^libdir/s/lib$/lib32/" -i $1/usr/lib32/pkgconfig/libzstd.pc
fi
