#!/bin/sh -e

sed 's/^FLAGS.*=/FLAGS = -static /' programs/Makefile > _
mv -f _ programs/Makefile

make prefix="$CROSS_PREFIX" CC="${CC:-gcc}" AR="${AR:-ar}"
make prefix="$CROSS_PREFIX" DESTDIR="$1" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit
make clean
CC="gcc -m32" make prefix=/usr
make prefix=/usr DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32/pkgconfig
cp -Rv DESTDIR/usr/lib/* $1/usr/lib32/
sed -e "/^libdir/s/lib$/lib32/" -i $1/usr/lib32/pkgconfig/libzstd.pc
fi
