#!/bin/bash -e

patch -Np1 -i 0001-units-Enable-statically.patch
# src/util/{proc,apparmor}.c use LINE_MAX without including <limits.h>;
# they only ever compiled because another header pulled it in transitively.
# Newer glibc no longer does, so the build dies with "'LINE_MAX' undeclared".
patch -Np1 -i 0002-util-include-limits.h-for-LINE_MAX.patch

meson setup build \
  --prefix=/usr   \
  -D docs=false   \
  -D audit=false  \
  -D linux-4-17=true \
  -D system-console-users=gdm,sddm,lightdm,lxdm

meson compile -C build
meson install -C build --destdir=$1
