#!/bin/sh -e

# fix a typo in a sgml file:
sed -e 's/"app-pgchecksums "/"app-pgchecksums"/' \
    -i doc/src/sgml/ref/pg_combinebackup.sgml

# change server socket to /run/postgresql
sed -e '/DEFAULT_PGSOCKET_DIR/s@/tmp@/run/postgresql@' \
    -i src/include/pg_config_manual.h

# use fat LTO objects for static libraries
CFLAGS+=" -ffat-lto-objects"
CXXFLAGS+=" -ffat-lto-objects"

./configure       \
  --prefix=/usr   \
  --with-readline \
  --with-openssl  \
  --with-pam      \
  --with-icu      \
  --with-systemd  \
  --with-zstd     \
  --enable-thread-safety

make
make DESTDIR=$1 install
make -C contrib DESTDIR="$1" install

install -Dm 644 postgresql.pam "${1}/etc/pam.d/postgresql"
install -Dm 644 postgresql.service -t "${1}/usr/lib/systemd/system"
install -Dm 644 postgresql.sysusers "${1}/usr/lib/sysusers.d/postgresql.conf"
install -Dm 644 postgresql.tmpfiles "${1}/usr/lib/tmpfiles.d/postgresql.conf"

majorver=${2%%.*}
sed -e "s/%PGMAJORVERSION%/${majorver}/g" \
    -e "s/%PREVMAJORVERSION%/$((majorver - 1))/g" \
    postgresql-check-db-dir.in |
install -Dm755 /dev/stdin "${1}/usr/bin/postgresql-check-db-dir"
