#!/bin/sh

# Create group if missing
getent group postgres >/dev/null || groupadd -g 41 postgres

# Create user if missing
id -u postgres >/dev/null 2>&1 || useradd -c "PostgreSQL Server" -g postgres -d /srv/pgsql/data -u 41 -s /bin/false postgres

install -v -dm700 /srv/pgsql/data
install -v -dm755 /run/postgresql
chown -Rv postgres:postgres /srv/pgsql /run/postgresql

sudo -u postgres initdb -D /srv/pgsql/data
