#!/bin/sh -e

#gcc 15 fix
sed '/typedef enum/,/bool ;/d' -i \
  src/ALAC/alac_{en,de}coder.c

./configure \
    --prefix=/usr \
    --disable-static

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"
