#!/bin/bash -e

#gcc 15 fix
sed '/typedef enum/,/bool ;/d' -i \
  src/ALAC/alac_{en,de}coder.c

./configure \
    --prefix=/usr \
    --disable-static

make
make DESTDIR="$1" install

if [ "$MULTILIB" = "1" ]; then
#32bit split package
make distclean
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu

make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
