#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

MESON_OPTS=(
    --prefix="$PREFIX"
    --buildtype=release
)

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    MESON_OPTS+=(-D gi_cross_ldd_wrapper=/usr/share/meson/cross/aarch64-ldd
                 -D python=/usr/aarch64-linux-gnu/bin/python)
fi

hokuto-meson build "${MESON_OPTS[@]}"
meson compile -C build
meson install -C build --destdir=$1

if [ "${HOKUTO_CROSS:-0}" = "1" ] && [ "${PREFIX}" = "/usr" ]; then
sed -i '1s|.*|#!/usr/bin/env python3|' $1/usr/bin/g-ir-scanner
sed -i '1s|.*|#!/usr/bin/env python3|' $1/usr/bin/g-ir-annotation-tool
fi

