#!/bin/sh -e

cmake -B build \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_BUILD_TYPE=None \
    -D ZXING_EXAMPLES=OFF \
    -D ZXING_UNIT_TESTS=OFF \
    -D ZXING_C_API=ON

cmake --build build
DESTDIR="$1" cmake --install build
