#!/bin/sh -e

cd firefox-$2
mv ../mozconfig .
mv ../google-api-key .

# LTO
#WARNING_FLAGS="-Werror=odr -Werror=strict-aliasing"
COMMON_FLAGS="-march=native -O2 -flto=thin -pipe ${WARNING_FLAGS}"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

RUSTFLAGS="-C target-cpu=native -C strip=debuginfo -C opt-level=3 \
-Clinker=clang -Clinker-plugin-lto -Clink-arg=-fuse-ld=lld"

LDFLAGS="${COMMON_FLAGS} ${LDFLAGS} -fuse-ld=lld -flto=thin"
CC="clang"
CXX="clang++"
CPP="clang-cpp"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"

export MOZILLA_OFFICIAL=1
export MOZ_NOSPAM=1
export RUST_MIN_STACK=16777216
ulimit -n 4096

export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=none
export MOZBUILD_STATE_PATH=${PWD}/mozbuild

./mach build $MAKEFLAGS --priority normal

export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=none
DESTDIR=$1 ./mach install

# Desktop file & icon
install -d $1/usr/share/applications
install -d $1/usr/share/icons/hicolor/symbolic/apps
install -Dvm644 ../firefox.desktop $1/usr/share/applications/
install -Dvm644 ../firefox-symbolic.svg -t "$1/usr/share/icons/hicolor/symbolic/apps"

# Install desktop icons and metadata
theme=official
for i in 16 22 24 32 48 64 128 256; do
install -Dvm644 browser/branding/$theme/default$i.png \
"$1/usr/share/icons/hicolor/${i}x${i}/apps/firefox.png"
done
install -Dvm644 browser/branding/$theme/content/about-logo.png \
"$1/usr/share/icons/hicolor/192x192/apps/firefox.png"
install -Dvm644 browser/branding/$theme/content/about-logo@2x.png \
"$1/usr/share/icons/hicolor/384x384/apps/firefox.png"
install -Dvm644 browser/branding/$theme/content/about-logo.svg \
"$1/usr/share/icons/hicolor/scalable/apps/firefox.svg"

# distribution
  install -Dvm644 /dev/stdin "$1/usr/lib/$3/distribution/distribution.ini" <<END
[Global]
id=sauzerOS
version=1.0
about=Mozilla Firefox for sauzerOS

[Preferences]
app.distributor=sauzeros
app.distributor.channel=$3
app.partner.archlinux=sauzeros
END
