#!/bin/sh -e

cat > .mozconfig << EOF
ac_add_options --prefix=/usr
ac_add_options --libdir=/usr/lib
ac_add_options --enable-default-toolkit=cairo-gtk3
ac_add_options --enable-strip
ac_add_options --enable-release
ac_add_options --enable-rust-simd
ac_add_options --enable-install-strip
ac_add_options --enable-official-branding
ac_add_options --enable-application=browser
ac_add_options --enable-optimize
ac_add_options --with-system-ffi
ac_add_options --with-system-jpeg
ac_add_options --with-system-libvpx
ac_add_options --with-system-nspr
ac_add_options --with-system-nss
ac_add_options --with-system-pixman
ac_add_options --with-system-png
ac_add_options --with-system-webp
ac_add_options --with-system-zlib
ac_add_options --without-wasm-sandboxed-libraries
ac_add_options --disable-eme
ac_add_options --disable-tests
ac_add_options --disable-vtune
ac_add_options --disable-updater
ac_add_options --disable-jemalloc
ac_add_options --disable-elf-hack
ac_add_options --disable-callgrind
ac_add_options --disable-profiling
ac_add_options --disable-necko-wifi
ac_add_options --disable-crashreporter
ac_add_options --disable-accessibility
ac_add_options --disable-debug
ac_add_options --disable-debug-symbols
ac_add_options --disable-parental-controls
ac_add_options --disable-system-extension-dirs
EOF

sed -e "/match cursor.kind()/a                                    \
        CXCursor_LinkageSpec => return Err(ParseError::Recurse)," \
    -i third_party/rust/bindgen/ir/item.rs                        &&

cat >> Cargo.toml << EOF &&
[patch.crates-io.bindgen_0_64_0]
package = "bindgen"
version = "0.64.0"
path = "third_party/rust/bindgen"
EOF

sed -r '/name = "bindgen"/,+5 s/^source|^checksum/#&/' \
    -i Cargo.lock

sed 's/uint32_t timestamp/uint64_t timestamp/'                \
    -i dom/media/gmp-plugin-openh264/gmp-fake-openh264.cpp    \
       dom/media/gtest/TestGMPRemoveAndDelete.cpp             \
       dom/media/webrtc/libwebrtcglue/WebrtcGmpVideoCodec.cpp &&

sed '/mInputImageMap/s/uint32_t/uint64_t/' \
    -i dom/media/webrtc/libwebrtcglue/WebrtcGmpVideoCodec.h

sed '/cfg_attr/,/)]/d' -i gfx/qcms/src/lib.rs

export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=none
export MOZBUILD_STATE_PATH=${PWD}/mozbuild
./mach build

export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=none
DESTDIR=$1 ./mach install

# Remove a lot of uneeded "stuff".
rm -rf \
    "$1/usr/include" \
    "$1/usr/lib/firefox-devel" \
    "$1/usr/share/idl"

# Desktop file
mkdir -p $1/usr/share/applications
cp firefox.desktop $1/usr/share/applications/
