#!/bin/sh -e

make \
	VAL_PREFIX=/usr \
	VAL_SYSCONFDIR=/etc \
	VAL_LIBEXECDIR=/usr/lib \
	VAL_MAIL=/var/spool/mail \
	VAL_SID= VAL_MAILX=mail \
	OPT_AUTOCC=0 \
	config

make build
make DESTDIR="${1}" install
ln -sf mail "${1}"/usr/bin/mailx
ln -sf mail.1.gz "${1}"/usr/share/man/man1/mailx.1.gz
