#!/bin/sh -e

install -d $1/usr/lib/firmware
cp -r rtlwifi $1/usr/lib/firmware
# compress firmware
find $1/usr/lib/firmware -type f -exec xz -C crc32 -T0 "{}" \;

# symlinks
ln -s rtl8192eu_nic.bin.xz $1/usr/lib/firmware/rtlwifi/rtl8192eefw.bin.xz
ln -s rtl8723bu_ap_wowlan.bin.xz $1/usr/lib/firmware/rtlwifi/rtl8723bs_ap_wowlan.bin.xz
ln -s rtl8723bu_nic.bin.xz $1/usr/lib/firmware/rtlwifi/rtl8723bs_nic.bin.xz
ln -s rtl8723bu_wowlan.bin.xz $1/usr/lib/firmware/rtlwifi/rtl8723bs_wowlan.bin.xz
