#!/bin/sh -e

patch -Np1 -i libpng-$2-apng.patch

cmake -B build                 \
  -D CMAKE_BUILD_TYPE=Release  \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D BUILD_SHARED_LIBS=ON      \
  -D PNG_TESTS=OFF             \
  -D PNG_STATIC=OFF            \
  -D PNG_SHARED=ON             \
  -D PNG_TOOLS=OFF

cmake --build build
DESTDIR=$1 cmake --install build

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --disable-static

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
fi
