#!/bin/bash -e

hokuto-meson build \
  -D pixbuf-loader=disabled

meson compile -C build
meson install -C build --destdir=$1

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
rm -rf build
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
hokuto-meson-32 build                \
  -D avif=disabled                   \
  -D docs=disabled                   \
  -D introspection=disabled          \
  -D pixbuf-loader=enabled           \
  -D triplet=i686-unknown-linux-gnu  \
  -D vala=disabled

meson compile -C build
meson install -C build --destdir="$pkgdir"
rm -r "$pkgdir"/usr/{bin,include,share}
fi
