#!/bin/bash -e

export CC=x86_64-w64-mingw32-gcc
export CFLAGS="-O2 -pipe"

mkdir build-x86_64-winpthreads
cd    build-x86_64-winpthreads

../mingw-w64-libraries/winpthreads/configure \
            --prefix=/usr/x86_64-w64-mingw32 \
            --host=x86_64-w64-mingw32
make
make DESTDIR=$1 install

# remove headers already provided by mingw-w64
rm -f "$1"/usr/x86_64-w64-mingw32/include/pthread_{signal,time,unistd}.h


if [ "$MULTILIB" = "1" ]; then
# 32-bit
cd ..

export CC=i686-w64-mingw32-gcc

mkdir build-i686-winpthreads
cd    build-i686-winpthreads

../mingw-w64-libraries/winpthreads/configure \
            --prefix=/usr/i686-w64-mingw32   \
            --host=i686-w64-mingw32

make
make DESTDIR=$1 install

# remove headers already provided by mingw-w64
rm -f "$1"/usr/i686-w64-mingw32/include/pthread_{signal,time,unistd}.h
fi
