#!/bin/sh -e


  install -Dm0644 --target-directory "$1/usr/share/pixmaps" "img/zerotier-gui.png"
  install -Dm0644 --target-directory "$1/usr/share/applications" "zerotier-gui.desktop"
  install -Dm0755 --target-directory "$1/usr/bin" "src/zerotier-gui"









