#!/bin/sh -e

export LDFLAGS="-fuse-ld=lld"

cmake -B build -D ENABLE_CUDA_DES_MULTIPLE_KERNELS_MODE=ON
cmake --build build
install -Dm 755 build/MerikensTripcodeEngine $1/opt/meriken/MerikensTripcodeEngine
