#!/bin/sh -e

ar x google-chrome-stable_*amd64.deb
tar -xf data.tar.xz -C "$1/"

rm -r "$1"/etc/cron.daily/ 
rm -r "$1"/opt/google/chrome/cron/

#remove libwidevinecdm (segfaults on my system)
rm -r "$1"/opt/google/chrome/WidevineCdm/

# Icons
	for i in 16x16 24x24 32x32 48x48 64x64 128x128 256x256; do
		install -Dm644 "$1"/opt/google/chrome/product_logo_${i/x*/}.png \
			"$1"/usr/share/icons/hicolor/$i/apps/google-chrome.png
	done

echo "  -> Fixing Chrome desktop entry..."
	sed -i \
		-e "/Exec=/i\StartupWMClass=Google-chrome" \
		-e "s/x-scheme-handler\/ftp;\?//g" \
		"$1"/usr/share/applications/google-chrome.desktop

	sed -i "s/Icon=google-chrome/Icon=\/usr\/share\/icons\/hicolor\/48x48\/apps\/google-chrome.png/g" \
	"$1"/usr/share/applications/google-chrome.desktop
