#!/bin/sh -e


patch -Np1 -i qt-everywhere-opensource-src-5.15.9-kf5-1.patch

# Without this folder, Qt can't find its header files.
mkdir .git
mkdir -pv qtbase/.git

#GCC 13 fix
sed -e "/pragma once/a#include <cstdint>"                                      \
    -i qtlocation/src/3rdparty/mapbox-gl-native/include/mbgl/util/geometry.hpp \
       qtlocation/src/3rdparty/mapbox-gl-native/include/mbgl/util/string.hpp   \
       qtlocation/src/3rdparty/mapbox-gl-native/src/mbgl/gl/stencil_mode.hpp

./configure \
    -confirm-license \
    -opensource \
    -prefix /usr \
    -docdir /usr/share/doc/qt \
    -headerdir /usr/include/qt \
    -archdatadir /usr/lib/qt \
    -datadir /usr/share/qt \
    -sysconfdir /etc/xdg \
    -examplesdir /usr/share/doc/qt/examples \
    -nomake examples \
    -nomake tests \
    -optimized-qmake \
    -no-separate-debug-info \
    -dbus-linked \
    -openssl-linked \
    -system-libjpeg \
    -system-libpng \
    -system-sqlite \
    -system-zlib \
    -system-freetype \
    -system-harfbuzz \
    -silent

make
make INSTALL_ROOT="$1" install

install -Dm755 qt.conf "$1/usr/bin/qt.conf"
