#!/bin/sh -e

# Without this folder, Qt can't find its header files.
mkdir .git
mkdir -pv qtbase/.git

  ./configure -confirm-license -opensource -v \
    -prefix /usr \
    -docdir /usr/share/doc/qt \
    -headerdir /usr/include/qt \
    -archdatadir /usr/lib/qt \
    -datadir /usr/share/qt \
    -sysconfdir /etc/xdg \
    -examplesdir /usr/share/doc/qt/examples \
    -plugin-sql-sqlite \
    -system-sqlite \
    -openssl-linked \
    -nomake examples \
    -no-rpath \
    -dbus-linked \
    -system-harfbuzz \
    -journald \
    -no-mimetype-database \
    -no-use-gold-linker \
    -no-reduce-relocations \
    -no-strip \
    -ltcg



make
make INSTALL_ROOT="$1" install

 # Drop QMAKE_PRL_BUILD_DIR because reference the build dir
  find "${1}/usr/lib" -type f -name '*.prl' \
    -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;
  # Symlinks for backwards compatibility
  for b in "${1}"/usr/bin/*; do
    ln -s $(basename $b) "${1}"/usr/bin/$(basename $b)-qt5
  done

install -d -m755 "$1"/usr/include/qtxcb-private
cp -r src/plugins/platforms/xcb/*.h "$1"/usr/include/qtxcb-private/


