#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

export SETUPTOOLS_SCM_PRETEND_VERSION=$2
python -m build --wheel --no-isolation --skip-dependency-check
python -m installer --destdir="$1" --prefix="$PREFIX" dist/*.whl
