#!/bin/sh -e

python -m build --wheel --no-isolation
python -m installer --destdir="$1" dist/*.whl

for f in cygdb cython cythonize; do
    mv "$1"/usr/bin/$f "$1"/usr/bin/${f}3
    ln -s ${f}3 "$1"/usr/bin/$f
done
