#!/bin/sh -e

# Use CROSS_PREFIX if set (defaults to /usr in hokuto)
PREFIX="${CROSS_PREFIX:-/usr}"

# triplet for --host
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"

    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure \
    --prefix="$PREFIX" \
    --sbindir="$PREFIX/bin" \
    --libdir="$PREFIX/lib" \
    --enable-libargon2 \
    --disable-ssh-token \
    --disable-asciidoc \
    --disable-static \
    --with-tmpfilesdir="${PREFIX}/lib/tmpfiles.d" \
    --with-modprobedir="${PREFIX}/lib/modprobe.d" \
    $CROSS_OPTS

make
make DESTDIR="$1" install

# Fix incorrect paths from cross-compilation (autotools + pkg-config often default to sysroot)
if [ "${HOKUTO_CROSS:-0}" = "1" ] && [ "$PREFIX" = "/usr" ]; then
    if [ -d "$1$PREFIX/$HOKUTO_ARCH-linux-gnu" ]; then
        echo "Moving files from sysroot $1$PREFIX/$HOKUTO_ARCH-linux-gnu to $1$PREFIX"
        cp -rl "$1$PREFIX/$HOKUTO_ARCH-linux-gnu/"* "$1$PREFIX/"
        rm -rf "$1$PREFIX/$HOKUTO_ARCH-linux-gnu"
    fi
fi
