#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-rpath \
    --disable-doxygen-docs \
    --disable-xmms-plugin \
    --disable-thorough-tests \
    --with-pic

make
make DESTDIR="$1" install

#32bit

make distclean
CC="gcc -m32" CXX="g++ -m32"         \
CFLAGS+=" -L/usr/lib32"              \
CXXFLAGS+=" -L/usr/lib32"            \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --disable-thorough-tests

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
