#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi

./configure \
    --prefix="$PREFIX" \
    --disable-rpath \
    --disable-doxygen-docs \
    --disable-xmms-plugin \
    --disable-thorough-tests \
    --with-pic \
    "${CROSS_OPTS[@]}"

make
make DESTDIR="$1" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit split package
make distclean
CC="gcc -m32" CXX="g++ -m32"         \
CFLAGS+=" -L/usr/lib32"              \
CXXFLAGS+=" -L/usr/lib32"            \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --disable-thorough-tests

make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
