#!/bin/bash -e

# Fix https://bugs.archlinux.org/task/38428
sed -i "s|/etc/timidity.cfg|/etc/timidity/timidity.cfg|g" src/codecs/music_timidity.c

./configure \
    --enable-music-mod-modplug \
    --enable-music-ogg-vorbis \
    --enable-music-flac-libflac \
    --enable-music-mp3-mpg123 \
    --disable-music-ogg-stb \
    --disable-music-flac-drflac \
    --disable-music-mp3-drmp3 \
    --disable-static \
    --prefix=/usr

make
make DESTDIR="${1}" install
