#!/bin/sh -e

./autogen.sh
./configure \
    --prefix=/usr \
    --disable-static \
    --enable-extras \
    --disable-ldconfig \
    --sbin=/usr/bin \
    --with-fuse=external

make
make DESTDIR="$1" rootbindir=/usr/bin rootsbindir=/usr/bin rootlibdir=/usr/lib install
