#!/bin/sh -e

patch -Np1 -i docbook-xsl-nons-$2-stack_fix-1.patch

install -v -m755 -d "$1/usr/share/xml/docbook/xsl-stylesheets-nons-${2}"

cp -v -R VERSION common eclipse epub extensions fo highlighting html \
    htmlhelp images javahelp lib manpages params profiling \
    roundtrip slides template tests tools webhelp website \
    xhtml xhtml-1_1 \
    "$1/usr/share/xml/docbook/xsl-stylesheets-nons-${2}"

ln -s VERSION "$1/usr/share/xml/docbook/xsl-stylesheets-nons-${2}/VERSION.xsl"


