#!/bin/bash -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-static

make
make DESTDIR="$1" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make clean
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
export CC='gcc -m32'
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
./configure \
  --prefix=/usr \
  --libdir=/usr/lib32 \
  --localstatedir=/var \
  --sysconfdir=/etc \
  --disable-bash-completion \
  --disable-checks \
  --disable-gtk-doc \
  --disable-static

make
make DESTDIR="${pkgdir}" install
rm -rf "${pkgdir}"/usr/{bin,include,share}
fi
