#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
SYSCONFDIR=/etc
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # The build runs dbus-binding-tool, so it takes the build machine's.
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu"
        --with-dbus-binding-tool=/usr/bin/dbus-binding-tool)
    [ "$PREFIX" != /usr ] && SYSCONFDIR="$PREFIX/etc"
fi

./configure \
    --prefix="$PREFIX" \
    --sysconfdir="$SYSCONFDIR" \
    --disable-static "${CROSS_OPTS[@]}"

make
make DESTDIR="$1" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make clean
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
export CC='gcc -m32'
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
./configure \
  --prefix=/usr \
  --libdir=/usr/lib32 \
  --localstatedir=/var \
  --sysconfdir=/etc \
  --disable-bash-completion \
  --disable-checks \
  --disable-gtk-doc \
  --disable-static

make
make DESTDIR="${pkgdir}" install
rm -rf "${pkgdir}"/usr/{bin,include,share}
fi
