#!/bin/bash -e

# qt6: fix build against Qt 6.9+
git cherry-pick -n 796053d2eebe4532aad6bd3fd80cdf3b197806ec

meson setup build         \
  --prefix=/usr           \
  -D docs=false           \
  -D backend-qt5=disabled \
  -D tests=false

meson compile -C build
meson install -C build --destdir=$1
