#!/bin/sh -e

cd thunderbird-$2
mv ../mozconfig .
mv ../google-api-key .

# patches
patch -Np1 -i ../thunderbird-147.0.2-glibc-2.43.patch
patch -Np1 -i ../clang22-wasm32-wasip1.patch
patch -Np1 -i ../missing-include.patch
patch -Np1 -i ../encoding_rs-simd-select.patch

sed -e 's|73114a5c28472e77082ad259113ffafb418ed602c1741f26da3e10278b0bf93e|a88d6cc10ec1322b53a8f4c782b5133135ace0fdfcf03d1624b768788e17be0f|' \
  -i third_party/rust/mp4parse/.cargo-checksum.json
sed -e 's|880c982df0843cbdff38b9f9c3829a2d863a224e4de2260c41c3ac69e9148ad4|239b3e4d20498f69ed5f94481ed932340bd58cb485b26c35b09517f249d20d11|' \
  -i third_party/rust/bindgen/.cargo-checksum.json

# clear cargo checksums for glslopt after patching threads_posix.h
for f in third_party/rust/glslopt/.cargo-checksum.json comm/third_party/rust/glslopt/.cargo-checksum.json; do
  sed -i 's/"files":{[^}]*}/"files":{}/' $f
done

# Clear cargo checksum for encoding_rs
sed -i -e 's/\("files":{\)[^}]*/\1/' \
comm/third_party/rust/encoding_rs/.cargo-checksum.json

# Set BOTAN_VERSION from system-botan
_botan_ver=$(pkg-config --modversion botan-3)
sed -i "s|crypto_backend_version = CONFIG\[\"BOTAN_VERSION\"\]|crypto_backend_version = CONFIG[\"BOTAN_VERSION\"] or \"${_botan_ver}\"|" \
comm/third_party/rnp/moz.build

# Make icon transparent
sed -i '/^<rect/d' comm/mail/branding/thunderbird/TB-symbolic.svg

# use llvm
CC="clang"
CXX="clang++"
CPP="clang-cpp"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"

export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=none
export MOZBUILD_STATE_PATH=$(pwd)/mozbuild
export MOZ_NOSPAM=1

# Set remoting name to fix the missing wayland icon
export MOZ_APP_REMOTINGNAME=org.mozilla.Thunderbird

# malloc_usable_size is used in various parts of the codebase
CFLAGS="${CFLAGS/_FORTIFY_SOURCE=3/_FORTIFY_SOURCE=2}"
CFLAGS="${CFLAGS/-fexceptions/}"
CXXFLAGS="${CXXFLAGS/_FORTIFY_SOURCE=3/_FORTIFY_SOURCE=2}"
CXXFLAGS="${CXXFLAGS/-fexceptions/}"

./mach configure
./mach build
DESTDIR=$1 ./mach install

# Desktop file
install -Dm 644 ../thunderbird.desktop $1/usr/share/applications/thunderbird.desktop

for i in 16 22 24 32 48 64 128 256; do
install -Dm644 comm/mail/branding/thunderbird/default${i}.png \
  "$1/usr/share/icons/hicolor/${i}x${i}/apps/org.mozilla.Thunderbird.png"
done
install -Dm644 comm/mail/branding/thunderbird/TB-symbolic.svg \
  "$1/usr/share/icons/hicolor/symbolic/apps/thunderbird-symbolic.svg"
