#!/bin/bash -e

./bootstrap.sh \
    --prefix="$1/usr" \
    --with-icu \
    --with-python=/usr/bin/python3

for action in stage install; do
    ./b2 $action \
        variant=release \
        debug-symbols=off \
        threading=multi
done


# boost-libs
_pick "$1" boost-libs usr/lib/libboost_*
_pick "$1" boost-libs usr/lib/python*/site-packages/boost/
