#!/bin/sh -e

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure --prefix="$PREFIX" \
    --disable-static  \
    --libexecdir="$PREFIX/lib" \
    $CROSS_OPTS

make
make DESTDIR="$1" install

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
rm -rf $1/usr/include
fi

