#!/bin/sh -e

cargo fetch --locked --target "$(rustc -vV | sed -n 's/host: //p')"
cargo build --frozen --release

install -Dm755 "target/release/halloy" "${1}/usr/bin/halloy"
install -Dm644 "assets/linux/org.squidowl.halloy.appdata.xml" -t "${1}/usr/share/metainfo"
install -Dm644 org.squidowl.halloy.desktop -t "${1}/usr/share/applications"
install -Dm755 halloy-wrapper $1/usr/bin

install -d $1/usr/share
cp -dr assets/linux/icons "${1}/usr/share"
