#!/bin/sh -e

sed -i "s/if not version_info.contains('git')/if version_info.length() >= 4/" server/meson.build
sed -i "/meson-dist/d" meson.build

hokuto-meson build \
  -D gstreamer=no  \
  -D tests=false

meson compile -C build
meson install -C build --destdir=$1
