#!/bin/bash -e

cmake -B build                    \
  -D CMAKE_INSTALL_PREFIX=/usr    \
  -D CMAKE_INSTALL_LIBEXECDIR=lib \
  -D CORROSION_BUILD_TESTS=OFF

cmake --build build
DESTDIR="${1}" cmake --install build
