#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi

autoreconf -fvi
./configure \
  --prefix="$PREFIX" \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --disable-gtk2-engine \
  "${CROSS_OPTS[@]}"

make
make DESTDIR="${1}" install
make -C themes/HighContrast/gtk-2.0 DESTDIR="${1}" uninstall
