#!/bin/bash -e

libtoolize --force --copy
aclocal
autoheader
automake --add-missing --include-deps --copy
autoconf

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi

./configure \
  --prefix="$PREFIX" "${CROSS_OPTS[@]}" \
  --enable-automated \
  --enable-basic \
  --enable-console \
  --enable-test \
  --enable-shared \
  --enable-static

make
make DESTDIR="${1}/" install
