#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --disable-nls

make
make DESTDIR="$1" install

# Disable file size check for ffmpegthumbnailer
sed '73s/.*/MaxFileSize=0/' -i "$1/etc/xdg/tumbler/tumbler.rc"
