#!/bin/bash -e

cmake -B build                        \
  -D CMAKE_INSTALL_PREFIX=/usr        \
  -D CMAKE_INSTALL_LIBDIR=lib         \
  -D CMAKE_POLICY_VERSION_MINIMUM=3.5 \
  -D CMAKE_CXX_FLAGS="${CXXFLAGS} -fPIC -ffat-lto-objects"

cmake --build build
DESTDIR="${1}" cmake --install build
