#!/bin/bash -e

sed -i "s/^PROJECT_LOGO/#&/" doc/doxygen.cfg.in

PREFIX="${CROSS_PREFIX:-/usr}"

cross_opts=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    cross_opts=(--host="${HOKUTO_ARCH}-linux-gnu")
fi

./configure --prefix="$PREFIX" --disable-static "${cross_opts[@]}"
make -j1
make DESTDIR="$1" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make distclean
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
install -d $pkgdir
export CC="gcc -m32"
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"

./configure --prefix=/usr \
  --libdir=/usr/lib32     \
  --disable-static
# prevent excessive overlinking due to libtool
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make DESTDIR="$pkgdir" install
rm -rf "$pkgdir"/usr/include
fi
