#!/bin/sh -e

export CGO_LDFLAGS="${LDFLAGS}"
export CGO_CFLAGS="${CFLAGS}"
export CGO_CPPFLAGS="${CPPFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"
export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
export MINIO_RELEASE="RELEASE"
  GO_LDFLAGS="\
      -linkmode=external \
      -compressdwarf=false \
      $(go run buildscripts/gen-ldflags.go)"

go build -ldflags "$GO_LDFLAGS" .
install -dm750 -o 103 -g 103 "${1}/srv/minio"
install -dm750 -o 103 -g 103 "${1}/var/lib/minio"

install -Dm755 "minio" "${1}/usr/bin/minio"
install -Dm600 "minio.conf" "${1}/etc/minio/minio.conf"
install -Dm644 "minio.service" "${1}/usr/lib/systemd/system/minio.service"
install -Dm644 "minio.sysusers" "${1}/usr/lib/sysusers.d/minio.conf"
