#!/bin/sh -e

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    case "$HOKUTO_ARCH" in
        aarch64) GOARCH=arm64 ;;
        x86_64)  GOARCH=amd64 ;;
        *)       GOARCH=$HOKUTO_ARCH ;;
    esac
    export GOARCH
    export CGO_ENABLED=0
fi

export MINIO_RELEASE="RELEASE"

if [ "${CGO_ENABLED:-1}" = "0" ]; then
    # Cross-compilation or non-CGO build
    GO_LDFLAGS="-s -w $(go run buildscripts/gen-ldflags.go)"
    go build -ldflags "$GO_LDFLAGS" .
else
    # Standard build with CGO
    export CGO_LDFLAGS="${LDFLAGS}"
    export CGO_CFLAGS="${CFLAGS}"
    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_CXXFLAGS="${CXXFLAGS}"
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
    
    GO_LDFLAGS="\
        -linkmode=external \
        -compressdwarf=false \
        $(go run buildscripts/gen-ldflags.go)"
    go build -ldflags "$GO_LDFLAGS" .
fi

install -dm750 -o 103 -g 103 "${1}/srv/minio"
install -dm750 -o 103 -g 103 "${1}/var/lib/minio"

install -Dm755 "minio" "${1}/usr/bin/minio"
install -Dm600 "minio.conf" "${1}/etc/minio/minio.conf"
install -Dm644 "minio.service" "${1}/usr/lib/systemd/system/minio.service"
install -Dm644 "minio.sysusers" "${1}/usr/lib/sysusers.d/minio.conf"
