#!/bin/sh -e

# Setup base directories.
for d in boot dev etc home mnt repo usr var opt run swap; do
    install -dm 755 "$1/$d"
done

install -dm 555  "$1/proc"
install -dm 555  "$1/sys"
install -dm 0750 "$1/root"
install -dm 1777 "$1/tmp"
install -dm 755 "$1/etc/profile.d"

# Setup /usr hierarchy.
for d in bin include lib lib32 share src; do
    install -dm 755 "$1/usr/$d"
done

# Setup manpages directories.
for d in 1 2 3 4 5 6 7 8; do
    install -dm 755 "$1/usr/share/man/man$d"
done

# Add symlinks.
ln -s usr/bin "$1/bin"
ln -s usr/bin "$1/sbin"
ln -s bin     "$1/usr/sbin"
ln -s usr/lib "$1/lib"
ln -s usr/lib32 "$1/lib32"
ln -s usr/lib "$1/lib64"
ln -s lib     "$1/usr/lib64"

# Setup /var.
for d in cache local opt log/old lib/misc empty service; do
    install -dm 755 "$1/var/$d"
done

install -dm 1777 "$1/var/tmp"
install -dm 1777 "$1/var/tmpdir"
install -dm 1777 "$1/var/spool/mail"

ln -s spool/mail  "$1/var/mail"
ln -s ../run      "$1/var/run"
ln -s ../run/lock "$1/var/lock"

# Setup /usr/local
for d in bin etc games include lib man sbin share src; do
    install -dm 755 "$1/usr/local/$d"
done

ln -s ../man "$1/usr/local/share/man"

# /etc skeleton files.
for f in bashrc fstab group host.conf hosts issue inputrc locale.conf os-release \
         nanorc passwd profile resolv.conf securetty shells mime.types; do
    install -m 644 "$f" "$1/etc"
done

for f in crypttab ; do
    install -m 600 "$f" "$1/etc"
done

ln -s /proc/self/mounts "$1/etc/mtab"

# Setup cross-compilation directories (aarch64-linux-gnu)
# This ensures the sysroot structure exists even if specific packages are removed.
for arch in aarch64-linux-gnu; do
    CROSS_DIR="$1/usr/$arch"
    install -dm 755 "$CROSS_DIR/usr/lib"
    install -dm 755 "$CROSS_DIR/usr/bin"
    install -dm 755 "$CROSS_DIR/usr/sbin"
    install -dm 755 "$CROSS_DIR/usr/share"
    install -dm 755 "$CROSS_DIR/usr/include"

    # Create sysroot structure compatibility symlinks
    ln -s usr/lib    "$CROSS_DIR/lib"
    ln -s usr/lib    "$CROSS_DIR/lib64"
    ln -s usr/bin    "$CROSS_DIR/bin"
    ln -s usr/bin    "$CROSS_DIR/sbin"
    ln -s usr/share  "$CROSS_DIR/share"
    ln -s usr/include "$CROSS_DIR/include"
done

# Setup hokuto cache dirs
install -dm 1777 "$1/var/cache/hokuto"

# Setup hokuto conf
install -d $1/etc/hokuto
install -d $1/etc/hokuto/keys
install -Dm 644 hokuto.conf "$1/etc/hokuto/hokuto.conf"

# Setup config.site
install -Dm644 config.site "$1/usr/share/config.site"

# Set multilib setting
if [ "$MULTILIB" = "1" ]; then
sed -i 's/^HOKUTO_MULTILIB=0$/HOKUTO_MULTILIB=1/' "$1/etc/hokuto/hokuto.conf"
fi

# Set GNU Mirror
sed -i "s|^GNU_MIRROR=.*|GNU_MIRROR=$GNU_MIRROR|" "$1/etc/hokuto/hokuto.conf"

# Set LTO
sed -i "s/^HOKUTO_LTO=.*/HOKUTO_LTO=$SET_HOKUTO_LTO/" "$1/etc/hokuto/hokuto.conf"

# Set CFLAGS
if [ "$HOKUTO_GENERIC" = "1" ]; then
CFLAGS_GEN=$(sed -n 's/^CFLAGS_GEN=//p' "$1/etc/hokuto/hokuto.conf")
CXXFLAGS_GEN=$(sed -n 's/^CFLAGS_GEN=//p' "$1/etc/hokuto/hokuto.conf")
sed -i "s|^CFLAGS=.*|CFLAGS=${CFLAGS_GEN}|" "$1/etc/hokuto/hokuto.conf"
sed -i "s|^CXXFLAGS=.*|CXXFLAGS=${CXXFLAGS_GEN}|" "$1/etc/hokuto/hokuto.conf"
fi
