#!/bin/bash -e

mkdir build
cd build

../configure --prefix=/usr          \
             --with-system-readline \
             --with-system-zlib

make
make -C gdb DESTDIR="$1" install
make -C gdbserver DESTDIR="$1" install
