#!/bin/sh -e

mkdir build
cd build

meson --prefix=/usr                             \
      --buildtype=release                       \
      -Dgtk_doc=false                           \
      -Dlibnma_gtk4=true			\
      -Dmobile_broadband_provider_info=false ..

ninja
DESTDIR=$1 ninja install
