#!/bin/sh -e

meson setup build     \
  --prefix=/usr       \
  --buildtype=release \
  -D gtk_doc=false    \
  -D libnma_gtk4=true \
  -D mobile_broadband_provider_info=false

meson compile -C build
meson install -C build --destdir=$1
