#!/bin/sh -e

#gcc 15 fix
sed -i '/long long t1;/,+1s/()/(...)/' configure

#don't optimize for host
#cp -v configfsf.guess config.guess
#cp -v configfsf.sub   config.sub

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_OPT="--host=${HOKUTO_ARCH}-linux-gnu"
    # Ensure generic build for cross-compilation
    cp -v configfsf.guess config.guess
    cp -v configfsf.sub   config.sub
else
    HOST_OPT=""
fi

./configure --prefix=${CROSS_PREFIX:-/usr} \
            --enable-cxx     \
            --disable-static \
            $HOST_OPT

make
make DESTDIR=$1 install

if [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
cp -v configfsf.guess config.guess
cp -v configfsf.sub   config.sub
ABI="32" \
CFLAGS="-m32 -O2 -pedantic -fomit-frame-pointer -mtune=generic -march=i686" \
CXXFLAGS="$CFLAGS" \
PKG_CONFIG_PATH="/usr/lib32/pkgconfig" \
./configure                      \
    --host=i686-pc-linux-gnu     \
    --prefix=/usr                \
    --disable-static             \
    --enable-cxx                 \
    --libdir=/usr/lib32          \
    --includedir=/usr/include/m32/gmp
sed -i 's/$(exec_prefix)\/include/$\(includedir\)/' Makefile
make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
install -d $1/usr/include/m32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
cp -Rv DESTDIR/usr/include/m32/* $1/usr/include/m32/
fi
