#!/bin/sh -e

cd openssh*
./configure --prefix=/usr                            \
            --sysconfdir=/etc/ssh                    \
            --with-privsep-path=/var/lib/sshd        \
            --with-default-path=/usr/bin             \
            --with-superuser-path=/usr/bin \
            --with-pid-dir=/run

make
make DESTDIR="$1" install

cp -f contrib/ssh-copy-id   "$1/usr/bin"
cp -f contrib/ssh-copy-id.1 "$1/usr/share/man/man1"
chmod +x "$1/usr/bin/ssh-copy-id"

mkdir -pv $1/usr/lib/systemd/system/

install -m644 ../sshd.service $1/usr/lib/systemd/system/
install -m644 ../sshdat.service $1/usr/lib/systemd/system/sshd@.service
install -m644 ../sshd.socket $1/usr/lib/systemd/system/

