#!/bin/sh -e

#gcc 15 fix
sed -e "/^extern int (\*xstat)/s/()/(const char * restrict,  struct stat * restrict)/" \
    -i src/extern.h
sed -e "/^int (\*xstat)/s/()/(const char * restrict,  struct stat * restrict)/" \
    -i src/global.c

./configure \
    --prefix=/usr \
    --with-rmt=/usr/libexec/rmt

make
make DESTDIR="$1" install

