#!/bin/sh -e

mkdir -p \
    "$1/usr/bin"

# Install kiss utilities.
cp -f kiss contrib/* "$1/usr/bin/"

# Install our custom kiss_path
install -D kiss_path.sh "$1/etc/profile.d/kiss_path.sh"
install -D flags.sh "$1/etc/profile.d/flags.sh"
