#!/bin/bash -e

sip-build \
   --confirm-license \
   --qmake-setting 'CONFIG += c++17' \
   --no-make \
   --qmake=/usr/lib/qt6/bin/qmake6 \
   --api-dir /usr/share/qt6/qsci/api/python \
   --pep484-pyi

cd build
make
make INSTALL_ROOT="$1" install

#  compile Python bytecode
python -m compileall -d / "$1"/usr/lib
python -O -m compileall -d / "$1"/usr/lib
