#!/bin/bash -e

# The cross glib ships no introspection, and the docs need the host's gi-docgen
# against it, so both have to be off for the target.
cross_opts=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    cross_opts+=(-D introspection=disabled -D docs=false)
fi

hokuto-meson build \
  -D default_bus=dbus-broker "${cross_opts[@]}"
meson compile -C build
meson install -C build --destdir=$1

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
rm -rf build
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
hokuto-meson-32 build        \
  -D default_bus=dbus-broker \
  -D docs=false              \
  -D introspection=disabled

meson compile -C build
meson install -C build --destdir "$pkgdir"
rm -r "${pkgdir}"/{etc,usr/{include,lib,share}}
fi
