#!/bin/sh -e

grep -rl '^#!.*python$' | xargs sed -i '1s/python/&3/'

mkdir build
cd build

CXXFLAGS+="-O2 -fPIC"            \
meson setup                      \
      --prefix=/usr              \
      --buildtype=release        \
      -Dlibaudit=no              \
      -Dnmtui=false              \
      -Dppp=false                \
      -Dselinux=false            \
      -Dqt=false                 \
      -Dsession_tracking=systemd \
      -Dmodem_manager=false      \
      ..

ninja
DESTDIR=$1 ninja install


cd ..

install  -Dm 644 NetworkManager.conf "$1/etc/NetworkManager/NetworkManager.conf"
install -Dm 644 no-dns-update.conf  "$1/etc/NetworkManager/conf.d/no-dns-update.conf"
install -Dm 644 polkit.conf "$1/etc/NetworkManager/conf.d/polkit.conf"
install -Dm 644 org.freedesktop.NetworkManager.rules "$1/usr/share/polkit-1/rules.d/org.freedesktop.NetworkManager.rules"
