#!/bin/bash -e

hokuto-meson build                \
      -D iwd=true                 \
      -D b_lto=true               \
      -D suspend_resume=systemd   \
      -D config_dns_rc_manager_default=symlink \
      -D libaudit=no              \
      -D ppp=false                \
      -D nmtui=true               \
      -D selinux=false            \
      -D qt=false                 \
      -D session_tracking=systemd \
      -D modem_manager=true

meson compile -C build
DESTDIR=$1 meson install -C build

install -Dm 644 NetworkManager.conf "$1/etc/NetworkManager/NetworkManager.conf"
install -Dm 644 polkit.conf "$1/etc/NetworkManager/conf.d/polkit.conf"
install -Dm 644 org.freedesktop.NetworkManager.rules "$1/usr/share/polkit-1/rules.d/org.freedesktop.NetworkManager.rules"
install -d "$1/etc/NetworkManager/dnsmasq.d/"
install -Dm 644 no-cache.conf "$1/etc/NetworkManager/dnsmasq.d/no-cache.conf"

# libnm
 _pick "$1" libnm usr/include/libnm
 _pick "$1" libnm usr/lib/girepository-1.0/NM-*
 _pick "$1" libnm usr/lib/libnm.*
 _pick "$1" libnm usr/lib/nm-libnm-helper
 _pick "$1" libnm usr/lib/pkgconfig/libnm.pc
 _pick "$1" libnm usr/share/gir-1.0/NM-*
 _pick "$1" libnm usr/share/vala/vapi/libnm.*

# nm-cloud-setup
 _pick "$1" nm-cloud-setup usr/lib/**/*nm-cloud-setup*
 _pick "$1" nm-cloudsetup usr/share/man/*/nm-cloud-setup*

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
meson_options=(
  -D b_lto=true
  -D libaudit=no
  -D session_tracking_consolekit=false
  -D suspend_resume=systemd
  -D polkit_noauth_group=wheel
  -D selinux=false
  -D concheck=false
  -D iwd=false
  -D modem_manager=false
  -D nm_cloud_setup=false
  -D nmcli=false
  -D nmtui=false
  -D ovs=false
  -D ppp=false
  -D teamdctl=false
  -D nbft=false
  -D config_plugins_default=keyfile
  -D ifupdown=false
  -D netconfig=no
  -D config_dns_rc_manager_default=symlink
  -D vapi=false
  -D docs=false
  -D man=false
  -D introspection=false
  -D tests=no
  -D more_asserts=no
  -D more_logging=false
  -D qt=false
)

dest_dir=$HOKUTO_SPLIT_DIR/lib32-libnm
hokuto-meson-32 build "${meson_options[@]}"
meson compile -C build
meson install -C build --destdir $dest_dir
rm -rf $dest_dir/{etc,usr/{bin,include,lib,lib32/NetworkManager,share},var}
fi
