#!/bin/bash -e

cross_opts=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # gobject-introspection scans the just-built libnm, which cannot run on
    # the build host; the release tarball's prebuilt man pages are kept.
    cross_opts+=(-D introspection=false -D vapi=false -D tests=no)
    # meson looks these up on the build host, where the cross session has
    # none of them installed, and the provider database through the
    # sysroot. Spell out the target's paths.
    cross_opts+=(
        -D dnsmasq=/usr/bin/dnsmasq
        -D nft=/usr/bin/nft
        -D iptables=/usr/bin/iptables
        -D ip6tables=/usr/bin/ip6tables
        -D modprobe=/usr/bin/modprobe
        -D resolvconf=/usr/bin/resolvconf
        -D mobile_broadband_provider_info_database=/usr/share/mobile-broadband-provider-info/serviceproviders.xml
    )
fi

hokuto-meson build                \
      -D iwd=true                 \
      -D b_lto=true               \
      -D suspend_resume=systemd   \
      -D config_dns_rc_manager_default=symlink \
      -D libaudit=no              \
      -D ppp=false                \
      -D nmtui=true               \
      -D selinux=false            \
      -D qt=false                 \
      -D session_tracking=systemd \
      -D clat=false               \
      -D modem_manager=true       \
      "${cross_opts[@]}"

meson compile -C build
DESTDIR=$1 meson install -C build

# A cross-system build keeps everything under its prefix, /etc included.
PREFIX="${CROSS_PREFIX:-/usr}"
SYSCONFDIR=/etc
[ "$PREFIX" != /usr ] && SYSCONFDIR="$PREFIX/etc"
install -Dm 644 NetworkManager.conf "$1$SYSCONFDIR/NetworkManager/NetworkManager.conf"
install -Dm 644 polkit.conf "$1$SYSCONFDIR/NetworkManager/conf.d/polkit.conf"
install -Dm 644 org.freedesktop.NetworkManager.rules "$1$PREFIX/share/polkit-1/rules.d/org.freedesktop.NetworkManager.rules"
install -d "$1$SYSCONFDIR/NetworkManager/dnsmasq.d/"
install -Dm 644 no-cache.conf "$1$SYSCONFDIR/NetworkManager/dnsmasq.d/no-cache.conf"

# The _pick paths are spelled usr/..., which holds for a native build;
# a cross-system build keeps everything in its sysroot package.
if [ "$PREFIX" = "/usr" ]; then
# libnm
 _pick "$1" libnm usr/include/libnm
 _pick "$1" libnm usr/lib/girepository-1.0/NM-*
 _pick "$1" libnm usr/lib/libnm.*
 _pick "$1" libnm usr/lib/nm-libnm-helper
 _pick "$1" libnm usr/lib/pkgconfig/libnm.pc
 _pick "$1" libnm usr/share/gir-1.0/NM-*
 _pick "$1" libnm usr/share/vala/vapi/libnm.*

# nm-cloud-setup
_pick "$1" nm-cloud-setup usr/lib/NetworkManager/dispatcher.d/90-nm-cloud-setup.sh
_pick "$1" nm-cloud-setup usr/lib/NetworkManager/dispatcher.d/no-wait.d/
_pick "$1" nm-cloud-setup usr/lib/NetworkManager/dispatcher.d/no-wait.d/90-nm-cloud-setup.sh
_pick "$1" nm-cloud-setup usr/lib/NetworkManager/dispatcher.d/pre-up.d/
_pick "$1" nm-cloud-setup usr/lib/NetworkManager/dispatcher.d/pre-up.d/90-nm-cloud-setup.sh
_pick "$1" nm-cloud-setup usr/lib/nm-cloud-setup
_pick "$1" nm-cloud-setup usr/lib/systemd/system/nm-cloud-setup.service
_pick "$1" nm-cloud-setup usr/lib/systemd/system/nm-cloud-setup.timer
_pick "$1" nm-cloud-setup usr/share/man/man8/nm-cloud-setup.8.gz
fi

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
meson_options=(
  -D b_lto=true
  -D libaudit=no
  -D session_tracking_consolekit=false
  -D suspend_resume=systemd
  -D polkit_noauth_group=wheel
  -D selinux=false
  -D concheck=false
  -D iwd=false
  -D modem_manager=false
  -D nm_cloud_setup=false
  -D nmcli=false
  -D nmtui=false
  -D ovs=false
  -D ppp=false
  -D teamdctl=false
  -D nbft=false
  -D config_plugins_default=keyfile
  -D ifupdown=false
  -D netconfig=no
  -D config_dns_rc_manager_default=symlink
  -D vapi=false
  -D docs=false
  -D man=false
  -D introspection=false
  -D tests=no
  -D more_asserts=no
  -D more_logging=false
  -D qt=false
)

dest_dir=$HOKUTO_SPLIT_DIR/lib32-libnm
hokuto-meson-32 build "${meson_options[@]}"
meson compile -C build
meson install -C build --destdir $dest_dir
rm -rf $dest_dir/{etc,usr/{bin,include,lib,lib32/NetworkManager,share},var}
fi
