#!/bin/sh -e

echo "adding netdev group"

sudo groupadd -fg 86 netdev

echo "*****************************"
echo "*****************************"
echo "                             "
echo "add your user to netdev group"
echo "                             "
echo "*****************************"
echo "*****************************"
