#!/bin/sh -e

patch -Np1 -i 256.patch
patch -Np1 -i 251.patch
patch -Np1 -i 242.patch

cmake_options=(
  -B build
  -D CMAKE_BUILD_TYPE=None
  -D CMAKE_INSTALL_PREFIX=/usr
  -W no-dev
)

export CFLAGS+=" -ffat-lto-objects"
cmake "${cmake_options[@]}"
cmake --build build
DESTDIR="$1" cmake --install build
