#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
    # The 2011 config.sub does not know aarch64.
    automake_dir=$(ls -d /usr/share/automake-* | sort -V | tail -n1)
    cp -f "$automake_dir"/config.{sub,guess} .
fi

./configure --prefix="$PREFIX" \
  --disable-static \
  "${CROSS_OPTS[@]}"

make
make DESTDIR=$1 install
