#!/bin/bash -e

meson setup build \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=release

meson compile -C build
meson install -C build --destdir="$1"

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
CC="gcc -m32" CXX="g++ -m32" PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
meson setup build \
    --prefix=/usr \
    --cross-file lib32 \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=release \
    --libdir=lib32

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
