#!/bin/sh -e

CFLAGS+=" -ffat-lto-objects"
cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_BUILD_TYPE=None

cmake --build build
DESTDIR=$1 cmake --install build
install -d $1/usr/lib/pkgconfig/
ln -s sdl2-compat.pc $1/usr/lib/pkgconfig/sdl2.pc

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
export CC='gcc -m32'
export CXX='g++ -m32'
export PKG_CONFIG_PATH='/usr/lib32/pkgconfig'

cmake -B build -G Ninja \
      -D CMAKE_INSTALL_PREFIX=/usr \
      -D CMAKE_INSTALL_LIBDIR=lib32 \
      -D CMAKE_BUILD_TYPE=None

cmake --build build
DESTDIR=tmp32dir cmake --install build
rm -rf tmp32dir/usr/{bin,include,share}
rsync -a tmp32dir/* $1/
fi
