#!/bin/sh -e

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install
rm -v $1/usr/lib/libSDL2*.a

#32bit

make distclean
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu

make
make DESTDIR=$PWD/DESTDIR install
rm -v DESTDIR/usr/lib32/libSDL2*.a
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32

