#!/bin/sh -e

MAKE_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    TARGET_ARCH="$HOKUTO_ARCH"
    # Normalize arm64 to aarch64 if needed, though usually handled by build.go
    if [ "$TARGET_ARCH" = "arm64" ]; then TARGET_ARCH="aarch64"; fi
    CC="${TARGET_ARCH}-linux-gnu-gcc"
    AR="${TARGET_ARCH}-linux-gnu-ar"
    MAKE_OPTS="CC=$CC AR=$AR"
fi

PREFIX="${CROSS_PREFIX:-/usr}"


make $MAKE_OPTS
make $MAKE_OPTS DESTDIR=$1 \
    SBINDIR="$PREFIX/bin" \
    BINDIR="$PREFIX/bin" \
    LIBDIR="$PREFIX/lib" \
    USRLIBDIR="$PREFIX/lib" \
    INCLUDEDIR="$PREFIX/include" \
    ETCDIR="$PREFIX/etc" \
    MANDIR="$PREFIX/share/man" \
    SHAREDIR="$PREFIX/share/keyutils" \
    install
