#!/bin/sh -e

sed 's/apiversion/soup_version/' -i docs/reference/meson.build

mkdir build
cd    build

meson --prefix=/usr          \
      --buildtype=release    \
      -Dvapi=enabled         \
      -Dgssapi=disabled      \
      -Dsysprof=disabled     \
      --wrap-mode=nofallback \
      ..

ninja
ninja install
