#!/bin/sh -e

patch -Np1 -i 0003-Adjust-includes-for-build-with-gstreamer-1.28.patch

autoreconf -fvi
BUILDCC=gcc ./configure --prefix=/usr
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make DESTDIR=$1 install
