#!/bin/bash -e

PREFIX=${CROSS_PREFIX:-/usr}

patch -Np1 -i sauzeros-logo.patch

CMAKE_FLAGS=()


cmake -B build -D CMAKE_INSTALL_PREFIX="$PREFIX" "${CMAKE_FLAGS[@]}"
cmake --build build --target fastfetch --target flashfetch
DESTDIR=$1 cmake --install build

install -Dm644 hokuto.png $1/usr/share/pixmaps/hokuto.png
install -Dm644 config.jsonc $1/etc/fastfetch/config.jsonc
