#!/bin/bash -e

patch -Np1 -i libmodplug-0.8.9.0-no-fast-math.patch
autoreconf -fvi

./configure --prefix=/usr
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make DESTDIR="${1}" install
