#!/bin/sh -e

PREFIX="${CROSS_PREFIX:-/usr}"
SYSCONF_DIR="${PREFIX}/etc"
[ "$PREFIX" = "/usr" ] && SYSCONF_DIR="/etc"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure \
    --prefix="$PREFIX" \
    --sysconfdir="$SYSCONF_DIR" \
    --disable-manpages \
    --with-xz \
    --with-zlib \
    $CROSS_OPTS

make
make DESTDIR="$1" install


if [ "$MULTILIB" = "1" ]; then
#32bit
mkdir build
cd build
PKG_CONFIG_PATH="/usr/lib32/pkgconfig" \
CC="gcc -m32 -march=i686"              \
CXX="g++ -m32 -march=i686"             \
meson setup --prefix=/usr ..    \
            --buildtype=release \
            --libdir=/usr/lib32 \
            -D manpages=false

ninja
DESTDIR=$PWD/DESTDIR ninja install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
fi
