#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
SYSCONF_DIR="${PREFIX}/etc"
[ "$PREFIX" = "/usr" ] && SYSCONF_DIR="/etc"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure                     \
    --prefix="$PREFIX"          \
    --sysconfdir="$SYSCONF_DIR" \
    --disable-manpages          \
    --with-xz                   \
    --with-zlib                 \
    --with-zstd                 \
    --with-systemdsystemunitdir="${PREFIX}/lib/systemd/system" \
    --with-bashcompletiondir="${PREFIX}/share/bash-completion/completions" \
    --with-fishcompletiondir="${PREFIX}/share/fish/vendor_completions.d" \
    $CROSS_OPTS

make
make DESTDIR="$1" install

if [ "$MULTILIB" = "1" ]; then
#32bit split package
PKG_CONFIG_PATH="/usr/lib32/pkgconfig" \
CC="gcc -m32 -march=i686"              \
CXX="g++ -m32 -march=i686"             \
meson setup build         \
      --prefix=/usr       \
      --buildtype=release \
      --libdir=/usr/lib32 \
      -D manpages=false

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
