#!/bin/sh -e

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=/usr     \
      -DCMAKE_BUILD_TYPE=Release      \
      -DALLOW_EXTERNAL_SPIRV_TOOLS=ON \
      -DBUILD_SHARED_LIBS=ON          \
      -DGLSLANG_TESTS=OFF             \
      -G Ninja ..
ninja

DESTDIR=$1 ninja install
