#!/bin/sh -e

autoreconf -fvi

./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var \
            --libexecdir=/usr/lib --disable-static --with-gtk4

make
make DESTDIR="$1" install dbusservicedir=/usr/share/dbus-1/system.d

echo 'u nm-openconnect - "NetworkManager OpenConnect"' |
install -Dm644 /dev/stdin "$1/usr/lib/sysusers.d/networkmanager-openconnect.conf"
