#!/bin/sh -e

#create required user
sudo groupadd -r nm-openconnect
sudo useradd -r -g nm-openconnect -d / -s /sbin/nologin -c "Default user for running openconnect spawned by NetworkManager" nm-openconnect

