#!/bin/bash -e

cmake -B build                 \
  -D CMAKE_BUILD_TYPE=None     \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -W no-dev                    \
  -D FASTFLOAT_TEST=OFF        \
  -D SYSTEM_DOCTEST=OFF

cmake --build build
DESTDIR="${1}" cmake --install build
