#!/bin/bash -e

autoreconf -vfi
./configure --prefix=/usr \
  --sysconfdir=/etc
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool

make
make DESTDIR=$1 install
touch "$1"/etc/{odbc,odbcinst}.ini
