#!/bin/sh -e

7z e CleanDoom_v1.1.0_Linux.7z
install -Dm755 CleanDoom.x86_64 $1/usr/bin/cleandoom
install -Dm644 cleandoom.png $1/usr/share/pixmaps/cleandoom.png
install -Dm644 cleandoom.desktop $1/usr/share/applications/cleandoom.desktop
