#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # gobject-introspection scans the just-built library, and the sysroot's
    # GLib has no .gir: no introspection in a cross build.
    CROSS_OPTS+=(--disable-introspection)
fi

./autogen.sh
./configure             \
  --prefix="$PREFIX"    \
  --sysconfdir=/etc     \
  --localstatedir=/var  \
  --disable-nls         \
  --disable-gtk-doc     \
  --libexecdir="$PREFIX/lib" \
  "${CROSS_OPTS[@]}"

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make DESTDIR="${1}" install
