#!/bin/bash -e

./autogen.sh
./configure             \
  --prefix=/usr         \
  --sysconfdir=/etc     \
  --localstatedir=/var  \
  --disable-nls         \
  --disable-gtk-doc     \
  --libexecdir=/usr/lib

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make DESTDIR="${1}" install
