#!/bin/sh -e

patch -Np1 -i sgml-common-0.6.3-manpage-1.patch

autoreconf -fvi
./configure \
    --prefix=/usr \
    --sysconfdir=/etc

make
make DESTDIR="$1" docdir=/usr/share/doc install

# Remove docs.
rm -rf "$1/usr/share/doc"
