#!/bin/bash -e

meson setup build     \
  --prefix=/usr       \
  --buildtype=release \
  -D gles1=false      \
  -D hgl=false

meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf build
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
meson setup build                    \
  --prefix=/usr                      \
  --libdir=/usr/lib32                \
  --buildtype=release                \
  -D gles1=false                     \
  -D hgl=false

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
