#!/bin/bash -e

sed -i '/^udev/,$ s/^/#/' util/meson.build

hokuto-meson build
meson compile -C build
meson install -C build --destdir=$1

rm -rf $1/dev
rm -rf $1/etc/init.d

if [ "$CROSS_PREFIX" = "/usr" ]; then
#fusermount needs +s to work
chmod +s $1/usr/bin/fusermount3

#symlink
ln -s fusermount3 $1/usr/bin/fusermount

#default config
mkdir -p "$1/etc"
echo "user_allow_other" > "$1/etc/fuse.conf"
fi
