#!/bin/bash -e

configure_options=(
    --prefix=/usr
    --sysconfdir=/etc
    --enable-maemo-plugin
    --enable-maemo-resource-manager
)

./configure "${configure_options[@]}"
# prevent excessive overlinking due to libtool
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool

make
make DESTDIR=$1 install

mv \
  "$1/etc/alsa/conf.d/99-pulseaudio-default.conf.example" \
  "$1/usr/share/alsa/alsa.conf.d/99-pulseaudio-default.conf"

# pulseaudio-alsa split package
pkgdir=$HOKUTO_SPLIT_DIR/pulseaudio-alsa
install -vdm 755 "$pkgdir/etc/alsa/conf.d"
ln -st "$pkgdir/etc/alsa/conf.d" /usr/share/alsa/alsa.conf.d/99-pulseaudio-default.conf

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make distclean
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
configure_options=(
    --prefix=/usr
    --libdir=/usr/lib32
    --sysconfdir=/etc
    --enable-maemo-plugin
)
export CC='gcc -m32'
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
 ./configure "${configure_options[@]}"
make
make DESTDIR="$pkgdir" install
rm -rv "$pkgdir"/{etc,usr/share}
fi

