#!/bin/sh -e

#fix ncurses detection script
sed '50s/main() {}/int main() {}/' -i scripts/kconfig/lxdialog/check-lxdialog.sh

if [ "$HOKUTO_CARCH" = "arm64" ]; then
# use custom config
mv config-arm64 .config
ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make
else
# use custom config
mv config .config
make
fi
install -Dm0755 busybox "$1"/usr/bin/busybox
