#!/bin/sh -e

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    case "$HOKUTO_ARCH" in
        aarch64) GOARCH=arm64 ;;
        x86_64)  GOARCH=amd64 ;;
        *)       GOARCH=$HOKUTO_ARCH ;;
    esac
    export GOARCH
    export CGO_ENABLED=0
fi

# welcome page
cp caddy-dist/welcome/index.html .
sed 's|/var/www/html|/srv/http|g' -i index.html
# do not write in /etc
patch -Np1 < use-data-dir-for-autosave.patch
# fix version identifier if not built from a module
patch -Np1 < override-main-module-version.patch
sed 's|"unknown"|"v'"${pkgver}"'"|g' -i caddy.go

# Add Cloudflare DNS plugin
sed -i '/modules\/standard"/a \	_ "github.com/caddy-dns/cloudflare"' cmd/caddy/main.go
export GOFLAGS="-trimpath -mod=mod -modcacherw"
go get github.com/caddy-dns/cloudflare

cd cmd/caddy
export CGO_LDFLAGS="${LDFLAGS}"
export CGO_CPPFLAGS="${CPPFLAGS}"
export CGO_CFLAGS="${CFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # Pure Go build for cross-compilation
    export GOFLAGS="-trimpath -mod=mod -modcacherw"
else
    # Native build
    export GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=mod -modcacherw"
fi

go build .

#if [ "${HOKUTO_CROSS:-0}" != "1" ]; then
    for i in zsh bash fish; do
        ./caddy completion $i >caddy.$i
    done
#fi

cd ../..

install -Dm 755 cmd/caddy/caddy -t "$1/usr/bin"

install -Dm 644 "caddy.service" "caddy-api.service" -t "$1/usr/lib/systemd/system"
install -Dm 644 "caddy.tmpfiles" "$1/usr/lib/tmpfiles.d/caddy.conf"
install -Dm 644 "caddy.sysusers" "$1/usr/lib/sysusers.d/caddy.conf"

install -Dm 644 "Caddyfile" -t "$1/etc/caddy"
install -d "$1/etc/caddy/conf.d"

install -Dm 644 index.html "$1/usr/share/caddy/index.html"

#if [ "${HOKUTO_CROSS:-0}" != "1" ]; then
    install -Dm 644 "cmd/caddy/caddy.zsh" "$1/usr/share/zsh/site-functions/_caddy"
    install -Dm 644 "cmd/caddy/caddy.bash" "$1/usr/share/bash-completion/completions/caddy"
    install -Dm 644 "cmd/caddy/caddy.fish" -t "$1/usr/share/fish/vendor_completions.d"
#fi
