#!/bin/sh -e

# welcome page
cp caddy-dist/welcome/index.html .
sed 's|/var/www/html|/srv/http|g' -i index.html
# do not write in /etc
patch -Np1 < use-data-dir-for-autosave.patch
# fix version identifier if not built from a module
patch -Np1 < override-main-module-version.patch
sed 's|"unknown"|"v'"${pkgver}"'"|g' -i caddy.go

cd cmd/caddy
export CGO_LDFLAGS="${LDFLAGS}"
export CGO_CPPFLAGS="${CPPFLAGS}"
export CGO_CFLAGS="${CFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"
export GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=readonly -modcacherw"
go build .

for i in zsh bash fish; do
./caddy completion $i >caddy.$i
done

cd ../..

install -Dm 755 cmd/caddy/caddy -t "$1/usr/bin"

install -Dm 644 "caddy.service" "caddy-api.service" -t "$1/usr/lib/systemd/system"
install -Dm 644 "caddy.tmpfiles" "$1/usr/lib/tmpfiles.d/caddy.conf"
install -Dm 644 "caddy.sysusers" "$1/usr/lib/sysusers.d/caddy.conf"

install -Dm 644 "Caddyfile" -t "$1/etc/caddy"
install -d "$1/etc/caddy/conf.d"

install -Dm 644 index.html "$1/usr/share/caddy/index.html"

install -Dm 644 "cmd/caddy/caddy.zsh" "$1/usr/share/zsh/site-functions/_caddy"
install -Dm 644 "cmd/caddy/caddy.bash" "$1/usr/share/bash-completion/completions/caddy"
install -Dm 644 "cmd/caddy/caddy.fish" -t "$1/usr/share/fish/vendor_completions.d"

