#!/bin/bash -e

sed -i "s/'-Werror'//" meson.build

# fix for newer libxml2
git cherry-pick -n 0adf38535637ec668e658d43f04f60f11f51574f

hokuto-meson build \
 -D enable-gtk-doc=false \
 -D with-usb-ids-path=/usr/share/hwdata/usb.ids \
 -D with-pci-ids-path=/usr/share/hwdata/pci.ids

meson compile -C build
meson install -C build --destdir=$1
