#!/bin/bash -e

#fix
sed -e '204a\    tree = ET.parse(xmlfile)'                 \
    -e 's/VkXML(ET.parse(xmlfile))/VkXML(tree.getroot())/' \
    -i src/vulkan/utils_gen.py

hokuto-meson build   \
  -D vulkan=enabled  \
  -D glslang=enabled \
  -D shaderc=enabled \
  -D lcms=enabled    \
  -D d3d11=disabled  \
  -D demos=false

meson compile -C build
meson install -C build --destdir=$1
