#!/bin/sh -e

#fix
sed -e '204a\    tree = ET.parse(xmlfile)'                 \
    -e 's/VkXML(ET.parse(xmlfile))/VkXML(tree.getroot())/' \
    -i src/vulkan/utils_gen.py

meson setup build --prefix=/usr \
        -D glslang=enabled

meson compile -C build
DESTDIR=$1 meson install -C build
