#!/bin/sh -e

PREFIX="${CROSS_PREFIX:-/usr}"

MESON_OPTS=(
    --prefix="$PREFIX"
    --buildtype=release
    -Dtests=false
)

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    MESON_OPTS+=(--cross-file "$HOKUTO_ARCH")
fi

meson setup build "${MESON_OPTS[@]}"

meson compile -C build
meson install -C build --destdir=$1