#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-documentation
make
make DESTDIR="$1" install

# show copy to ram progress
cd $1/usr/lib/dracut/modules.d/70dmsquash-live
patch -Np0 < ../../../../../../build/show-progress.patch

# Remove docs.
rm -rf "$1/usr/share/doc"
