#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure \
  --prefix=$PREFIX \
  --disable-documentation \
  $CROSS_OPTS

make
make DESTDIR="$1" install

# show copy to ram progress
cd $1/usr/lib/dracut/modules.d/70dmsquash-live
patch -Np0 < ../../../../../../build/show-progress.patch

# fake rpcbind for nfs module to install
touch $1/usr/bin/rpcbind
