#!/bin/sh -e

sed -i -r 's:"(/apps):"/org/gnome\1:' data/*.xml
sed -i "s/'2.3.0'/'2.3.0', '2.4.0'/" meson.build

mkdir build
cd build

meson --prefix=/usr -Dldap-support=false \
                    -Dpkcs11-support=false \
                    --buildtype=release ..

ninja
ninja install
