#!/bin/bash -e

hokuto-meson build    \
  -D elogind=disabled \
  -D doc=disabled     \
  -D tests=false      \
  -D dbus-tests=false \
  -D system-lua=true

meson compile -C build
meson install -C build --destdir=$1
