#!/bin/sh -e

mkdir build
cd    build

meson setup ..        \
  --prefix=/usr       \
  --buildtype=release \
  -Ddocs=disabled

ninja
DESTDIR="$1" ninja install

install -v -m755 -d "$1/etc/pam.d"

cd ..
install -v -m644 system-account "$1/etc/pam.d/system-account"
install -v -m644 system-auth "$1/etc/pam.d/system-auth"
install -v -m644 system-session "$1/etc/pam.d/system-session"
install -v -m644 system-password "$1/etc/pam.d/system-password"
install -v -m644 other "$1/etc/pam.d/other"
