#!/bin/sh -e

unset LDFLAGS

meson setup build       \
  --prefix=/usr         \
  --buildtype=release   \
  -Ddocs=disabled

meson compile -C build
meson install -C build --destdir=$1

install -v -m755 -d "$1/etc/pam.d"
install -v -m644 system-account "$1/etc/pam.d/system-account"
install -v -m644 system-auth "$1/etc/pam.d/system-auth"
install -v -m644 system-session "$1/etc/pam.d/system-session"
install -v -m644 system-password "$1/etc/pam.d/system-password"
install -v -m644 other "$1/etc/pam.d/other"

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
PKG_CONFIG_PATH="/usr/lib32/pkgconfig" \
CC="gcc -m32 -march=i686"              \
CXX="g++ -m32 -march=i686"             \
meson setup build       \
    --prefix=/usr       \
    --libdir=/usr/lib32 \
    --buildtype=release \
    -D docs=disabled

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
fi
