#!/bin/bash -e

hokuto-meson build \
  -D default_library=shared
meson compile -C build
meson install -C build --destdir=$1

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
rm -rf build
dest_dir="$HOKUTO_SPLIT_DIR/lib32-glu"
hokuto-meson-32 build     \
  -D default_library=shared
meson compile -C build
meson install -C build --destdir=$dest_dir
rm -rvf $dest_dir/usr/include
fi
