#!/bin/sh

/usr/bin/depmod
/usr/bin/ldconfig

cat <<EOF

NOTE: If 'KERNEL_UNAME' was exported, it is necessary to run
      'depmod \$KERNEL_UNAME' manually.

if using linux-rt, edit "include/linux/export.h" in kernel source tree

remove gpl from:
#define EXPORT_SYMBOL_GPL(sym)          _EXPORT_SYMBOL(sym, "")
#define EXPORT_SYMBOL_NS(sym, ns)       __EXPORT_SYMBOL(sym, "", #ns)
#define EXPORT_SYMBOL_NS_GPL(sym, ns)   __EXPORT_SYMBOL(sym, "", #ns)

EOF
