#!/bin/sh

# nvidia-modprobe needs +s
chmod 4755 /bin/nvidia-modprobe

# enable systemd services
systemctl enable nvidia-resume nvidia-hibernate nvidia-suspend nvidia-persistenced

depmod -a
ldconfig
