#!/bin/bash -e

autoreconf -fvi
./configure --prefix=/usr   \
  --disable-static          \
  --enable-security         \
  --enable-no-sock-security \
  --with-libtirpc

make
make DESTDIR=$1 install

