#!/bin/sh -e

meson setup build \
  --prefix=/usr   \
  -D xvfb=true    \
  -D xnest=true   \
  -D xephyr=true  \
  -D systemd_logind=true \
  -D drm=true \
  -D suid_wrapper=true

meson compile -C build
meson install -C build --destdir=$1
