#!/bin/bash -e

meson_options=(
    -D libsystemd=true
    -D libudev=true
    -D polkit=true
    -D serial=true
    -D systemdunit=system
)

hokuto-meson build "${meson_options[@]}"
meson compile -C build
meson install -C build --destdir "${1}"

install -D -m0644 doc/org.debian.pcsc-lite.policy -t "${1}"/usr/share/polkit-1/actions/
install -d "${1}"/usr/lib/pcsc/drivers
