#!/bin/sh -e

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dtests=false \
    -Ddocumentation=false \
    -Ddtd_validation=false \
    . build

ninja -C build
DESTDIR=$1 ninja -C build install

#32bit
rm -rf build
mkdir build
cd build
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
meson setup ..                       \
      --prefix=/usr                  \
      --libdir=/usr/lib32            \
      --buildtype=release            \
      -D documentation=false

ninja
DESTDIR=$PWD/DESTDIR ninja install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
