#!/bin/sh -e

# remove flit_core check
sed -i 's/<4//g' pyproject.toml

# Use CROSS_PREFIX if set (defaults to /usr in hokuto)
PREFIX="${CROSS_PREFIX:-/usr}"

python -m build --wheel --no-isolation
python -m installer --destdir="$1" --prefix="$PREFIX" dist/*.whl
