#!/bin/bash -e

./configure --prefix=/usr \
  --enable-cxx

make -j1
make DESTDIR="${1}" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
cd portaudio-32
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
./configure --prefix=/usr \
  --enable-cxx            \
  --libdir=/usr/lib32

make -j1
make DESTDIR="$pkgdir" install
rm -rf "$pkgdir/usr/include"
fi
