#!/bin/sh -e

meson setup output  \
    -D prefix=/usr  \
    -D gtk=disabled

meson compile -C output
meson install -C output --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit
meson setup build           \
      --cross-file=lib32    \
      --prefix=/usr         \
      --libdir=/usr/lib32   \
      --buildtype=release   \
      -D tests=disabled

ninja -C build
DESTDIR=$PWD/DESTDIR ninja -C build install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
fi
