#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi

autoreconf -fi
./bootstrap.sh
./configure --prefix="$PREFIX" \
  --localstatedir=/var    \
  --disable-lynx          \
  "${CROSS_OPTS[@]}"

make
make DESTDIR="${1}" install
