#!/bin/bash -e

hokuto-meson build          \
      --localstatedir=/var  \
      -D glamor=true        \
      -D xkb_output_dir=/var/lib/xkb

meson compile -C build
meson install -C build --destdir=$1
