#!/bin/bash -e

cross_opts=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # gobject-introspection and vala scan the just-built library, which
    # cannot run on the build host.
    cross_opts+=(-D introspection=false -D vapi=false)
    # bash-completion is arch-independent; give the cross pkg-config the
    # build machine's .pc alone, for the completions directory.
    mkdir -p "$PWD/.bash-completion-pc"
    cp /usr/share/pkgconfig/bash-completion.pc "$PWD/.bash-completion-pc/"
    export PKG_CONFIG_PATH="$PWD/.bash-completion-pc${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
    export PKG_CONFIG_BASH_COMPLETION_DATADIR="${CROSS_PREFIX:-/usr}/share"
fi

hokuto-meson build     \
      -D gtk_doc=false \
      -D manpage=false "${cross_opts[@]}"

meson compile -C build
meson install -C build --destdir=$1
