#!/bin/bash -e

sed -i 's/AV_OPT_TYPE_CHANNEL_LAYOUT/AV_OPT_TYPE_CHLAYOUT/' filters/f_lavfi.c

hokuto-meson build \
  -D x11=enabled   \
  -D drm=enabled

meson compile -C build
meson install -C build --destdir=$1
