#!/bin/sh -e

mkdir build
cd    build

meson setup --prefix=/usr            \
            --buildtype=release      \
            -D gallium-drivers=      \
            -D vulkan-drivers=       \
            -D video-codecs=         \
            -D gbm=enabled           \
            -D glx=disabled          \
            -D llvm=disabled         \
            -D valgrind=disabled     \
            -D libunwind=disabled    \
            ..

ninja
DESTDIR=$1 ninja install
mkdir -pv $1/usr/include/GL/internal
cp -v ../include/GL/internal/dri_interface.h $1/usr/include/GL/internal
mkdir -pv $1/usr/include/EGL
cp -v ../include/EGL/eglmesaext.h $1/usr/include/EGL

#32bit

rm -rf *
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
meson setup --prefix=/usr            \
            --libdir=/usr/lib32      \
            --buildtype=release      \
            -D gallium-drivers=      \
            -D vulkan-drivers=       \
            -D video-codecs=         \
            -D gbm=enabled           \
            -D glx=disabled          \
            -D llvm=disabled         \
            -D valgrind=disabled     \
            -D libunwind=disabled    \
            ..

ninja
DESTDIR=$PWD/DESTDIR ninja install
install -d $1/usr/{lib32,share}/
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
