#!/bin/sh -e

mkdir build
cd build

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

../configure --prefix="$PREFIX" \
    --disable-static            \
    --libexecdir="$PREFIX/lib"  \
    --enable-elf-shlibs         \
    --disable-libblkid          \
    --disable-libuuid           \
    --disable-uuidd             \
    --disable-fsck              \
    $CROSS_OPTS

make
make DESTDIR=$1 install

rm -fv $1/usr/lib/{libcom_err,libe2p,libext2fs,libss}.a
