#!/bin/sh -e

export RUSTUP_TOOLCHAIN=stable
export CARGO_TARGET_DIR=target
export CC=clang
cargo fetch --locked --target "$(rustc -vV | sed -n 's/host: //p')"
cargo build --frozen --release
# Binary (installed alongside plugins, symlinked from /usr/bin)
install -Dm755 target/release/fresh "$1/usr/share/fresh-editor/fresh"
install -dm755 "$1/usr/bin"
n -s "/usr/share/fresh-editor/fresh" "$1/usr/bin/fresh"

# Plugins
cp -r plugins "$1/usr/share/fresh-editor/"

# Keymaps
cp -r keymaps "$1/usr/share/fresh-editor/"
