#!/bin/sh -e

meson setup build            \
      --prefix=/usr          \
      --buildtype=release    \
      -D gpl=enabled         \
      -D gsm=disabled

meson compile -C build
DESTDIR=$1 meson install -C build

#32bit
rm -rf build
meson setup build               \
            --prefix=/usr       \
            --libdir=/usr/lib32 \
            --cross-file=lib32  \
            --buildtype=release \
            -D gpl=enabled      \
            -D gsm=disabled

meson compile -C build
DESTDIR=$PWD/DESTDIR meson install -C build
install -d $1/usr/lib32
cp -vR DESTDIR/usr/lib32/* $1/usr/lib32
