#!/bin/bash -e

./configure \
    --prefix=/usr \
    --disable-static

make
make DESTDIR="$1" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
export CC='gcc -m32'
export CXX='g++ -m32'
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig
make distclean
./configure --prefix=/usr \
  --libdir=/usr/lib32     \
  --disable-static

make
make DESTDIR=$PWD/DESTDIR install
_pick "$PWD/DESTDIR" lib32-$3 usr/lib32/libxcb-keysyms.so*
_pick "$PWD/DESTDIR" lib32-$3 usr/lib32/pkgconfig/xcb-keysyms.pc
fi
