#!/bin/sh -e

#gcc 15 fix
sed -i 's/do_version ()/do_version (PedDevice** dev, PedDisk** diskp)/' parted/parted.c

./configure \
	--prefix=/usr \
	--sbindir=/usr/bin \
	--disable-nls \
	--disable-rpath \
	--disable-device-mapper \
	--without-readline

make
make DESTDIR="$1" install

rm -rf $1/usr/share/info
