#!/bin/bash -e

hokuto-meson build \
  -D installed-tests=false \
  -D documentation=disabled \
  -D sandboxed-sound-validation=disabled \
  -D tests=disabled

meson compile -C build
meson install -C build --destdir=$1
