#!/bin/sh -e

meson setup build \
  --prefix=/usr \
  -D installed-tests=false \
  -D documentation=disabled \
  -D sandboxed-sound-validation=disabled \
  -D tests=disabled

meson compile -C build
meson install -C build --destdir=$1
