#!/bin/sh -e

patch -Np1 -i nss-standalone-1.patch

cd nss

NSS_EXTRA=""
if echo "$CPUFLAGS" | grep -q "avx2"; then
  NSS_EXTRA="NSS_ENABLE_AVX2=1"
fi

make BUILD_OPT=1                     \
  NSPR_INCLUDE_DIR=/usr/include/nspr \
  USE_SYSTEM_ZLIB=1                  \
  ZLIB_LIBS=-lz                      \
  NSS_ENABLE_WERROR=0                \
  USE_64=1                           \
  NSS_USE_SYSTEM_SQLITE=1            \
  $NSS_EXTRA

cd ../dist

install -d $1/usr/lib/pkgconfig
install -d $1/usr/bin

install -v -m755 Linux*/lib/*.so              $1/usr/lib
install -v -m644 Linux*/lib/{*.chk,libcrmf.a} $1/usr/lib

install -v -m755 -d                           $1/usr/include/nss
cp -v -RL {public,private}/nss/*              $1/usr/include/nss

install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} $1/usr/bin

install -v -m644 Linux*/lib/pkgconfig/nss.pc  $1/usr/lib/pkgconfig

if [ "$MULTILIB" = "1" ]; then
#32bit
cd ../nss
find -name "Linux*.OBJ" -type d -exec rm -rf {} +
rm -rf ../dist

CC="gcc -m32" CXX="g++ -m32"          \
make BUILD_OPT=1                      \
NSPR_INCLUDE_DIR=/usr/include/nspr    \
  USE_SYSTEM_ZLIB=1                   \
  ZLIB_LIBS=-lz                       \
  NSS_ENABLE_WERROR=0                 \
  NSS_USE_SYSTEM_SQLITE=1             \

cd ../dist

install -d $1/usr/lib32/pkgconfig
install -v -m755 Linux*/lib/*.so              $1/usr/lib32
install -v -m644 Linux*/lib/{*.chk,libcrmf.a} $1/usr/lib32
sed -i 's/lib/lib32/g' Linux*/lib/pkgconfig/nss.pc
install -v -m644 Linux*/lib/pkgconfig/nss.pc  $1/usr/lib32/pkgconfig
fi
