#!/bin/bash -e

# remove git requirement
sed -i "/'git'/,+3d" meson.build

PREFIX="${CROSS_PREFIX:-/usr}"

MESON_OPTS=(
    --prefix="$PREFIX"
    -D icu=enabled
    -D legacy=enabled
    -D history=enabled
    -D docs=disabled
)

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    MESON_OPTS+=(--cross-file "$HOKUTO_ARCH")
fi

meson setup build "${MESON_OPTS[@]}"
meson compile -C build
meson install -C build --destdir=$1

# prevent some packages from unnecessarily linking to ICU
rm -vf "$1$PREFIX/lib/"libxml2.la 2>/dev/null || :
sed '/libs=/s/xml2.*/xml2"/' -i "$1$PREFIX/bin/xml2-config"

if [ "$MULTILIB" = "1" ]; then
#32bit split package
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --sysconfdir=/etc        \
            --disable-static         \
            --with-history           \
            --with-icu               \
            --without-python

make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
rm -vf DESTDIR/usr/lib32/libxml2.la
cp -Rv DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
