#!/bin/sh -e

meson setup build --prefix=/usr \
    -D icu=enabled \
    -D legacy=enabled \
    -D docs=disabled
meson compile -C build
meson install -C build --destdir=$1

#prevent some packages from unnecessarily linking to ICU
rm -vf $1/usr/lib/libxml2.la
sed '/libs=/s/xml2.*/xml2"/' -i $1/usr/bin/xml2-config

if [ "$MULTILIB" = "1" ]; then
#32bit
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --sysconfdir=/etc        \
            --disable-static         \
            --with-history           \
            --with-icu               \
            --without-python

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
rm -vf DESTDIR/usr/lib32/libxml2.la
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
fi
