#!/bin/bash -e

make DESTDIR=$1 PREFIX=/usr install

if [ "$MULTILIB" = "1" ]; then
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32/pkgconfig
ln -sfv /usr/lib/pkgconfig/ffnvcodec.pc $dest_dir/usr/lib32/pkgconfig/ffnvcodec.pc
fi
