#!/bin/bash -e

cmake -B build                 \
  -D CMAKE_BUILD_TYPE=None     \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -W no-dev                    \
  -D BUILD_SHARED_LIBS=ON

cmake --build build
DESTDIR=$1 cmake --install build
