#!/bin/sh -e

cmake -S . -B build \
    -D CMAKE_BUILD_TYPE=None \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_C_FLAGS="$CFLAGS -ffat-lto-objects" \
    -D CMAKE_CXX_FLAGS="$CXXFLAGS -ffat-lto-objects" \
    -D protobuf_BUILD_SHARED_LIBS=ON \
    -D protobuf_ABSL_PROVIDER=package \
    -W no-dev

cmake --build build
DESTDIR=$1 cmake --install build
