#!/bin/sh -e

meson setup build --prefix=/usr
meson compile -C build
DESTDIR=$1 meson install -C build

install -Dm644 49-allow-passwordless-printer-admin.rules $1/etc/polkit-1/rules.d/49-allow-passwordless-printer-admin.rules
