#!/bin/bash -e

hokuto-meson build
meson compile -C build
meson install -C build --destdir=$1

install -Dm644 49-allow-passwordless-printer-admin.rules $1/etc/polkit-1/rules.d/49-allow-passwordless-printer-admin.rules
