#!/bin/sh -e

git cherry-pick -n 1e0515b2 # Fix build with GCC 13
patch -p1 -i cmake-4.patch # Fix build with cmake 4

cmake -B build \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D CMAKE_C_FLAGS="$CFLAGS -ffat-lto-objects" \
  -D USE_SYSTEM_XZ=ON \
  -D USE_SYSTEM_SQUASHFUSE=ON \
  -D USE_SYSTEM_LIBARCHIVE=ON \
  -D USE_SYSTEM_BOOST=ON \
  -D USE_SYSTEM_XDGUTILS=ON \
  -D BUILD_TESTING=OFF

cmake --build build
DESTDIR="${1}" cmake --install build
