#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
SYSCONF_DIR="${PREFIX}/etc"
[ "$PREFIX" = "/usr" ] && SYSCONF_DIR="/etc"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"

    # Autoconf cannot run tests when cross-compiling
    export ac_cv_func_malloc_0_nonnull=yes
    export ac_cv_func_realloc_0_nonnull=yes
fi

./configure --prefix="$PREFIX"       \
            --sysconfdir="$SYSCONF_DIR" \
            --sbindir="$PREFIX/bin" \
            --enable-cmdlib     \
            --enable-pkgconfig  \
            --enable-udev_sync  \
            --with-systemdsystemunitdir="${PREFIX}/lib/systemd/system" \
            --with-tmpfilesdir="${PREFIX}/lib/tmpfiles.d" \
            $CROSS_OPTS

make
make DESTDIR="$1" install
make DESTDIR="$1" install_systemd_units

if [ "$PREFIX" != "/usr" ]; then
rm -rf $1/etc
fi

# device-mapper split package
_pick "$1" device-mapper usr/bin/blkdeactivate
_pick "$1" device-mapper usr/bin/dmeventd
_pick "$1" device-mapper usr/bin/dmsetup
_pick "$1" device-mapper usr/bin/dmstats
_pick "$1" device-mapper usr/bin/dmvdostats
_pick "$1" device-mapper usr/include/libdevmapper-event.h
_pick "$1" device-mapper usr/include/libdevmapper.h
_pick "$1" device-mapper usr/lib/libdevmapper-event.so
_pick "$1" device-mapper usr/lib/libdevmapper-event.so*
_pick "$1" device-mapper usr/lib/libdevmapper.so*
_pick "$1" device-mapper usr/lib/pkgconfig/devmapper-event.pc
_pick "$1" device-mapper usr/lib/pkgconfig/devmapper.pc
_pick "$1" device-mapper usr/lib/systemd/system/dm-event.service
_pick "$1" device-mapper usr/lib/systemd/system/dm-event.socket
_pick "$1" device-mapper usr/lib/systemd/system/sockets.target.wants/dm-event.socket
_pick "$1" device-mapper usr/lib/udev/rules.d/10-dm.rules
_pick "$1" device-mapper usr/lib/udev/rules.d/13-dm-disk.rules
_pick "$1" device-mapper usr/lib/udev/rules.d/95-dm-notify.rules
_pick "$1" device-mapper usr/share/man/man8/blkdeactivate.8.gz
_pick "$1" device-mapper usr/share/man/man8/dmeventd.8.gz
_pick "$1" device-mapper usr/share/man/man8/dmsetup.8.gz
_pick "$1" device-mapper usr/share/man/man8/dmstats.8.gz
_pick "$1" device-mapper usr/share/man/man8/dmvdostats.8.gz
