#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi

NOCONFIGURE=1 ./autogen.sh
./configure --prefix="$PREFIX" \
  --disable-static \
  --disable-db \
  --with-openssl=no \
  --with-gnutls=yes \
  --with-poll "${CROSS_OPTS[@]}"

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make DESTDIR="${1}" install
