#!/bin/sh -e

# Common files
ar -x packages/cnijfilter-common_4.10-1_amd64.deb data.tar.gz
tar -xf data.tar.gz -C $1/

# Model specific files
ar -x packages/cnijfilter-e400series_4.10-1_amd64.deb data.tar.gz
tar -xf data.tar.gz -C $1/

# Move the udev rule to its proper location
mv $1/etc/udev $1/usr/lib/
