#!/bin/bash -e

hokuto-meson build           \
  -D tests=false             \
  -D selinux_module=disabled \
  -D system_bubblewrap=bwrap \
  -D seccomp=disabled        \
  -D system_dbus_proxy=xdg-dbus-proxy

meson compile -C build
meson install -C build --destdir=$1
