#!/bin/sh -e

PYTHONPATH=$PWD/pyparsing:$(python -c "import sys; print(':'.join(sys.path))")
export PYTHONPATH

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib \
    --disable-static \
    --disable-gtk-doc \
    --disable-documentation \
    --disable-nls \
    --disable-system-helper

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool

make
make DESTDIR="$1" install

install -Dm644 flatpak-bindir.sh "$1/etc/profile.d/flatpak-bindir.sh"
