#!/bin/sh -e

for font in ttf/*.ttf
do
install -Dm755 "$font" "$1/usr/share/fonts/TTF/$font"
done

for font in *.ttf
do
install -Dm755 "$font" "$1/usr/share/fonts/TTF/$font"
done

for font in *.otf
do
install -Dm755 "$font" "$1/usr/share/fonts/OTF/$font"
done



