#!/bin/bash -e

# remove flit_core check
sed -i 's/<4//g' pyproject.toml

PREFIX="${CROSS_PREFIX:-/usr}"
python -m build --wheel --no-isolation
python -m installer --destdir="$1" --prefix="$PREFIX" dist/*.whl
