#!/bin/bash -e

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_OPT="--host=${HOKUTO_ARCH}-linux-gnu"
else
    HOST_OPT=""
fi

./configure --prefix=${CROSS_PREFIX:-/usr} \
            --disable-static \
            $HOST_OPT

make
make DESTDIR=$1 install


if [ "$MULTILIB" = "1" ]; then
#32bit split package
make distclean
CC="gcc -m32" ./configure \
    --prefix=/usr         \
    --disable-static      \
    --libdir=/usr/lib32   \
    --libexecdir=/usr/lib32   \
    --host=i686-pc-linux-gnu

make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
