#!/bin/sh -e

meson setup build       \
    --prefix=/usr       \
    --buildtype=release \
    -D gst_debug=false

meson compile -C build
meson install -C build --destdir=$1

#32bit
rm -rf build
meson setup build       \
    --prefix=/usr       \
    --libdir=/usr/lib32 \
    --cross-file=lib32  \
    --buildtype=release \
    -D gst_debug=false

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
install -d $1/usr/lib32
cp -vR DESTDIR/usr/lib32/* $1/usr/lib32
