#!/bin/sh -e

mkdir build
cd build

meson  --prefix=/usr       \
       --buildtype=release \
       -Dgst_debug=false

ninja
DESTDIR=$1 ninja install

#32bit

rm -rf *
meson setup --prefix=/usr       \
                --libdir=/usr/lib32 \
                --cross-file=lib32  \
                --buildtype=release \
                -Dgst_debug=false \
                ..
ninja
DESTDIR=$PWD/DESTDIR ninja install
install -d $1/usr/lib32
cp -vR DESTDIR/usr/lib32/* $1/usr/lib32
