#!/bin/bash -e

autoreconf -vif
./configure --prefix=/usr

sed -e 's/ -shared / -Wl,-O1,--as-needed\0/g' -i libtool # Fix overlinking
make
make DESTDIR="${1}" install

# install missing headers
install -Dm644 *.h -t "${1}"/usr/include/squashfuse
