#!/bin/sh -e
set +h
umask 022

ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64
ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64/ld-lsb-x86-64.so.3

mkdir build
cd build

echo "rootsbindir=/usr/sbin" > configparms
../configure                             \
      --prefix=/usr                      \
      --host=$LFS_TGT                    \
      --build=$(../scripts/config.guess) \
      --disable-nscd                     \
      libc_cv_slibdir=/usr/lib           \
      --enable-kernel=5.4

make
make DESTDIR=$LFS install

sed '/RTLDLIST=/s@/usr@@g' -i $LFS/usr/bin/ldd

#32bit
make clean
find .. -name "*.a" -delete
CC="$LFS_TGT-gcc -m32" \
CXX="$LFS_TGT-g++ -m32" \
../configure                             \
      --prefix=/usr                      \
      --host=$LFS_TGT32                  \
      --build=$(../scripts/config.guess) \
      --disable-nscd                     \
      --with-headers=$LFS/usr/include    \
      --libdir=/usr/lib32                \
      --libexecdir=/usr/lib32            \
      libc_cv_slibdir=/usr/lib32         \
      --enable-kernel=6.16

make
make DESTDIR=$PWD/DESTDIR install
cp -a DESTDIR/usr/lib32 $LFS/usr/
install -vm644 DESTDIR/usr/include/gnu/{lib-names,stubs}-32.h \
               $LFS/usr/include/gnu/
ln -svf ../lib32/ld-linux.so.2 $LFS/lib/ld-linux.so.2

# checks
set +e
echo -e "\033[0;32mRunning basic toolchain sanity checks\033[0m"
echo 'int main(){}' > dummy.c
$LFS_TGT-gcc -m32 dummy.c
readelf -l a.out | grep '/ld-linux'
echo -e "\033[0;32mCorrect output:\n[Requesting program interpreter: /lib/ld-linux.so.2]\033[0m"
echo 'int main(){}' | $LFS_TGT-gcc -x c - -v -Wl,--verbose &> dummy.log
readelf -l a.out | grep ': /lib'
echo -e "\033[0;32mCorrect output:\n[Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]\033[0m"
grep -E -o "$LFS/lib.*/S?crt[1in].*succeeded" dummy.log
echo -e "\033[0;32mCorrect output:\n$LFS/lib/../lib/Scrt1.o succeeded\n$LFS/lib/../lib/crti.o succeeded\n$LFS/lib/../lib/crtn.o succeeded\033[0m"
grep -B3 "^ $LFS/usr/include" dummy.log
echo -e "\033[0;32mCorrect output:\n$LFS/tools/lib/gcc/x86_64-lfs-linux-gnu/15.2.0/include\n$LFS/tools/lib/gcc/x86_64-lfs-linux-gnu/15.2.0/include-fixed\n$LFS/usr/include\033[0m"
grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
echo -e "\033[0;32mCorrect output:\nSEARCH_DIR(\"=$LFS/tools/x86_64-lfs-linux-gnu/lib64\")\nSEARCH_DIR(\"=/usr/local/lib64\")\nSEARCH_DIR(\"=/lib64\")\nSEARCH_DIR(\"=/usr/lib64\")\nSEARCH_DIR(\"=$LFS/tools/x86_64-lfs-linux-gnu/lib\")\nSEARCH_DIR(\"=/usr/local/lib\")\nSEARCH_DIR(\"=/lib\")\nSEARCH_DIR(\"=/usr/lib\");\033[0m"
grep "/lib.*/libc.so.6 " dummy.log
echo -e "\033[0;32mCorrect output:\nattempt to open $LFS/usr/lib/libc.so.6 succeeded\033[0m"
grep found dummy.log
echo -e "\033[0;32mCorrect output:\nfound ld-linux-x86-64.so.2 at $LFS/usr/lib/ld-linux-x86-64.so.2\033[0m"
set -e
read -p "Press Enter to continue" < /dev/tty
