#!/bin/bash -e

#gcc 15 fix
sed -e 's/; i.*size)/, e = end(); i != e; ++i, ++size_)/' \
    -i modules/speller/default/vector_hash-t.hpp

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi

./configure --prefix="$PREFIX" "${CROSS_OPTS[@]}"
make
make DESTDIR=$1 install

install -v -m 755 scripts/ispell $1$PREFIX/bin/
install -v -m 755 scripts/spell $1$PREFIX/bin/
