#!/bin/sh -e

sudo pip install pytest
sudo pip install python-dbusmock

mkdir build
cd build

meson --prefix=/usr -Dinstalled-tests=false \
      -Ddocumentation=disabled \
      -Dsandboxed-sound-validation=disabled \
      -Dtests=disabled ..

ninja
DESTDIR=$1 ninja install
