#!/bin/sh -e

mkdir build
cd    build

cmake -D CMAKE_INSTALL_PREFIX=/usr                   \
      -D CMAKE_BUILD_TYPE=Release                    \
      -D BUILD_SHARED_LIBS=ON                        \
      -D CMAKE_SKIP_INSTALL_RPATH=ON                 \
      -D LLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=/usr \
      -G Ninja ..

ninja
DESTDIR=$1 ninja install

#32bit

rm -rf *
CC="gcc -m32" CXX="g++ -m32"                         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig                 \
cmake -D CMAKE_INSTALL_PREFIX=/usr                   \
      -D CMAKE_INSTALL_LIBDIR=lib32                  \
      -D CMAKE_BUILD_TYPE=Release                    \
      -D CMAKE_SKIP_INSTALL_RPATH=ON                 \
      -D BUILD_SHARED_LIBS=ON                        \
      -D LLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=/usr \
      -G Ninja ..

ninja
DESTDIR=$PWD/DESTDIR ninja install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
