#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddocs=false \
    -Dgir=false \
    -Dfribidi=false \
    -Dicu=false \
    -Dvapi=false \
    -Dgnutls=true \
    -D_systemd=true \
    . output

ninja -C output
ninja -C output install
