#!/bin/bash -e

# Add Xfce pluggable support
# Manual implementation of the --xfce-integration flag logic which is not compatible with PEP517
echo "X-XfcePluggable=true" >> lightdm-gtk-greeter-settings.desktop.in
# Fix __data_directory__ value in installation_config.py when using PEP517
sed -i "s|\(target_pkgdata = \)target_data|\1'/usr/'|" setup.py

python -m build --wheel --no-isolation
python -m installer --destdir="${1}" dist/*.whl
