#!/bin/bash -e

cmake -B build-native \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D CMAKE_POLICY_VERSION_MINIMUM=3.5

cmake --build build-native
DESTDIR=$1 cmake --install build-native

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
cmake_options=(
    -B build-multilib
    -D CMAKE_BUILD_TYPE=None
    -D CMAKE_INSTALL_PREFIX=/usr
    -D CMAKE_INSTALL_LIBDIR=/usr/lib32
    -D CMAKE_INSTALL_INCLUDEDIR=/usr/include/libtiff32
    -D CMAKE_POLICY_VERSION_MINIMUM=3.5
    -D BUILD_SHARED_LIBS=ON
    -D tiff-static=OFF
    -D tiff-tools=OFF
    -D tiff-tests=OFF
    -D tiff-contrib=OFF
    -D tiff-docs=OFF
    -D tiff-opengl=OFF
    -D webp=OFF
)

export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"

cmake "${cmake_options[@]}"
cmake --build build-multilib
DESTDIR="$pkgdir" cmake --install build-multilib
rm -rf "${pkgdir}"/usr/{share,bin}
fi
