#!/bin/bash -e

GUDEV_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # gobject-introspection and vala bindings need to run target binaries to
    # scan them, which cannot happen while cross compiling.
    GUDEV_OPTS+=(-D introspection=disabled -D vapi=disabled -D tests=disabled)
fi

hokuto-meson build "${GUDEV_OPTS[@]}"
meson compile -C build
meson install -C build --destdir=$1

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
rm -rf build
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
hokuto-meson-32 build        \
  -D gtk_doc=false           \
  -D introspection=disabled  \
  -D tests=disabled          \
  -D vapi=disabled

meson compile -C build
meson install -C build --destdir=$pkgdir
rm -r "$pkgdir/usr/include"
fi
