#!/bin/bash -e

hokuto-meson build
meson compile -C build
meson install -C build --destdir=$1

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
rm -rf build
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
hokuto-meson-32 build        \
  -D gtk_doc=false           \
  -D introspection=disabled  \
  -D tests=disabled          \
  -D vapi=disabled

meson compile -C build
meson install -C build --destdir=$pkgdir
rm -r "$pkgdir/usr/include"
fi
