#!/bin/sh -e

CONF_ARGS="--prefix=$CROSS_PREFIX \
    --without-xmlwf \
    --without-examples \
    --without-tests \
    --without-docbook"

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CONF_ARGS="$CONF_ARGS --host=$HOKUTO_ARCH-linux-gnu"
fi

./configure $CONF_ARGS

make
make DESTDIR=$1 install

# Remove documentation (Changelogs, etc).
# Use -f to avoid failing if share directory doesn't exist
rm -rf "${1:?}/$CROSS_PREFIX/share"

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit
sed -e "/^am__append_1/ s/doc//" -i Makefile
make clean
CC="gcc -m32" ./configure \
    --prefix=/usr        \
    --disable-static     \
    --libdir=/usr/lib32  \
    --host=i686-pc-linux-gnu

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
fi
