#!/bin/bash
# Cross-compiler wrapper for cargo
# Sets the target by default so you don't have to pass --target every time
export CARGO_BUILD_TARGET="aarch64-unknown-linux-gnu"
# DO NOT set --sysroot here, rely on symlinked libraries in host rustc
exec /usr/bin/cargo "$@"
