#!/bin/bash -e

cmake -B build \
  -D CMAKE_BUILD_TYPE=None \
  -D CMAKE_INSTALL_PREFIX="${CROSS_PREFIX:-/usr}" \
  -W no-dev \
  -D UNIT_TESTING=ON

cmake --build build
DESTDIR="${1}" cmake --install build
