#!/bin/sh -e

CFLAGS=" " ./configure --prefix=/usr       \
            --enable-cmdlib     \
            --enable-pkgconfig  \
            --enable-udev_sync

make
make DESTDIR=$1 install
make DESTDIR=$1 install_systemd_units
