#!/bin/sh -e

git rm -r externals/MoltenVK
git rm -r externals/date
git rm -r externals/ext-boost
git rm -r externals/ffmpeg-core
git rm -r externals/glslang
git rm -r externals/json
git rm -r externals/libpng
git rm -r externals/pugixml
git rm -r externals/zlib-ng
git submodule update --init --recursive --depth 1

# fix nlohmann-json
sed -E -e '/nlohmann_json/i find_package(nlohmann_json)' -i CMakeLists.txt
sed -E -e '/add_subdirectory\(json\)/d' -i externals/CMakeLists.txt

# allow any version
sed -E -e '/find_package/s&(glslang) \S+ (CONFIG)&\1 \2&' -i CMakeLists.txt

# respect system build flags
sed -E -e '/march/d' -i CMakeLists.txt

# set version info
sed -E -e 's&@APP_IS_RELEASE@&true&' \
  -e 's&@APP_VERSION@&'"${2:?}&" \
  -i src/common/scm_rev.cpp.in

sed -E -e 's&(fmt::format)\("shadPS4 v&\1("shadPS4 &' \
  -i src/emulator.cpp

cmake -B build \
  -G Ninja     \
  -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE=ON \
  -D CMAKE_C_COMPILER=clang \
  -D CMAKE_CXX_COMPILER=clang++ \
  -D CMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" \
  -D CMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold" \
  -D CMAKE_INSTALL_PREFIX='/usr' \
  -D CMAKE_SKIP_RPATH=ON \
  -D BUILD_TESTING=OFF \
  -D TRACY_ENABLE=OFF \
  -D ENABLE_UPDATER=OFF \
  -D SIRIT_USE_SYSTEM_SPIRV_HEADERS=ON \
  -Wno-dev

cmake --build build
install -Dm755 build/shadps4 "$1/usr/bin/shadps4"

