#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

cross_opts=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # The python bindings would need the target interpreter at build time and
    # nothing here consumes them -- lxml links the C library directly.
    cross_opts=(--host="${HOKUTO_ARCH}-linux-gnu" --without-python)
fi

./configure --prefix="$PREFIX" \
  --disable-static \
  "${cross_opts[@]}"

make
make DESTDIR=$1 install
