#!/bin/sh -e

./configure --prefix=/usr \
    --disable-static  \
    --sysconfdir=/etc

make
make DESTDIR="$1" install

#32bit

make distclean
CC="gcc -m32" ./configure \
    --prefix=/usr         \
    --disable-static      \
    --sysconfdir=/etc     \
    --libdir=/usr/lib32   \
    --host=i686-pc-linux-gnu
make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
