#!/bin/sh -e

mkdir -p kernel/x86/microcode
cat amd-ucode/microcode_amd*.bin > kernel/x86/microcode/AuthenticAMD.bin

make DESTDIR="$1" FIRMWAREDIR=/usr/lib/firmware install

echo "compressing firmware"
find $1/usr/lib/firmware -type f -exec xz "{}" \;

# Trigger a microcode reload for configurations not using early updates
echo 'w /sys/devices/system/cpu/microcode/reload - - - - 1' |
install -Dm644 /dev/stdin "$1/usr/lib/tmpfiles.d/linux-firmware.conf"

#AMD microcode
cat amd-ucode/microcode_amd*.bin > amd-ucode.img
install -Dt "$1/boot" -m644 amd-ucode.img
