#!/bin/sh -e

# apply archlinux patches
patch -Np1 -i 0001-Disable-replaced-tools-their-man-pages-and-PAM-integ.patch
patch -Np1 -i 0002-Adapt-login.defs-for-PAM-and-util-linux.patch
patch -Np1 -i 0003-Add-Arch-Linux-defaults-for-login.defs.patch

autoreconf -fvi

configure_options=(
    --bindir=/usr/bin
    --disable-account-tools-setuid  # no setuid for chgpasswd, chpasswd, groupadd, groupdel, groupmod, newusers, useradd, userdel, usermod
    --enable-man
    --libdir=/usr/lib
    --mandir=/usr/share/man
    --prefix=/usr
    --sbindir=/usr/bin
    --sysconfdir=/etc
    --with-fcaps  # use capabilities instead of setuid for setuidmap and setgidmap
    --with-group-name-max-length=32
    --with-libpam  # PAM integration for chpasswd, groupmems, newusers, passwd
    --with-yescrypt
    --without-bcrypt
    --without-libbsd  # shadow can use internal implementation for getting passphrase
    --without-nscd  # we do not ship nscd anymore
    --without-selinux
    --without-su  # su is provided by util-linux
)

# add extra check, preventing accidental deletion of other user's home dirs when using `userdel -r <user with home in />`
export CFLAGS="$CFLAGS -DEXTRA_CHECK_HOME_DIR"
./configure "${configure_options[@]}"

# prevent excessive overlinking due to libtool
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make DESTDIR=$1 install
make DESTDIR=$1 -C man install

# custom useradd(8) defaults (not provided by upstream)
install -vDm 600 useradd.defaults "$1/etc/default/useradd"

# systemd units
install -vDm 644 shadow.timer -t "$1/usr/lib/systemd/system/"
install -vDm 644 shadow.service -t "$1/usr/lib/systemd/system/"
install -vdm 755 "$1/usr/lib/systemd/system/timers.target.wants"
ln -s shadow.timer "$1/usr/lib/systemd/system/timers.target.wants/shadow.timer"

install -vDm 644 $3.sysusers "$1/usr/lib/sysusers.d/$3.conf"
install -vDm 644 $3.tmpfiles "$1/usr/lib/tmpfiles.d/$3.conf"

# adapt executables to match the modes used by tmpfiles.d, so that pacman does not complain:
chmod 750 "$1/usr/bin/groupmems"
