#!/bin/bash -e

# Backport shadow-maint/shadow@ba4419c5, committed just after 4.20.0.
# uintmax_t is declared by <stdint.h>; relying on a transitive include breaks
# with current toolchains.
sed -i '/#include <stdio.h>/i #include <stdint.h>' \
    lib/find_new_sub_gids.c \
    lib/find_new_sub_uids.c

configure_options=(
    --bindir=/usr/bin
    --disable-account-tools-setuid  # no setuid for chgpasswd, chpasswd, groupadd, groupdel, groupmod, newusers, useradd, userdel, usermod
    --enable-man
    --libdir=/usr/lib
    --mandir=/usr/share/man
    --prefix=/usr
    --sbindir=/usr/bin
    --sysconfdir=/etc
    --disable-logind # not required we use login from util-linux
    --with-fcaps  # use capabilities instead of setuid for setuidmap and setgidmap
    --with-group-name-max-length=32
    --with-libpam  # PAM integration for chpasswd, groupmems, newusers, passwd
    --with-yescrypt
    --without-bcrypt
    --without-libbsd  # shadow can use internal implementation for getting passphrase
    --without-nscd  # we do not ship nscd anymore
    --without-selinux
    --without-su  # su is provided by util-linux
)

# add extra check, preventing accidental deletion of other user's home dirs when using `userdel -r <user with home in />`
export CFLAGS="$CFLAGS -DEXTRA_CHECK_HOME_DIR"
./configure "${configure_options[@]}"

# prevent excessive overlinking due to libtool
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
# usbindir is hardcoded to $prefix/sbin in src/Makefile.am; /usr/sbin is a
# symlink to bin here, so install the admin tools where they belong.
make DESTDIR=$1 usbindir=/usr/bin install
make DESTDIR=$1 -C man install

# util-linux provides login, nologin, chfn, chsh, newgrp/sg, vipw/vigr and su
# (with their PAM files), coreutils provides groups: drop shadow's copies,
# their man pages and PAM files.
_replaced="login nologin chfn chsh newgrp sg vipw vigr su groups"
for _t in $_replaced; do
    rm -f "$1/usr/bin/$_t" "$1/usr/sbin/$_t" "$1/etc/pam.d/$_t"
done
find "$1/usr/share/man" -regextype posix-extended \
    -regex ".*/($(echo $_replaced | tr ' ' '|'))\.[1-8](\.[a-z0-9]+)?" -delete
rmdir "$1/usr/sbin" 2>/dev/null || true

# login.defs adapted for PAM and util-linux, with sauzerOS defaults
# (yescrypt, system IDs from 500, HOME_MODE 0700, no duplicate MOTD)
install -vDm 644 login.defs "$1/etc/login.defs"

# custom useradd(8) defaults (not provided by upstream)
install -vDm 600 useradd.defaults "$1/etc/default/useradd"

# systemd units
install -vDm 644 shadow.timer -t "$1/usr/lib/systemd/system/"
install -vDm 644 shadow.service -t "$1/usr/lib/systemd/system/"
install -vdm 755 "$1/usr/lib/systemd/system/timers.target.wants"
ln -s ../shadow.timer "$1/usr/lib/systemd/system/timers.target.wants/shadow.timer"

install -vDm 644 $3.sysusers "$1/usr/lib/sysusers.d/$3.conf"
install -vDm 644 $3.tmpfiles "$1/usr/lib/tmpfiles.d/$3.conf"
