#!/bin/sh -e

cmake -B build \
  -D CMAKE_BUILD_TYPE=Release \
  -D CMAKE_INSTALL_PREFIX="/usr" \
  -D CMAKE_INSTALL_LIBDIR="lib" \
  -D python-bindings=ON \
  -D boost-python-module-name="python" \
  -D python-egg-info=ON

cmake --build build
DESTDIR=$1 cmake --install build
