#!/bin/sh -e

#fix build with boost 1.78.0
patch -p1 -i 71d608fc.patch

mkdir build
cd build


cmake -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -Dpython-bindings=ON \
    -Dboost-python-module-name="python" \
    -Dpython-egg-info=ON \
    -GNinja ..

ninja
ninja install
