#!/bin/sh

for kver in /lib/modules/*; do
    if [ -d "$kver" ]; then
        echo "Running depmod for $(basename "$kver")"
        depmod -a "$(basename "$kver")"
    fi
done


if hokuto check nvidia-modules; then
hokuto build -a nvidia-modules
fi

if hokuto check cdemu-vhba-module; then
hokuto build -a cdemu-vhba-module
fi

