#!/bin/sh -e

# TODO: These tests invoke the TTY and our container *really* does not like that
rm pkg/cmd/auth/login/login_test.go
# Drop tests that invoking 3rd party server processes
rm pkg/cmd/search/shared/shared_test.go \
   internal/codespaces/rpc/invoker_test.go


export CGO_CPPFLAGS="${CPPFLAGS}"
export CGO_CFLAGS="${CFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"
export CGO_LDFLAGS="${LDFLAGS}"
export GOFLAGS='-buildmode=pie -trimpath -mod=readonly -modcacherw'

make GH_VERSION=$2 bin/gh manpages
bin/gh completion -s bash | install -Dm0644 /dev/stdin share/bash-completion/completions/gh
bin/gh completion -s zsh  | install -Dm0644 /dev/stdin share/zsh/site-functions/_gh
bin/gh completion -s fish | install -Dm0644 /dev/stdin share/fish/vendor_completions.d/gh.fish
make DESTDIR=$1 prefix="/usr" install
cp -r share/ "$1"/usr
