#!/bin/sh -e

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure --prefix="$PREFIX" \
    --disable-static \
    $CROSS_OPTS

make
make DESTDIR="$1" install


if [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
CC="gcc -m32" ./configure \
    --prefix=/usr         \
    --disable-static      \
    --libdir=/usr/lib32   \
    --libexecdir=/usr/lib32   \
    --host=i686-pc-linux-gnu

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
fi
