#!/bin/sh -e

# Don't build GTK examples/demos/testsuite.
sed 's/demos tests testsuite examples//;s/docs \(m4macros\)/\1/' Makefile.in > _
mv -f _ Makefile.in

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-wayland-backend \
    --enable-x11-backend \
    --disable-cups \
    --disable-papi \
    --disable-cloudprint \
    --disable-glibtest \
    --disable-nls \
    --disable-installed-tests \
    --enable-introspection=no \
    --enable-colord=no \
    --enable-gtk-doc-html=no

make
make DESTDIR="$1" install

# We don't compile with librsvg which leads to this
# utility solely causing compiler errors for some
# packages. It has no use at all.
#rm -f "$1/usr/bin/gtk-encode-symbolic-svg"
