#!/bin/sh -e

mkdir build
cd    build

meson setup ..                 \
      --prefix=/usr            \
      --buildtype=release      \
      -D man=false             \
      -D broadway_backend=true
ninja
DESTDIR=$1 ninja install

cd ..
mkdir -p $1/etc/gtk-3.0/
cp settings.ini $1/etc/gtk-3.0/
