#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"
sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf

for p in readline83-*; do
    patch -Np0 -i "$p";
done

# Use CROSS_PREFIX if set (defaults to /usr in hokuto)
PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET --build=$(gcc -dumpmachine)"
    
    # Readline requires knowing if wcwidth is broken (can't test when cross compiling)
    export bash_cv_wcwidth_broken=no
fi

./configure \
    --prefix="$PREFIX" \
    $CROSS_OPTS

make SHLIB_LIBS=-lncursesw
make DESTDIR="$1" install

if [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
CC="gcc -m32" ./configure \
    --host=i686-pc-linux-gnu      \
    --prefix=/usr                 \
    --libdir=/usr/lib32           \
    --disable-static              \
    --with-curses
make SHLIB_LIBS="-lncursesw"
make SHLIB_LIBS="-lncursesw" DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
fi
