#!/bin/sh -e

./configure --prefix=/usr      \
            --sysconfdir=/etc  \
            --with-bzip2       \
            --with-lzma

make
make DESTDIR=$1 install

ln -s /usr/bin/wget2 $1/usr/bin/wget
