#!/bin/sh -e

mkdir -v build
cd       build

../configure --prefix=/usr \
    --sysconfdir=$1/etc \
    --with-lib-path=/usr/lib:/usr/local/lib \
    --enable-cet \
    --enable-colored-disassembly \
    --enable-default-execstack=no \
    --enable-deterministic-archives \
    --enable-install-libiberty \
    --enable-ld=default \
    --enable-new-dtags \
    --enable-pgo-build=lto \
    --enable-plugins \
    --enable-relro \
    --enable-shared \
    --enable-threads \
    --disable-gdb \
    --disable-gdbserver \
    --disable-libdecnumber \
    --disable-readline \
    --disable-sim \
    --disable-werror \
    --with-debuginfod \
    --with-pic \
    --with-system-zlib

make tooldir=/usr
make tooldir=/usr DESTDIR=$1 install
