#!/bin/sh -e

mkdir -v build
cd       build


../configure --prefix=/usr       \
             --sysconfdir=/etc   \
             --enable-gold       \
             --enable-ld=default \
             --enable-plugins    \
             --enable-shared     \
             --disable-werror    \
             --enable-new-dtags  \
	     --enable-64-bit-bfd \
	     --enable-default-hash-style=gnu \
             --with-system-zlib

make tooldir=/usr
make tooldir=/usr DESTDIR=$1 install

rm -rf $1/usr/share/info
