#!/bin/bash -e

hokuto-meson build      \
  -D tests=false        \
  -D docs=false         \
  -D introspection=true \
  -D vapi=true          \
  -D examples=false     \
  -D smoke-tests=false

meson compile -C build
meson install -C build --destdir=$1
