#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi

./configure \
    --prefix="$PREFIX" \
    --disable-nls \
    --disable-gpg-test \
    "${CROSS_OPTS[@]}"

make
make DESTDIR="$1" install
# Ensure that gpgme-config is always installed
cp -f src/gpgme-config "$1$PREFIX/bin/"
