#!/bin/sh -e

cmake_options=(
  -D BUILD_SHARED_LIBS=ON
  -D CMAKE_BUILD_TYPE=None
  -D CMAKE_INSTALL_LIBDIR=/usr/lib
  -D CMAKE_INSTALL_PREFIX=/usr
  -D CMAKE_SKIP_INSTALL_RPATH=ON
  -D WEBP_BUILD_CWEBP=ON
  -D WEBP_BUILD_DWEBP=ON
  -D WEBP_BUILD_EXTRAS=OFF
  -D WEBP_BUILD_GIF2WEBP=ON
  -D WEBP_BUILD_IMG2WEBP=ON
  -D WEBP_BUILD_VWEBP=OFF
)

# Mimic autotools build without --enable-asserts
CFLAGS+=" -DNDEBUG"
CXXFLAGS+=" -DNDEBUG"

cmake -B build "${cmake_options[@]}"
cmake --build build
DESTDIR=$1 cmake --install build
