#!/bin/bash -e

cmake -B build                 \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D MZ_BUILD_TESTS=ON         \
  -D BUILD_SHARED_LIBS=ON      \
  -D CMAKE_BUILD_TYPE=Release

cmake --build build
DESTDIR=$1 cmake --install build

# symlink for zip compat
ln -s /usr/bin/minizip $1/usr/bin/zip
