#!/bin/sh -e

#cmake fix
sed -r '/cmake_policy.*(0025|0054)/d' -i source/CMakeLists.txt
mkdir bld
cd bld

cmake -D CMAKE_INSTALL_PREFIX=/usr        \
      -D GIT_ARCHETYPE=1                  \
      -D CMAKE_POLICY_VERSION_MINIMUM=3.5 \
      -W no-dev ../source

make
make DESTDIR=$1 install
rm -vf $1/usr/lib/libx265.a

#32bit

rm -rf *
CC="gcc -m32" CXX="g++ -m32"              \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig      \
cmake -D CMAKE_INSTALL_PREFIX=/usr        \
      -D LIB_INSTALL_DIR=lib32            \
      -D GIT_ARCHETYPE=1                  \
      -D CMAKE_POLICY_VERSION_MINIMUM=3.5 \
      -W no-dev ../source

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vR DESTDIR/usr/lib32/* $1/usr/lib32
rm -vf $1/usr/lib32/libx265.a
