#!/bin/sh -e

./configure --prefix=/usr       \
            --with-wolfssl      \
            --host=$LFS_TGT     \
            --disable-shared    \
            --enable-static     \
            --disable-zlib      \
            --without-zstd      \
            --disable-aws       \
            --disable-hsts      \
            --disable-alt-svc   \
            --disable-headers-api \
            --with-ca-bundle=/etc/ssl/ca-certificates.crt \
        LIBS="-lwolfssl -lm"    \
ac_cv_func_malloc_0_nonnull=yes \
ac_cv_func_realloc_0_nonnull=yes

make
make DESTDIR=$LFS install

install -Dm644 ../ca-certificates.crt $LFS/etc/ssl/ca-certificates.crt
