#!/bin/sh -e

sed -i -E 's/(ln -s)/\1f/' rules/meson.build

PREFIX="${CROSS_PREFIX:-/usr}"

MESON_OPTS=(
    --prefix="$PREFIX"
    --buildtype=release
)

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    MESON_OPTS+=(--cross-file "$HOKUTO_ARCH")
fi

meson setup build "${MESON_OPTS[@]}"
meson compile -C build
meson install -C build --destdir=$1

