#!/bin/sh -e

_backports=(
  # f2fs-tools: fix build error on lz4-1.9.4
  '19f77c6f6277a274434d6d8883f50e7955c6a8db'
  # f2fs-tools: use stdbool.h instead of bool
  '6617d15a660becc23825007ab3fc2d270b5b250f'
)

for _c in "${_backports[@]}"; do
  if [[ $_c == *..* ]]; then
    git log --oneline --reverse "${_c}"
  else
    git log --oneline -1 "${_c}"
  fi
  git cherry-pick -n -m1 "${_c}"
done
for _c in "${_reverts[@]}"; do
  git log --oneline -1 "${_c}"
  git revert -n "${_c}"
done

./autogen.sh
./configure --prefix=/usr \
            --bindir=/usr/bin \
            --sbindir=/usr/bin \
            --disable-static

make
make DESTDIR="$1" install

