#!/bin/bash -e

_backports=(
)

for _c in "${_backports[@]}"; do
  if [[ $_c == *..* ]]; then
    git log --oneline --reverse "${_c}"
  else
    git log --oneline -1 "${_c}"
  fi
  git cherry-pick -n -m1 "${_c}"
done
for _c in "${_reverts[@]}"; do
  git log --oneline -1 "${_c}"
  git revert -n "${_c}"
done

./autogen.sh
./configure --prefix=/usr \
            --bindir=/usr/bin \
            --sbindir=/usr/bin \
            --disable-static

make
make DESTDIR="$1" install

