#!/bin/sh -e

#add scanner group if required
if [ $(getent group admin) ];then
sudo groupadd -g 70 scanner
fi

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --with-group=scanner \
            --enable-libusb_1_0  \
            --with-lockdir=/run/lock

make
make install

install -Dm 644 -v tools/udev/libsane.rules           \
                  $1/etc/udev/rules.d/65-scanner.rules
mkdir -p          $1/run/lock/sane
sudo chgrp -v scanner  $1/run/lock/sane
