#!/bin/sh -e

./autogen.sh
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --with-group=scanner \
            --enable-libusb_1_0  \
            --with-lockdir=/run/lock

make
make DESTDIR=$1 install

install -Dm 644 -v tools/udev/libsane.rules           \
                  $1/etc/udev/rules.d/65-scanner.rules

install -d        $1/run/lock/sane
