#!/bin/sh -e

meson setup build \
  --prefix=/usr \
  -D glamor=true \
  -D dri3=true \
  -D xkb_dir=/usr/share/X11/xkb \
  -D xkb_output_dir=/var/lib/xkb \

meson compile -C build
meson install -C build --destdir=$1
