#!/bin/bash -e

# Fix for 'private' becoming a reserved keyword as of GCC 4.3+
patch -p0 -i cdparanoia-r15388.patch
# Add missing printf format strings for `-Wformat -Werror=format-security`
patch -p1 -i cdparanoia-10.2-format-security.patch
# Use LDFLAGS
patch -p1 -i cdparanoia-10.2-ldflags.patch

./configure --prefix=/usr \
  --mandir=/usr/share/man

make -j1
make prefix="$1"/usr MANDIR="$1"/usr/share/man install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make distclean
dest_dir=$HOKUTO_SPLIT_DIR/lib32-cdparanoia
install -d $dest_dir
export CC='gcc -m32'
export CXX='g++ -m32'
export CFLAGS+=' -Wno-format-security'
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
autoreconf -fiv
./configure \
  --prefix=$dest_dir/usr \
  --libdir=$dest_dir/usr/lib32

make -j1
make DESTDIR=$dest_dir install
rm -rf "${dest_dir}"/usr/{bin,include,share}
fi
