#!/bin/bash -e

# Fix for 'private' becoming a reserved keyword as of GCC 4.3+
patch -p0 -i cdparanoia-r15388.patch
# Add missing printf format strings for `-Wformat -Werror=format-security`
patch -p1 -i cdparanoia-10.2-format-security.patch
# Use LDFLAGS
patch -p1 -i cdparanoia-10.2-ldflags.patch

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
    # The 2008 config.sub does not know aarch64. configure copies
    # configure.sub and configure.guess over config.sub and config.guess.
    automake_dir=$(ls -d /usr/share/automake-* | sort -V | tail -n1)
    cp -f "$automake_dir"/config.sub configure.sub
    cp -f "$automake_dir"/config.guess configure.guess
fi

./configure --prefix="$PREFIX" \
  --mandir="$PREFIX/share/man" \
  "${CROSS_OPTS[@]}"

make -j1
make prefix="$1$PREFIX" MANDIR="$1$PREFIX/share/man" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make distclean
dest_dir=$HOKUTO_SPLIT_DIR/lib32-cdparanoia
install -d $dest_dir
export CC='gcc -m32'
export CXX='g++ -m32'
export CFLAGS+=' -Wno-format-security'
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
autoreconf -fiv
./configure \
  --prefix=$dest_dir/usr \
  --libdir=$dest_dir/usr/lib32

make -j1
make DESTDIR=$dest_dir install
rm -rf "${dest_dir}"/usr/{bin,include,share}
fi
