#!/bin/sh -e

rm -f intel-ucode{,-with-caveats}/list
mkdir -p kernel/x86/microcode
iucode_tool --write-earlyfw=intel-ucode.img intel-ucode{,-with-caveats}/

install -vDm 644 ${3}/* -t "${1}/usr/lib/firmware/${3}/"
install -D -m0644 intel-ucode.img "${1}"/boot/intel-ucode.img
