#!/bin/sh -e

python -m build --wheel --no-isolation
_site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
python -m installer --destdir="${1}" dist/*.whl

PYTHONPATH="${1}/$_site_packages" "${1}"/usr/bin/pip completion --bash | install -vDm 644 /dev/stdin "${1}"/usr/share/bash-completion/completions/pip
PYTHONPATH="${1}/$_site_packages" "${1}"/usr/bin/pip completion --zsh | tail -n+3 | install -vDm 644 /dev/stdin "${1}"/usr/share/zsh/site-functions/_pip
PYTHONPATH="${1}/$_site_packages" "${1}"/usr/bin/pip completion --fish | install -vDm 644 /dev/stdin "${1}"/usr/share/fish/vendor_completions.d/pip.fish
