#!/bin/sh -e

cmake -B build \
  -D CMAKE_BUILD_TYPE=Release \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D CMAKE_INSTALL_LIBDIR=lib \
  -D ENABLE_ACCOUNTS_SERVICE=off

cmake --build build
DESTDIR=$1 cmake --install build
