#!/bin/sh -e

mkdir build
cd build

cmake   -DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib \
	-DENABLE_ACCOUNTS_SERVICE=off \
	-GNinja ..

 ninja
 DESTDIR=$1 ninja install
