#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

cmake -B build \
  -D CMAKE_BUILD_TYPE=Release \
  -D CMAKE_INSTALL_PREFIX="$PREFIX" \
  -D CMAKE_INSTALL_LIBDIR=lib \
  -D ENABLE_ACCOUNTS_SERVICE=off

cmake --build build
DESTDIR=$1 cmake --install build
