#!/bin/sh -e

PREFIX="${CROSS_PREFIX:-/usr}"

# Default to -fPIC for everyone
export CFLAGS_FOR_BUILD="-fPIC"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    TARGET_ARCH="$HOKUTO_ARCH"
    # Normalize arm64 to aarch64
    if [ "$TARGET_ARCH" = "arm64" ]; then TARGET_ARCH="aarch64"; fi
    CROSS_OPTS="--host=${TARGET_ARCH}-linux-gnu"
    # libx11 needs to build 'makekeys' for the host to generate keys
    export CC_FOR_BUILD="gcc"
fi

# Use the exported variable; do not override it here
./configure \
    --prefix="$PREFIX" \
    --without-xmlto \
    --disable-specs \
    --disable-static \
    $CROSS_OPTS

make
make DESTDIR="$1" install

if [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
CC="gcc -m32" CXX="g++ -m32" PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --disable-specs \
    --without-xmlto \
    --disable-static \
     --libdir=/usr/lib32

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
fi
