#!/bin/bash -e

./configure --prefix=/usr \
  --sysconfdir=/etc       \
  --localstatedir=/var    \
  --enable-binaries       \
  --disable-static

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make distclean
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
export CC="gcc -m32"
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
./configure --prefix=/usr \
  --sysconfdir=/etc       \
  --localstatedir=/var    \
  --disable-binaries      \
  --libdir=/usr/lib32     \
  --disable-static
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make DESTDIR="$pkgdir" install
rm -r "$pkgdir"/usr/{include,share}
fi
