#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

MESON_OPTS=(
    --prefix="$PREFIX"
    --buildtype=release
    --wrap-mode=nofallback
)

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    if [ "$PREFIX" = "/usr" ]; then
        MESON_OPTS+=(
            --cross-file "${HOKUTO_ARCH}"
        )
    else
        MESON_OPTS+=(--cross-file "${HOKUTO_ARCH}")
    fi
fi

meson setup build "${MESON_OPTS[@]}"

meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf build
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
meson setup build                    \
      --prefix=/usr                  \
      --libdir=/usr/lib32            \
      --buildtype=release

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
