#!/bin/sh -e

cd AppStream-$2

meson setup build       \
    --prefix=/usr       \
    --buildtype=release \
    -D apidocs=false    \
    -D docs=false       \
    -D man=false        \
    -D qt=true          \
    -D stemming=false

meson compile -C build
meson install -C build --destdir=$1
