#!/bin/sh -e

cd App*

mkdir build
cd    build

meson setup --prefix=/usr       \
            --buildtype=release \
            -D apidocs=false    \
            -D docs=false        \
            -D stemming=false ..
ninja
DESTDIR=$1 ninja install
