#!/bin/sh -e

cargo fetch --locked --target "$(rustc --print host-tuple)" --manifest-path=Cargo.toml

export CFLAGS+=' -ffat-lto-objects'
export RUSTUP_TOOLCHAIN='stable'
export CARGO_TARGET_DIR="target"
cargo build --release --frozen --manifest-path="Cargo.toml"

find "target/release" -maxdepth 1 -type f -executable -exec install -D -m755 -t "${1}/usr/bin" {} +
