#!/bin/sh -e

cargo fetch --locked
cargo build -p rqbit --frozen --release
install -d $1/usr/bin
install -Dm 755 target/release/rqbit $1/usr/bin

# install completions
install -d "${1}/usr/share/bash-completion/completions" \
           "${1}/usr/share/zsh/site-functions" \
           "${1}/usr/share/fish/vendor_completions.d"
RUST_LOG=off "${1}/usr/bin/rqbit" completions bash > "${1}/usr/share/bash-completion/completions/rqbit"
RUST_LOG=off "${1}/usr/bin/rqbit" completions zsh > "${1}/usr/share/zsh/site-functions/_rqbit"
RUST_LOG=off "${1}/usr/bin/rqbit" completions fish > "${1}/usr/share/fish/vendor_completions.d/rqbit.fish"

