#!/bin/sh -e

meson setup build       \
    --prefix=/usr       \
    --buildtype=release \
    -D gconv=disabled   \
    -D doxygen-doc=disabled

meson compile -C build
meson install -C build --destdir=$1
