#!/bin/bash -e

# gcc + glib + glibc fix
patch -Np2 -i 779.patch
patch -Np2 -i 783.patch

./configure --prefix=/usr \
  --sbindir=/usr/bin      \
  --sysconfdir=/etc       \
  --disable-vgauth        \
  --without-gtk4

make
make DESTDIR="$1" install

# install systemd files
install -D -m0644 vmtoolsd.service "$1"/usr/lib/systemd/system/vmtoolsd.service
install -D -m0644 vmware-vmblock-fuse.service "$1"/usr/lib/systemd/system/vmware-vmblock-fuse.service

# install vmware-xdg-detect-de
install -D -m0755 scripts/common/vmware-xdg-detect-de "$1"/usr/bin/vmware-xdg-detect-de
