#!/bin/sh -e

#sed -i -e 's|-Werror||g' -e 's|.*common-agent/etc/config/Makefile.*||' configure.ac
#mkdir -p common-agent/etc/config
#autoreconf -vi

./configure --prefix=/usr \
--sbindir=/usr/bin \
--without-xmlsecurity \
--without-dnet \
--without-icu \
--without-dncp

make
make DESTDIR="$1" install

# install systemd files
  install -D -m0644 vmtoolsd.service "$1"/usr/lib/systemd/system/vmtoolsd.service
  install -D -m0644 vmware-vmblock-fuse.service "$1"/usr/lib/systemd/system/vmware-vmblock-fuse.service
