#!/bin/sh -e

mkdir build
cd    build

../configure --prefix=/usr           \
             --localstatedir=/var    \
             --sysconfdir=/etc

make
make DESTDIR="$1" install

rm -rf $1/usr/share/info
