#!/bin/sh -e

./configure --prefix=/usr \
            --sbindir=/usr/bin \
            --libexecdir=/usr/lib/gnupg \
            --enable-symcryptrun \
            --enable-gpg-is-gpg2 \
            --disable-nls

sed -e '/ks_ldap_free_state/i #if USE_LDAP' \
    -e '/ks_get_state =/a #endif'           \
    -i dirmngr/server.c

make
make DESTDIR="$1" install

ln -s /usr/bin/gpg2 "$1/usr/bin/gpg"
ln -s /usr/bin/gpgv2 "$1/usr/bin/gpgv"
