#!/bin/sh -e

if hokuto check sane; then
    sane_opt=enabled
else
    sane_opt=disabled
fi

meson setup build           \
  --prefix=/usr             \
  --buildtype=release       \
  -D daemon_user=colord     \
  -D vapi=true              \
  -D systemd=true           \
  -D libcolordcompat=true   \
  -D argyllcms_sensor=false \
  -D bash_completion=false  \
  -D docs=false             \
  -D sane=$sane_opt         \
  -D man=false

meson compile -C build
meson install -C build --destdir=$1
