#!/bin/sh -e

meson setup build --prefix=/usr \
    --buildtype=release         \
    --wrap-mode=nodownload      \
    -D gtk_doc=false            \
    -D user_doc=false

meson compile -C build
meson install -C build --destdir=$1
