#!/bin/sh -e

cmake -B build                     \
  -D CMAKE_INSTALL_PREFIX=/usr     \
  -D CMAKE_BUILD_TYPE=Release      \
  -D ICAL_BUILD_DOCS=false         \
  -D GOBJECT_INTROSPECTION=true    \
  -D LIBICAL_JAVA_BINDINGS=False   \
  -D LIBICAL_GLIB_BUILD_DOCS=False \
  -D ICAL_GLIB_VAPI=true

cmake --build build
DESTDIR=$1 cmake --install build
