#!/bin/sh -e

cmake -B build \
  -D CMAKE_INSTALL_PREFIX=/usr  \
  -D CMAKE_BUILD_TYPE=Release   \
  -D SHARED_ONLY=yes            \
  -D ICAL_BUILD_DOCS=false      \
  -D GOBJECT_INTROSPECTION=true \
  -D ICAL_GLIB_VAPI=true

cmake --build build
DESTDIR=$1 cmake --install build
