#!/bin/bash -e

meson setup build               \
            --prefix=/usr       \
            --buildtype=release

meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf build
meson setup build                    \
            --prefix=/usr            \
            --cross-file=lib32       \
            --buildtype=release

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
