#!/bin/bash -e

meson setup build               \
      --prefix=/usr             \
      --buildtype=release       \
      -D documentation=disabled

meson compile -C build
meson install -C build --destdir=$1
