#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-fontrootdir=/usr/share/fonts/X11

make
make DESTDIR="$1" install

#32bit

make distclean
CC="gcc -m32" CXX="g++ -m32" PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr \
     --with-fontrootdir=/usr/share/fonts/X11 \
     --libdir=/usr/lib32

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
