#!/bin/sh -e

cmake -D CMAKE_BUILD_TYPE='None'        \
      -D CMAKE_INSTALL_PREFIX=/usr      \
      -D CMAKE_INSTALL_LIBEXECDIR='lib' \
      -D MOLD_LTO=ON                    \
      -B build

cmake --build build
DESTDIR=$1 cmake --install build

