#!/bin/sh -e

cd llvm

grep -rl '#!.*python' | xargs sed -i '1s/python$/python3/'
sed 's/utility/tool/' -i utils/FileCheck/CMakeLists.txt

mkdir build
cd build

CC=gcc CXX=g++                               \
cmake -D CMAKE_INSTALL_PREFIX=/usr           \
      -D CMAKE_SKIP_INSTALL_RPATH=ON         \
      -D LLVM_ENABLE_FFI=ON                  \
      -D CMAKE_BUILD_TYPE=Release            \
      -D LLVM_BUILD_LLVM_DYLIB=ON            \
      -D LLVM_LINK_LLVM_DYLIB=ON             \
      -D LLVM_ENABLE_RTTI=ON                 \
      -D LLVM_TARGETS_TO_BUILD="BPF;X86;host;AMDGPU;NVPTX" \
      -D LLVM_BINUTILS_INCDIR=/usr/include   \
      -D LLVM_INCLUDE_BENCHMARKS=OFF         \
      -D CLANG_DEFAULT_PIE_ON_LINUX=ON       \
      -D CLANG_CONFIG_FILE_SYSTEM_DIR=/etc/clang \
      -W no-dev -G Ninja ..

ninja
DESTDIR=$1 ninja install

mkdir -pv $1/etc/clang
for i in clang clang++; do
  echo -fstack-protector-strong > $1/etc/clang/$i.cfg
done

#32bit

rm -rf *
CC=gcc CXX=g++                                          \
cmake -D CMAKE_INSTALL_PREFIX=/usr                      \
      -D CMAKE_C_FLAGS:STRING=-m32                      \
      -D CMAKE_SKIP_INSTALL_RPATH=ON                    \
      -D CMAKE_CXX_FLAGS:STRING=-m32                    \
      -D LLVM_TARGET_ARCH:STRING=i686                   \
      -D LLVM_LIBDIR_SUFFIX=32                          \
      -D LLVM_ENABLE_FFI=ON                             \
      -D CMAKE_BUILD_TYPE=Release                       \
      -D LLVM_BUILD_LLVM_DYLIB=ON                       \
      -D LLVM_LINK_LLVM_DYLIB=ON                        \
      -D LLVM_ENABLE_RTTI=ON                            \
      -D LLVM_DEFAULT_TARGET_TRIPLE="i686-pc-linux-gnu" \
      -D LLVM_TARGETS_TO_BUILD="BPF;X86;host;AMDGPU;NVPTX"  \
      -D LLVM_HOST_TRIPLE="x86_64-pc-linux-gnu"         \
      -D LLVM_BINUTILS_INCDIR=/usr/include              \
      -D LLVM_INCLUDE_BENCHMARKS=OFF                    \
      -D CLANG_DEFAULT_PIE_ON_LINUX=ON                  \
      -D CLANG_CONFIG_FILE_SYSTEM_DIR=/etc/clang        \
      -W no-dev -G Ninja ..

ninja
DESTDIR=$PWD/DESTDIR ninja install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
