#!/bin/sh -e

PREFIX="${CROSS_PREFIX:-/usr}"

MESON_OPTS=(
    --prefix="$PREFIX"
    --buildtype=release
    --wrap-mode=nofallback
)

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    MESON_OPTS+=(--cross-file "$HOKUTO_ARCH")
fi

meson setup build "${MESON_OPTS[@]}"

meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
PKG_CONFIG_PATH="/usr/lib32/pkgconfig" \
CC="gcc -m32 -march=i686"              \
CXX="g++ -m32 -march=i686"             \
meson setup build          \
    --prefix=/usr          \
    --libdir=/usr/lib32    \
    --buildtype=release    \
    --wrap-mode=nofallback

meson compile -C build
meson install -C build --destdir=$(pwd)/destdir
install -d $1/usr/lib32/pkgconfig
cp -av $(pwd)/destdir/usr/lib32/libdbus-1.so* $1/usr/lib32/
cp -av $(pwd)/destdir/usr/lib32/dbus-1.0 $1/usr/lib32/
cp -v  $(pwd)/destdir/usr/lib32/pkgconfig/dbus-1.pc $1/usr/lib32/pkgconfig/
fi
