#!/bin/sh -e

./configure --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-doxygen-docs \
    --disable-xml-docs \
    --disable-static \
    --with-system-socket=/run/dbus/system_bus_socket \
    --enable-user-session

make
make DESTDIR="$1" install

mkdir -pv "$1/etc/dbus-1/"

install -m644 session-local.conf "$1/etc/dbus-1/"
