#!/bin/bash -e

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
# Cross-compilation configuration
PREFIX="${CROSS_PREFIX:-/usr}"
fi
# Map architecture names for CMake
CMAKE_ARCH="$HOKUTO_ARCH"
CMAKE_OPTS="-D CMAKE_SYSTEM_NAME=Linux \
            -D CMAKE_SYSTEM_PROCESSOR=$CMAKE_ARCH"

cmake -B build \
    -D CMAKE_INSTALL_PREFIX="${PREFIX:-/usr}" \
    -D CMAKE_INSTALL_LIBDIR=/usr/lib \
    -D CMAKE_SHARED_LIBS=True \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_AR=$(which gcc-ar) \
    -D CMAKE_RANLIB=$(which gcc-ranlib) \
    -D CMAKE_NM=$(which gcc-nm) \
    -D WITH_JPEG8=ON \
    $CMAKE_OPTS

cmake --build   build
DESTDIR=$1 cmake --install build

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
rm -rf build
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
cmake_options=(
    -B build
    -D CMAKE_INSTALL_PREFIX=/usr
    -D CMAKE_INSTALL_LIBDIR=/usr/lib32
    -D CMAKE_BUILD_TYPE=None
    -D ENABLE_STATIC=OFF
    -D WITH_JAVA=OFF
    -D WITH_JPEG8=ON
    -G Ninja
    -W no-dev
)
export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"
cmake "${cmake_options[@]}"
cmake --build build
DESTDIR="$pkgdir" cmake --install build
# remove everything that is provided by libjpeg-turbo
rm -r "$pkgdir"/usr/{include,share,bin}
fi
