#!/bin/sh -e

sed -i '/"lib64"/s/64//' kde-modules/KDEInstallDirsCommon.cmake

sed -e '/PACKAGE_INIT/i set(SAVE_PACKAGE_PREFIX_DIR "${PACKAGE_PREFIX_DIR}")' \
    -e '/^include/a set(PACKAGE_PREFIX_DIR "${SAVE_PACKAGE_PREFIX_DIR}")' \
    -i ECMConfig.cmake.in

cmake -B build -G ninja        \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D BUILD_WITH_QT6=ON

cmake --build build
DESTDIR=$1 cmake --install build
