#!/bin/sh -e

sed '/BUILD_STATIC =/d' -i Makefile

make CFLAGS="${CFLAGS} -I." LDFLAGS="${LDFLAGS}"
make \
		INSTALL_DIR="$1/usr/bin" \
		INSTALL_LIB="$1/usr/lib" \
		INSTALL_INC="$1/usr/include" \
		INSTALL_MAN="$1/usr/share/man" \
		install
