#!/bin/bash -e

_pkg=NVIDIA-Linux-${HOKUTO_ARCH}-${2}

create_links() {
# create soname links
find "$pkgdir" -type f -name '*.so*' ! -path '*xorg/*' -print0 | while read -d $'\0' _lib; do
    _soname=$(dirname "${_lib}")/$(readelf -d "${_lib}" | grep -Po 'SONAME.*: \[\K[^]]*' || true)
    _base=$(echo ${_soname} | sed -r 's/(.*)\.so.*/\1.so/')
    [[ -e "${_soname}" ]] || ln -s $(basename "${_lib}") "${_soname}"
    [[ -e "${_base}" ]] || ln -s $(basename "${_soname}") "${_base}"
done
}

sh ${_pkg}.run --extract-only
cd ${_pkg}
tar xvf nvidia-persistenced-init.tar.bz2

# opencl-nvidia split package
pkgdir="$HOKUTO_SPLIT_DIR/opencl-nvidia"
install -d "${pkgdir}"
install -Dm644 nvidia.icd "${pkgdir}/etc/OpenCL/vendors/nvidia.icd"
install -Dm755 "libnvidia-opencl.so.${2}" "${pkgdir}/usr/lib/libnvidia-opencl.so.${2}"
create_links

# nvidia-utils split package
pkgdir="$HOKUTO_SPLIT_DIR/nvidia-utils"
# X driver
install -Dm755 nvidia_drv.so "${pkgdir}/usr/lib/xorg/modules/drivers/nvidia_drv.so"

# Wayland/GBM
mkdir -p "${pkgdir}/usr/lib/gbm"
ln -sr "${pkgdir}/usr/lib/libnvidia-allocator.so.${2}" "${pkgdir}/usr/lib/gbm/nvidia-drm_gbm.so"

# firmware
install -Dm644 -t "${pkgdir}/usr/lib/firmware/nvidia/${2}/" firmware/*.bin

# GLX extension module for X
install -Dm755 "libglxserver_nvidia.so.${2}" "${pkgdir}/usr/lib/nvidia/xorg/libglxserver_nvidia.so.${2}"
# Ensure that X finds glx
ln -s "libglxserver_nvidia.so.${2}" "${pkgdir}/usr/lib/nvidia/xorg/libglxserver_nvidia.so.1"
ln -s "libglxserver_nvidia.so.${2}" "${pkgdir}/usr/lib/nvidia/xorg/libglxserver_nvidia.so"

install -Dm755 "libGLX_nvidia.so.${2}" "${pkgdir}/usr/lib/libGLX_nvidia.so.${2}"

# OpenGL libraries
install -Dm755 "libEGL_nvidia.so.${2}" "${pkgdir}/usr/lib/libEGL_nvidia.so.${2}"
install -Dm755 "libGLESv1_CM_nvidia.so.${2}" "${pkgdir}/usr/lib/libGLESv1_CM_nvidia.so.${2}"
install -Dm755 "libGLESv2_nvidia.so.${2}" "${pkgdir}/usr/lib/libGLESv2_nvidia.so.${2}"
install -Dm644 "10_nvidia.json" "${pkgdir}/usr/share/glvnd/egl_vendor.d/10_nvidia.json"

# OpenGL core library
install -Dm755 "libnvidia-glcore.so.${2}" "${pkgdir}/usr/lib/libnvidia-glcore.so.${2}"
install -Dm755 "libnvidia-eglcore.so.${2}" "${pkgdir}/usr/lib/libnvidia-eglcore.so.${2}"
install -Dm755 "libnvidia-glsi.so.${2}" "${pkgdir}/usr/lib/libnvidia-glsi.so.${2}"

# misc
install -Dm755 "libnvidia-api.so.1" "${pkgdir}/usr/lib/libnvidia-api.so.1"
install -Dm755 "libnvidia-fbc.so.${2}" "${pkgdir}/usr/lib/libnvidia-fbc.so.${2}"
install -Dm755 "libnvidia-encode.so.${2}" "${pkgdir}/usr/lib/libnvidia-encode.so.${2}"
install -Dm755 "libnvidia-cfg.so.${2}" "${pkgdir}/usr/lib/libnvidia-cfg.so.${2}"
install -Dm755 "libnvidia-ml.so.${2}" "${pkgdir}/usr/lib/libnvidia-ml.so.${2}"
install -Dm755 "libnvidia-glvkspirv.so.${2}" "${pkgdir}/usr/lib/libnvidia-glvkspirv.so.${2}"
install -Dm755 "libnvidia-allocator.so.${2}" "${pkgdir}/usr/lib/libnvidia-allocator.so.${2}"
install -Dm755 "libnvidia-gpucomp.so.${2}" "${pkgdir}/usr/lib/libnvidia-gpucomp.so.${2}"

# Vulkan ICD
install -Dm644 "nvidia_icd.json" "${pkgdir}/usr/share/vulkan/icd.d/nvidia_icd.json"
install -Dm644 "nvidia_layers.json" "${pkgdir}/usr/share/vulkan/implicit_layer.d/nvidia_layers.json"

if [[ $HOKUTO_ARCH = x86_64 ]]; then
# VulkanSC
install -D -m755 nvidia-pcc -t "${pkgdir}/usr/bin"
install -D -m755 "libnvidia-vksc-core.so.${2}" -t "${pkgdir}/usr/lib"
install -D -m644 nvidia_icd_vksc.json -t "${pkgdir}/usr/share/vulkansc/icd.d"
fi

# VDPAU
install -Dm755 "libvdpau_nvidia.so.${2}" "${pkgdir}/usr/lib/vdpau/libvdpau_nvidia.so.${2}"

# nvidia-tls library
install -Dm755 "libnvidia-tls.so.${2}" "${pkgdir}/usr/lib/libnvidia-tls.so.${2}"

# CUDA
install -Dm755 "libcuda.so.${2}" "${pkgdir}/usr/lib/libcuda.so.${2}"
install -Dm755 "libnvcuvid.so.${2}" "${pkgdir}/usr/lib/libnvcuvid.so.${2}"
install -Dm755 "libcudadebugger.so.${2}" "${pkgdir}/usr/lib/libcudadebugger.so.${2}"

# NVVM Compiler library loaded by the CUDA driver to do JIT link-time-optimization
install -Dm644 "libnvidia-nvvm.so.${2}" "${pkgdir}/usr/lib/libnvidia-nvvm.so.${2}"
install -Dm755 "libnvidia-nvvm70.so.4" "${pkgdir}/usr/lib/libnvidia-nvvm70.so.4"

# PTX JIT Compiler (Parallel Thread Execution (PTX) is a pseudo-assembly language for CUDA)
install -Dm755 "libnvidia-ptxjitcompiler.so.${2}" "${pkgdir}/usr/lib/libnvidia-ptxjitcompiler.so.${2}"

# raytracing
install -Dm755 "nvoptix.bin" "${pkgdir}/usr/share/nvidia/nvoptix.bin"
install -Dm755 "libnvoptix.so.${2}" "${pkgdir}/usr/lib/libnvoptix.so.${2}"
install -Dm755 "libnvidia-rtcore.so.${2}" "${pkgdir}/usr/lib/libnvidia-rtcore.so.${2}"

# NGX
install -Dm755 nvidia-ngx-updater "${pkgdir}/usr/bin/nvidia-ngx-updater"
install -Dm755 "libnvidia-ngx.so.${2}" "${pkgdir}/usr/lib/libnvidia-ngx.so.${2}"
if [[ $HOKUTO_ARCH = x86_64 ]]; then
install -Dm755 _nvngx.dll "${pkgdir}/usr/lib/nvidia/wine/_nvngx.dll"
install -Dm755 nvngx.dll "${pkgdir}/usr/lib/nvidia/wine/nvngx.dll"
install -Dm755 nvngx_dlssg.dll "${pkgdir}/usr/lib/nvidia/wine/nvngx_dlssg.dll"
fi

# Optical flow
install -Dm755 "libnvidia-opticalflow.so.${2}" "${pkgdir}/usr/lib/libnvidia-opticalflow.so.${2}"

if [[ $HOKUTO_ARCH = x86_64 ]]; then
# Cryptography library wrapper
install -Dm755 "libnvidia-pkcs11.so.${2}" "${pkgdir}/usr/lib/libnvidia-pkcs11.so.${2}"
install -Dm755 "libnvidia-pkcs11-openssl3.so.${2}" "${pkgdir}/usr/lib/libnvidia-pkcs11-openssl3.so.${2}"
fi

# Sandboxhelper
install -Dm755 "libnvidia-sandboxutils.so.${2}" "${pkgdir}/usr/lib/libnvidia-sandboxutils.so.${2}"

# Present Helper
install -Dm755 "libnvidia-present.so.${2}" "${pkgdir}/usr/lib/libnvidia-present.so.${2}"

# https://github.com/microsoft/TileIR
install -Dm755 "libnvidia-tileiras.so.${2}" "${pkgdir}/usr/lib/libnvidia-tileiras.so.${2}"

# Debug
install -Dm755 nvidia-debugdump "${pkgdir}/usr/bin/nvidia-debugdump"

# nvidia-xconfig
install -Dm755 nvidia-xconfig "${pkgdir}/usr/bin/nvidia-xconfig"
install -Dm644 nvidia-xconfig.1.gz "${pkgdir}/usr/share/man/man1/nvidia-xconfig.1.gz"

# nvidia-bug-report
install -Dm755 nvidia-bug-report.sh "${pkgdir}/usr/bin/nvidia-bug-report.sh"

# nvidia-smi
install -Dm755 nvidia-smi "${pkgdir}/usr/bin/nvidia-smi"
install -Dm644 nvidia-smi.1.gz "${pkgdir}/usr/share/man/man1/nvidia-smi.1.gz"

# nvidia-cuda-mps
install -Dm755 nvidia-cuda-mps-server "${pkgdir}/usr/bin/nvidia-cuda-mps-server"
install -Dm755 nvidia-cuda-mps-control "${pkgdir}/usr/bin/nvidia-cuda-mps-control"
install -Dm644 nvidia-cuda-mps-control.1.gz "${pkgdir}/usr/share/man/man1/nvidia-cuda-mps-control.1.gz"

# nvidia-modprobe
# This should be removed if nvidia fixed their uvm module!
install -Dm4755 nvidia-modprobe "${pkgdir}/usr/bin/nvidia-modprobe"
install -Dm644 nvidia-modprobe.1.gz "${pkgdir}/usr/share/man/man1/nvidia-modprobe.1.gz"

# nvidia-persistenced
install -Dm755 nvidia-persistenced "${pkgdir}/usr/bin/nvidia-persistenced"
install -Dm644 nvidia-persistenced.1.gz "${pkgdir}/usr/share/man/man1/nvidia-persistenced.1.gz"
install -Dm644 nvidia-persistenced-init/systemd/nvidia-persistenced.service.template "${pkgdir}/usr/lib/systemd/system/nvidia-persistenced.service"
sed -i 's/__USER__/nvidia-persistenced/' "${pkgdir}/usr/lib/systemd/system/nvidia-persistenced.service"

# application profiles
install -Dm644 "nvidia-application-profiles-${2}-rc" "${pkgdir}/usr/share/nvidia/nvidia-application-profiles-${2}-rc"
install -Dm644 "nvidia-application-profiles-${2}-key-documentation" "${pkgdir}/usr/share/nvidia/nvidia-application-profiles-${2}-key-documentation"

# new power management support
install -Dm644 systemd/system/*.service -t "${pkgdir}/usr/lib/systemd/system"
install -Dm755 systemd/system-sleep/nvidia "${pkgdir}/usr/lib/systemd/system-sleep/nvidia"
install -Dm755 systemd/nvidia-sleep.sh "${pkgdir}/usr/bin/nvidia-sleep.sh"
install -Dm755 nvidia-powerd "${pkgdir}/usr/bin/nvidia-powerd"
install -Dm644 dlsnetparams.csv "${pkgdir}/usr/share/nvidia/nvidia-powerd/dlsnetparams.csv"
install -Dm644 nvidia-dbus.conf "${pkgdir}/usr/share/dbus-1/system.d/nvidia-dbus.conf"
install -Dm644 "../systemd-suspend-override.conf" "${pkgdir}/usr/lib/systemd/system/systemd-suspend.service.d/10-nvidia-no-freeze-session.conf"
install -Dm644 "../systemd-suspend-override.conf" "${pkgdir}/usr/lib/systemd/system/systemd-suspend-then-hibernate.service.d/10-nvidia-no-freeze-session.conf"
install -Dm644 "../systemd-suspend-override.conf" "${pkgdir}/usr/lib/systemd/system/systemd-hibernate.service.d/10-nvidia-no-freeze-session.conf"
install -Dm644 "../systemd-suspend-override.conf" "${pkgdir}/usr/lib/systemd/system/systemd-hybrid-sleep.service.d/10-nvidia-no-freeze-session.conf"

# distro specific files must be installed in /usr/share/X11/xorg.conf.d
install -Dm644 "../nvidia-drm-outputclass.conf" "${pkgdir}/usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf"

install -Dm644 "../nvidia-utils.sysusers" "${pkgdir}/usr/lib/sysusers.d/$pkgname.conf"

install -Dm644 "../nvidia.rules" "$pkgdir"/usr/lib/udev/rules.d/60-nvidia.rules

# Blacklist nouveau and nova
install -Dm644 /dev/stdin "${pkgdir}/usr/lib/modprobe.d/${pkgname}.conf" <<END
blacklist nouveau
blacklist nova_core
blacklist nova_drm
END
echo "nvidia-uvm" | install -Dm644 /dev/stdin "${pkgdir}/usr/lib/modules-load.d/${pkgname}.conf"

# Enable kernel suspend notifiers for open modules and override TemporaryFilePath
# from default /tmp to /var/tmp
install -Dm644 "../nvidia-sleep.conf" "${pkgdir}/usr/lib/modprobe.d/nvidia-sleep.conf"

# Lists NVIDIA driver files for container runtimes like nvidia-container-toolkit
install -Dm644 sandboxutils-filelist.json "${pkgdir}/usr/share/nvidia/files.d/sandboxutils-filelist.json"

create_links

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit
create_links() {
    # create soname links
    for _lib in $(find "${pkgdir}" -name '*.so*' | grep -v 'xorg/'); do
        _soname=$(dirname "${_lib}")/$(readelf -d "${_lib}" | grep -Po 'SONAME.*: \[\K[^]]*' || true)
        _base=$(echo ${_soname} | sed -r 's/(.*).so.*/\1.so/')
        [[ -e "${_soname}" ]] || ln -s $(basename "${_lib}") "${_soname}"
        [[ -e "${_base}" ]] || ln -s $(basename "${_soname}") "${_base}"
    done
}
cd 32
# lib32-opencl-nvidia
pkgdir="$HOKUTO_SPLIT_DIR/lib32-opencl-nvidia"
install -d "${pkgdir}"
install -D -m755 "libnvidia-opencl.so.${2}" "${pkgdir}/usr/lib32/libnvidia-opencl.so.${2}"

create_links

# lib32-nvidia-utils
pkgdir="$HOKUTO_SPLIT_DIR/lib32-nvidia-utils"
install -d "${pkgdir}"
install -D -m755 "libGLX_nvidia.so.${2}" "${pkgdir}/usr/lib32/libGLX_nvidia.so.${2}"

# OpenGL libraries
install -D -m755 "libEGL_nvidia.so.${2}" "${pkgdir}/usr/lib32/libEGL_nvidia.so.${2}"
install -D -m755 "libGLESv1_CM_nvidia.so.${2}" "${pkgdir}/usr/lib32/libGLESv1_CM_nvidia.so.${2}"
install -D -m755 "libGLESv2_nvidia.so.${2}" "${pkgdir}/usr/lib32/libGLESv2_nvidia.so.${2}"

# OpenGL core library
install -D -m755 "libnvidia-glcore.so.${2}" "${pkgdir}/usr/lib32/libnvidia-glcore.so.${2}"
install -D -m755 "libnvidia-eglcore.so.${2}" "${pkgdir}/usr/lib32/libnvidia-eglcore.so.${2}"
install -D -m755 "libnvidia-glsi.so.${2}" "${pkgdir}/usr/lib32/libnvidia-glsi.so.${2}"

# misc
mkdir -p "${pkgdir}/usr/lib32/gbm" && ln -sr "${pkgdir}/usr/lib32/libnvidia-allocator.so.${2}" "${pkgdir}/usr/lib32/gbm/nvidia-drm_gbm.so"
install -D -m755 "libnvidia-fbc.so.${2}" "${pkgdir}/usr/lib32/libnvidia-fbc.so.${2}"
install -D -m755 "libnvidia-encode.so.${2}" "${pkgdir}/usr/lib32/libnvidia-encode.so.${2}"
install -D -m755 "libnvidia-ml.so.${2}" "${pkgdir}/usr/lib32/libnvidia-ml.so.${2}"
install -D -m755 "libnvidia-glvkspirv.so.${2}" "${pkgdir}/usr/lib32/libnvidia-glvkspirv.so.${2}"
install -D -m755 "libnvidia-allocator.so.${2}" "${pkgdir}/usr/lib32/libnvidia-allocator.so.${2}"
install -D -m755 "libnvidia-gpucomp.so.${2}" "${pkgdir}/usr/lib32/libnvidia-gpucomp.so.${2}"
install -D -m755 "libnvidia-tileiras.so.${2}" "${pkgdir}/usr/lib32/libnvidia-tileiras.so.${2}"

# VDPAU
install -D -m755 "libvdpau_nvidia.so.${2}" "${pkgdir}/usr/lib32/vdpau/libvdpau_nvidia.so.${2}"

# nvidia-tls library
install -D -m755 "libnvidia-tls.so.${2}" "${pkgdir}/usr/lib32/libnvidia-tls.so.${2}"

# CUDA
install -D -m755 "libcuda.so.${2}" "${pkgdir}/usr/lib32/libcuda.so.${2}"
install -D -m755 "libnvcuvid.so.${2}" "${pkgdir}/usr/lib32/libnvcuvid.so.${2}"

# NVVM Compiler library loaded by the CUDA driver to do JIT link-time-optimization
install -D -m644 "libnvidia-nvvm.so.${2}" "${pkgdir}/usr/lib32/libnvidia-nvvm.so.${2}"

# PTX JIT Compiler (Parallel Thread Execution (PTX) is a pseudo-assembly language for CUDA)
install -D -m755 "libnvidia-ptxjitcompiler.so.${2}" "${pkgdir}/usr/lib32/libnvidia-ptxjitcompiler.so.${2}"

# Optical flow
install -D -m755 "libnvidia-opticalflow.so.${2}" "${pkgdir}/usr/lib32/libnvidia-opticalflow.so.${2}"

create_links

rm -rf "${pkgdir}"/usr/{include,share,bin}
fi
