#!/bin/bash -e

./configure --prefix=/usr \
  --disable-static        \
  --with-ui               \
  --with-readline

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool

make
make DESTDIR="${1}" install

# add generic hunspell.so for development and projects not using pkgconfig flags - FS#30592
pushd "${1}"/usr/lib
ln -s libhunspell-?.?.so libhunspell.so
popd
