#!/bin/bash -e

hokuto-meson build             \
    --sysconfdir=/etc          \
    --mandir=/usr/share/man    \
    --localstatedir=/var       \
    --optimization 2           \
    -D platforms=x11,wayland   \
    -D egl=enabled             \
    -D valgrind=disabled       \
    -D libunwind=disabled      \
    -D glvnd=enabled           \
    -D vulkan-drivers="amd,swrast,virtio,broadcom" \
    -D vulkan-layers=device-select,intel-nullhw,overlay,screenshot,anti-lag,vram-report-limit \
    -D vulkan-manifest-per-architecture=false \
    -D gallium-drivers="llvmpipe,radeonsi,softpipe,svga,v3d,vc4,virgl,zink"  \
    -D gallium-extra-hud=true  \
    -D gallium-mediafoundation=disabled \
    -D intel-rt=enabled        \
    -D intel-virtio-experimental=true \
    -D gles1=disabled          \
    -D video-codecs=all

meson compile -C build
meson install -C build --destdir=$1

libdir=usr/lib

_pick "$1" vulkan-broadcom $libdir/libvulkan_broadcom.so
_pick "$1" vulkan-broadcom usr/share/vulkan/icd.d/broadcom_icd.json

_pick "$1" vulkan-radeon $libdir/libvulkan_radeon.so
_pick "$1" vulkan-radeon usr/share/drirc.d/00-radv-defaults.conf
_pick "$1" vulkan-radeon usr/share/vulkan/icd.d/radeon_icd.json

_pick "$1" vulkan-swrast $libdir/libvulkan_lvp.so
_pick "$1" vulkan-swrast usr/share/vulkan/icd.d/lvp_icd.json

_pick "$1" vulkan-virtio $libdir/libvulkan_virtio.so
_pick "$1" vulkan-virtio usr/share/vulkan/icd.d/virtio_icd.json

_pick "$1" vulkan-mesa-implicit-layers $libdir/libVkLayer_MESA_anti_lag.so
_pick "$1" vulkan-mesa-implicit-layers $libdir/libVkLayer_MESA_device_select.so
_pick "$1" vulkan-mesa-implicit-layers usr/share/vulkan/implicit_layer.d

_pick "$1" vulkan-mesa-layers $libdir/libVkLayer_*.so
_pick "$1" vulkan-mesa-layers usr/bin/mesa-*-control.py
_pick "$1" vulkan-mesa-layers usr/share/vulkan/explicit_layer.d

# indirect rendering
pushd $1
ln -sr $libdir/libGLX_{mesa,indirect}.so.0
popd

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
rm -rf build
hokuto-meson-32 build          \
      --optimization 2         \
    -D platforms=x11,wayland   \
    -D egl=enabled             \
    -D valgrind=disabled       \
    -D libunwind=disabled      \
    -D glvnd=enabled           \
    -D vulkan-drivers="amd,swrast,virtio,broadcom" \
    -D vulkan-layers=device-select,intel-nullhw,overlay,screenshot,anti-lag,vram-report-limit \
    -D vulkan-manifest-per-architecture=false \
    -D gallium-drivers="llvmpipe,radeonsi,softpipe,svga,v3d,vc4,virgl,zink"  \
    -D gallium-extra-hud=true  \
    -D gallium-mediafoundation=disabled \
    -D intel-virtio-experimental=true \
    -D gles1=disabled          \
    -D video-codecs=all

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR

libdir=usr/lib32

_pick "$PWD/DESTDIR" lib32-vulkan-broadcom $libdir/libvulkan_broadcom.so
_pick "$PWD/DESTDIR" lib32-vulkan-broadcom usr/share/vulkan/icd.d/broadcom_icd.json

_pick "$PWD/DESTDIR" lib32-vulkan-radeon $libdir/libvulkan_radeon.so
_pick "$PWD/DESTDIR" lib32-vulkan-radeon usr/share/drirc.d/00-radv-defaults.conf
_pick "$PWD/DESTDIR" lib32-vulkan-radeon usr/share/vulkan/icd.d/radeon_icd.json

_pick "$PWD/DESTDIR" lib32-vulkan-swrast $libdir/libvulkan_lvp.so
_pick "$PWD/DESTDIR" lib32-vulkan-swrast usr/share/vulkan/icd.d/lvp_icd.json

_pick "$PWD/DESTDIR" lib32-vulkan-virtio $libdir/libvulkan_virtio.so
_pick "$PWD/DESTDIR" lib32-vulkan-virtio usr/share/vulkan/icd.d/virtio_icd.json

_pick "$PWD/DESTDIR" lib32-vulkan-mesa-implicit-layers $libdir/libVkLayer_MESA_anti_lag.so
_pick "$PWD/DESTDIR" lib32-vulkan-mesa-implicit-layers $libdir/libVkLayer_MESA_device_select.so
_pick "$PWD/DESTDIR" lib32-vulkan-mesa-implicit-layers usr/share/vulkan/implicit_layer.d

_pick "$PWD/DESTDIR" lib32-vulkan-mesa-layers $libdir/libVkLayer_*.so
_pick "$PWD/DESTDIR" lib32-vulkan-mesa-layers usr/bin/mesa-*-control.py
_pick "$PWD/DESTDIR" lib32-vulkan-mesa-layers usr/share/vulkan/explicit_layer.d

rm -rf "$PWD/DESTDIR"/usr/{include,share}
_pick "$PWD/DESTDIR" lib32-mesa '*'
fi
