#!/bin/sh -e

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=release \
    -Dplatforms=x11,wayland \
    -Degl=enabled \
    -Dvalgrind=disabled \
    -Dlibunwind=disabled \
    -Dglvnd=true \
    -Dvulkan-drivers="auto" \
    -Dgallium-drivers="auto" \
    -D gles1=disabled        \
    -Dvideo-codecs=all     \
    . output

ninja -C output
DESTDIR=$1 ninja -C output install

#32bit

rm -rf output
mkdir build
cd build
meson setup                    \
      --cross-file=lib32       \
      --prefix=/usr            \
      --libdir=/usr/lib32      \
      --buildtype=release      \
      -D platforms=x11,wayland \
      -D gallium-drivers=auto  \
      -D vulkan-drivers=auto   \
      -D gles1=disabled        \
      -D video-codecs=all      \
      -D valgrind=disabled     \
      -D libunwind=disabled    \
      ..
sed -i 's/\/usr\/lib\//\/usr\/lib32\//g' ./build.ninja
BINDGEN_EXTRA_CLANG_ARGS="-m32" ninja

DESTDIR=$PWD/DESTDIR ninja install
install -d $1/usr/{lib32,share}/
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
if [ -d DESTDIR/usr/share/vulkan ]; then
    cp -vR DESTDIR/usr/share/vulkan $1/usr/share
fi
