#!/bin/sh -e

meson setup build              \
    --prefix=/usr              \
    --sysconfdir=/etc          \
    --mandir=/usr/share/man    \
    --localstatedir=/var       \
    --buildtype=release        \
    -D platforms=x11,wayland   \
    -D egl=enabled             \
    -D valgrind=disabled       \
    -D libunwind=disabled      \
    -D glvnd=true              \
    -D vulkan-drivers="swrast" \
    -D gallium-drivers="virgl,svga,softpipe,llvmpipe"  \
    -D  gles1=disabled         \
    -D video-codecs=all

meson compile -C build
meson install -C build --destdir=$1
