#!/bin/bash -e

if [ "$HOKUTO_ARCH" = "aarch64" ]; then
install -Dm755 hokuto-arm64 "$1/usr/bin/hokuto"
else
install -Dm755 hokuto-amd64 "$1/usr/bin/hokuto"
fi

ln -s hokuto $1/usr/bin/hk
install -Dm644 hokuto.fish $1/usr/share/fish/vendor_completions.d/hokuto.fish
ln -s hokuto.fish $1/usr/share/fish/vendor_completions.d/hk.fish
install -Dm644 hokuto.bash $1/usr/share/bash-completion/completions/hokuto
ln -s hokuto $1/usr/share/bash-completion/completions/hk
install -Dm644 hokuto.zsh $1/usr/share/zsh/site-functions/_hokuto
ln -s _hokuto $1/usr/share/zsh/site-functions/_hk
install -d $1/etc/hokuto
install -Dm644 hokuto.pkgset $1/etc/hokuto/hokuto.pkgset
install -Dm644 hokuto.update $1/etc/hokuto/hokuto.update
install -Dm644 hokuto.rebuild $1/etc/hokuto/hokuto.rebuild

# hokuto-tools: the web installer and the build container script
pkgdir=$HOKUTO_SPLIT_DIR/hokuto-tools
install -Dm755 hokutostrap "$pkgdir"/usr/bin/hokutostrap
install -Dm755 hokuto-builder "$pkgdir"/usr/bin/hokuto-builder
install -Dm644 hokuto-builder.bash "$pkgdir"/usr/share/bash-completion/completions/hokuto-builder
install -Dm644 hokuto-builder.fish "$pkgdir"/usr/share/fish/vendor_completions.d/hokuto-builder.fish
install -Dm644 hokuto-builder.zsh "$pkgdir"/usr/share/zsh/site-functions/_hokuto-builder
install -Dm644 hokuto-builder.service "$pkgdir"/usr/lib/systemd/system/hokuto-builder.service
install -Dm644 hokuto-builder.timer "$pkgdir"/usr/lib/systemd/system/hokuto-builder.timer
