#!/bin/sh -e

#don't compile man pages
sed -i.bak -e '26,28d;65,68d' Makefile

make CARGOFLAGS="--target-dir=target" build
make CARGOFLAGS="--target-dir=target" DESTDIR="$1" install

install -Dm644 zram-generator.conf $1/etc/systemd/zram-generator.conf
