#!/bin/bash -e

meson subprojects download
for submodule in src/reshade subprojects/{libdisplay-info,libliftoff,openvr,vkroots,wlroots} thirdparty/SPIRV-Headers; do
git submodule init ${submodule}
git config submodule.${submodule}.url ${submodule##*/}
done
git -c protocol.file.allow=always submodule update

meson setup build --prefix=/usr \
    -D pipewire=enabled \
    -D force_fallback_for=glm,stb,libdisplay-info,libliftoff,vkroots,wlroots \
    -D enable_openvr_support=false

meson compile -C build
meson install -C build --skip-subprojects --destdir=$1
