#!/bin/sh -e

# Do not run fixincludes
sed -i 's@\./fixinc\.sh@-c true@' gcc/Makefile.in

mkdir gcc-build
cd gcc-build

../configure \
    --prefix=/usr \
    --program-prefix=aarch64-linux-gnu- \
    --with-local-prefix=/usr/aarch64-linux-gnu \
    --with-sysroot=/usr/aarch64-linux-gnu \
    --with-build-sysroot=/usr/aarch64-linux-gnu \
    --with-native-system-header-dir=/include \
    --libdir=/usr/lib \
    --libexecdir=/usr/lib \
    --target=aarch64-linux-gnu \
    --host=x86_64-unknown-linux-gnu \
    --build=x86_64-unknown-linux-gnu \
    --disable-nls \
    --enable-default-pie \
    --enable-languages=c,c++ \
    --enable-shared \
    --enable-threads=posix \
    --with-system-zlib \
    --with-isl \
    --enable-__cxa_atexit \
    --disable-libunwind-exceptions \
    --enable-clocale=gnu \
    --disable-libstdcxx-pch \
    --disable-libssp \
    --enable-gnu-unique-object \
    --enable-linker-build-id \
    --enable-lto \
    --enable-plugin \
    --enable-install-libiberty \
    --with-linker-hash-style=gnu \
    --enable-gnu-indirect-function \
    --disable-multilib \
    --disable-werror \
    --enable-checking=release

make
make DESTDIR="$1" install-gcc install-target-{libgcc,libstdc++-v3,libgomp,libquadmath,libatomic}

# Remove files that conflict with host gcc package
rm -r "$1"/usr/share/man/man7
rm -r "$1"/usr/share/info
rm -r "$1"/usr/share/gcc-$2
