#!/bin/sh -e

cd nspr
sed -i '/^RELEASE/s|^|#|' pr/src/misc/Makefile.in
sed -i 's|$(LIBRARY) ||'  config/rules.mk

./configure --prefix=/usr   \
            --with-mozilla  \
            --with-pthreads \
            --enable-64bit

make
make DESTDIR=$1 install

#32bit

make distclean
CC="gcc -m32" CXX="g++ -m32"   \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --with-mozilla           \
            --with-pthreads          \
            --disable-64bit

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
