#!/bin/sh -e

cd nspr
sed -i '/^RELEASE/s|^|#|' pr/src/misc/Makefile.in
sed -i 's|$(LIBRARY) ||'  config/rules.mk

CONF_ARGS="--prefix=$CROSS_PREFIX \
           --with-mozilla \
           --with-pthreads"

if [ "$HOKUTO_ARCH" = "x86_64" ] || [ "$HOKUTO_ARCH" = "aarch64" ]; then
    CONF_ARGS="$CONF_ARGS --enable-64bit"
else
    CONF_ARGS="$CONF_ARGS --disable-64bit"
fi

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CONF_ARGS="$CONF_ARGS --host=$HOKUTO_ARCH-linux-gnu"
fi

./configure $CONF_ARGS

make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
CC="gcc -m32" CXX="g++ -m32"   \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --with-mozilla           \
            --with-pthreads          \
            --disable-64bit

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
fi
