#!/bin/bash -e

# Build sometimes forces -Werror.
export CFLAGS="$CFLAGS -Wno-error -ffat-lto-objects"

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure --prefix="$PREFIX"           \
            --disable-debuginfod         \
            --enable-libdebuginfod=dummy \
            --sysconfdir=/etc            \
            --program-prefix="eu-"       \
           $CROSS_OPTS

make
make DESTDIR=$1 install

mkdir -p "$1$PREFIX/lib/pkgconfig"
cp -f config/libelf.pc "$1$PREFIX/lib/pkgconfig/libelf.pc"

# libelf
_pick "$1" libelf etc/debuginfod
_pick "$1" libelf etc/profile.d/*
_pick "$1" libelf usr/{include,lib}
_pick "$1" libelf usr/share/man/*/{,lib}elf*

# debuginfod
_pick "$1" debuginfod usr/bin/debuginfod*
_pick "$1" debuginfod usr/share/fish/vendor_conf.d/debuginfod.fish
_pick "$1" debuginfod usr/share/man/*/debuginfod*

if [ "$MULTILIB" = "1" ]; then
#32bit split package
make distclean
dest_dir="$HOKUTO_SPLIT_DIR/lib32-libelf"
CC="gcc -m32" CXX="g++ -m32" ./configure \
    --host=i686-pc-linux-gnu \
    --prefix=/usr            \
    --libdir=/usr/lib32      \
    --disable-debuginfod     \
    --disable-static

make
make DESTDIR=$dest_dir install
rm -rf "$dest_dir/"{etc,usr/{bin,include,share}}
fi
