CFLAGS=-march=native -mtune=native -O2 -pipe -fomit-frame-pointer
CFLAGS_ARM64=-O2 -march=armv8-a+crc -mcpu=cortex-a72 -pipe -fPIC
CFLAGS_GEN=-O2 -pipe -march=x86-64 -mtune=generic -fno-plt -fno-semantic-interposition
CFLAGS_LTO=-march=native -O2 -pipe -fomit-frame-pointer -flto=LTOJOBS
CXXFLAGS=-march=native -mtune=native -O2 -pipe -fomit-frame-pointer
CXXFLAGS_ARM64=-O2 -march=armv8-a+crc -mcpu=cortex-a72 -pipe -fPIC
CXXFLAGS_GEN=-O2 -pipe -march=x86-64 -mtune=generic -fno-plt -fno-semantic-interposition
GNU_MIRROR=https://mirror.cyberbits.asia/gnu/
HOKUTO_DEBUG=0
HOKUTO_GENERIC=0
HOKUTO_LTO=1
HOKUTO_MIRROR=https://vdrlake.xdd.ovh:7778/sauzeros
HOKUTO_MIRROR_NAME=vdrlake
HOKUTO_MULTILIB=1
HOKUTO_PATH=/repo/sauzeros/core:/repo/sauzeros/extra:/repo/kde:/repo/cosmic
HOKUTO_ROOT=/
LDFLAGS=-fuse-ld=bfd -O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
LDFLAGS_LTO=-fuse-ld=bfd -flto=LTOJOBS -O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
MIRROR_LIST=vdrlake,cloudflare-r2
MIRROR_cloudflare-r2_ACCESS_KEY=94cf44431379721a4e3b0b258f68bd97
MIRROR_cloudflare-r2_REGION=auto
MIRROR_cloudflare-r2_SECRET_KEY=4a764b0797403d5c8f66a05ac54c625ea4f854ad2e08a9185928aa7cc7aa8fa1
MIRROR_cloudflare-r2_TYPE=r2
MIRROR_cloudflare-r2_URL=https://f926227d8ec1a5564840adfa395afc9b.r2.cloudflarestorage.com
MIRROR_vdrlake_ACCESS_KEY=ACQWY1CK3C6WX5WESJJL
MIRROR_vdrlake_BUCKET=sauzeros
MIRROR_vdrlake_REGION=auto
MIRROR_vdrlake_SECRET_KEY=bMMDnAyXBAAo0QZjegME+RUxNkpu2HSVRxuODbof
MIRROR_vdrlake_TYPE=minio
MIRROR_vdrlake_URL=https://vdrlake.xdd.ovh:7778
TMPDIR=/var/tmp/hokuto
TMPDIR2=/var/tmpdir/hokuto
