#!/bin/sh -e

./configure --prefix=/usr \
    --enable-c++11 \
    --enable-release \
    --enable-all-engines

make
make install

install -vDm644 dists/scummvm.desktop -t "$1"/usr/share/applications/
