#!/bin/bash -e

CONF_ARGS="--prefix=$CROSS_PREFIX --disable-doc"

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CONF_ARGS="$CONF_ARGS --host=$HOKUTO_ARCH-linux-gnu"
fi

./configure $CONF_ARGS

make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit split package
make distclean
CC="gcc -m32" ./configure \
    --host=i686-pc-linux-gnu      \
    --prefix=/usr                 \
    --libdir=/usr/lib32           \
    --disable-static
make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
