#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-doc

make
make DESTDIR=$1 install

rm -rf $1/usr/share/info

#32bit
make distclean
CC="gcc -m32" ./configure \
    --host=i686-pc-linux-gnu      \
    --prefix=/usr                 \
    --libdir=/usr/lib32           \
    --disable-static
make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
