#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-shared \
    --enable-static \
    --enable-mini-gmp \
    --disable-documentation

make
make DESTDIR="$1" install

#32bit

make distclean
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --disable-static         \
            --disable-tests

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
