#!/bin/sh -e

mkdir build
cd build

meson setup --prefix=/usr             \
            --buildtype=release       \
           -Dbroadway-backend=true    \
           -Dmedia-gstreamer=disabled \
           -Dintrospection=enabled    \
           ..

ninja
DESTDIR=$1 ninja install
