#!/bin/bash -e

cmake_options=(
    -D CMAKE_BUILD_TYPE=None
    -D CMAKE_INSTALL_LIBDIR=lib
    -D CMAKE_INSTALL_PREFIX=/usr
    -D FREEGLUT_BUILD_STATIC_LIBS=OFF
)

cmake -B build "${cmake_options[@]}"
cmake --build build
DESTDIR="${1}" cmake --install build

ln -s glut.pc "${1}/usr/lib/pkgconfig/freeglut.pc"

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
rm -rf build
cmake_options=(
    -D CMAKE_BUILD_TYPE=None
    -D CMAKE_INSTALL_LIBDIR=lib32
    -D CMAKE_INSTALL_PREFIX=/usr
    -D FREEGLUT_BUILD_STATIC_LIBS=OFF
    -D FREEGLUT_INSTALL_MAN_PAGES=OFF
)
pkgdir="$HOKUTO_SPLIT_DIR/lib32-freeglut"
export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
cmake -B build "${cmake_options[@]}"
cmake --build build
DESTDIR="$pkgdir" cmake --install build
rm -r "$pkgdir/usr/include"
ln -s glut.pc "$pkgdir/usr/lib32/pkgconfig/freeglut.pc"
fi
