#!/bin/sh -e

patch -Np1 -i libtirpc-1.3.6-gcc15_fixes-1.patch


./configure --prefix=/usr \
    --sysconfdir=/etc \
    --disable-static \
    --disable-gssapi

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"
