#!/bin/sh -e

./configure --prefix=/usr \
    --sysconfdir=/etc \
    --disable-static \
    --disable-gssapi

make
make DESTDIR="$1" install

if [ "$MULTILIB" = "1" ]; then
#32bit
make clean
CFLAGS+=" -m32" CXXFLAGS+=" -m32" \
./configure --prefix=/usr \
    --libdir=/usr/lib32   \
    --disable-gssapi
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32/
fi
