#!/bin/sh -e

(for i in Bundles/{Alone,Alone7z,Format7zF,SFXCon} UI/Console; do
    make -C CPP/7zip/$i -f ../../cmpl_gcc.mak || exit
done)

install -vDm755 CPP/7zip/Bundles/Alone{/b/g/7za,7z/b/g/7zr} \
                CPP/7zip/Bundles/Format7zF/b/g/7z.so        \
                CPP/7zip/UI/Console/b/g/7z                  \
                -t $1/usr/lib/7zip/

install -vm755 CPP/7zip/Bundles/SFXCon/b/g/7zCon \
               $1/usr/lib/7zip/7zCon.sfx

 for _prog in 7za 7zr 7z; do
printf '#!/bin/sh\nexec /usr/lib/7zip/%s "$@"\n' "$_prog" \
| install -D /dev/stdin "$1/usr/bin/$_prog"
done

