#!/bin/bash -e

# fix gcc 16 bug
sed -i 's/-Werror/-Werror -Wno-error=array-bounds/' CPP/7zip/7zip_gcc.mak
sed -i 's/-Werror/-Werror -Wno-error=array-bounds/' CPP/Build.mak


_platform_flags=()

  case $HOKUTO_ARCH in
    x86_64)
      _platform_flags=(PLATFORM=x64 IS_X64=1 MY_ASM=uasm USE_ASM=1)
      ;;
    aarch64)
      _platform_flags=(PLATFORM=arm64 IS_ARM64=1 USE_ASM=1)
      ;;
  esac

(for i in Bundles/{Alone,Alone7z,Format7zF,SFXCon} UI/Console; do
    make -C CPP/7zip/$i -f ../../cmpl_gcc.mak "${_platform_flags[@]}" \
      LFLAGS_STRIP= \
      CC="cc $CPPFLAGS $CFLAGS $LDFLAGS" \
      CXX="g++ $CPPFLAGS $CXXFLAGS $LDFLAGS"
done)

install -vDm755 CPP/7zip/Bundles/Alone{/b/g/7za,7z/b/g/7zr} \
                CPP/7zip/Bundles/Format7zF/b/g/7z.so        \
                CPP/7zip/UI/Console/b/g/7z                  \
                -t $1/usr/lib/7zip/

install -vm755 CPP/7zip/Bundles/SFXCon/b/g/7zCon \
               $1/usr/lib/7zip/7zCon.sfx

 for _prog in 7za 7zr 7z; do
printf '#!/bin/bash\nexec /usr/lib/7zip/%s "$@"\n' "$_prog" \
| install -D /dev/stdin "$1/usr/bin/$_prog"
done
