#!/bin/sh -e

git rm -r externals/MoltenVK
git submodule update --init --recursive --depth 1

cmake -B build \
  -G Ninja     \
  -D CMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" \
  -D CMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold" \
  -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE=ON \
  -D CMAKE_C_COMPILER=clang \
  -D CMAKE_CXX_COMPILER=clang++ \
  -D ENABLE_QT_GUI=ON \
  -D CMAKE_INSTALL_PREFIX='/usr' \
  -D CMAKE_SKIP_RPATH=ON \
  -D BUILD_TESTING=OFF \
  -D SIRIT_USE_SYSTEM_SPIRV_HEADERS=ON \
  -Wno-dev

cmake --build build
DESTDIR=$1 cmake --install build
