#!/bin/sh -e

meson setup build --prefix=/usr       \
            --buildtype=release       \
           -Dbroadway-backend=true    \
           -Dmedia-gstreamer=disabled \
           -Dintrospection=enabled

meson compile -C build
meson install -C build --destdir=$1
