#!/bin/sh -e

patch -Np1 -i 983.patch

hokuto-meson build    \
  -D default-hvs=qemu \
  -D tests=disabled

meson compile -C build
meson install -C build --destdir=$1

python -m compileall "${1}"/usr/share/virt-manager
python -O -m compileall "${1}"/usr/share/virt-manager
