#!/bin/sh -e

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    case "$HOKUTO_ARCH" in
        aarch64) GOARCH=arm64 ;;
        x86_64)  GOARCH=amd64 ;;
        *)       GOARCH=$HOKUTO_ARCH ;;
    esac

    export CGO_ENABLED=0
    unset GOBIN
    # Patch build.go to not set GOBIN, which breaks cross-compilation install
    sed -i 's|os.Setenv("GOBIN"|// os.Setenv("GOBIN"|' build.go
    go run build.go -goos linux -goarch "$GOARCH" -no-upgrade build
    mkdir -p bin
    mv syncthing bin/
else
    go run build.go -no-upgrade install
fi
install -Dm755 bin/syncthing "$1/usr/bin/syncthing"

cd etc/linux-systemd

mkdir -pv "$1/usr/lib/systemd/system"
mkdir -pv "$1/usr/lib/systemd/user"

cp -a system/* "$1/usr/lib/systemd/system"
cp -a user/* "$1/usr/lib/systemd/user"
