#!/bin/sh -e

cd rpcs3
COMM_TAG="$(grep 'version{.*}' rpcs3/rpcs3_version.cpp | awk -F[{,] '{printf "%d.%d.%d", $2, $3, $4}')"
COMM_COUNT="$(git rev-list --count HEAD)"
COMM_HASH="$(git rev-parse --short HEAD)"
echo "${COMM_TAG}.r${COMM_COUNT}.${COMM_HASH}"

git submodule init 3rdparty/glslang/glslang
git config submodule.3rdparty/glslang.url ../glslang

SUBMODULES=($(git config --file .gitmodules --get-regexp path | \
  awk '!/libpng/ && !/zlib/ && !/curl/ && !/llvm/ && !/glslang/ && !/pugixml/ && !/SDL/ && !/flatbuffers/ '))

# We need to convert from a relative folder path to a https://github.com path
for ((i=0;i<${#SUBMODULES[@]};i+=2))
 do
  pathid=${SUBMODULES[$i]}
  path=${SUBMODULES[$i+1]}

  git submodule init $path
  urlid=${pathid/%.path/.url}

# This gets the last two paths in the url, ie RPCS3/rpcs3.git
  url=$(git config $urlid | awk -F/ '{print $(NF-1)"/"$(NF-0)}')

  git config $urlid https://github.com/$url
  git -c protocol.file.allow=always submodule update --init --filter=tree:0 $path
done

  git -c protocol.file.allow=always submodule update 3rdparty/glslang/glslang

cd ..

# GLIBCXX_ASSERTIONS is know to cause unwanted assertions and crash rpcs3
BAD_FLAG="-Wp,-D_GLIBCXX_ASSERTIONS"
CXXFLAGS="${CXXFLAGS//$BAD_FLAG/}"

CC=clang CXX=clang++ cmake -S rpcs3 -B build \
    -D CMAKE_BUILD_TYPE=Release              \
    -D CMAKE_INSTALL_PREFIX=/usr             \
    -D CMAKE_SKIP_RPATH=ON                   \
    -D USE_NATIVE_INSTRUCTIONS=OFF           \
    -D USE_SYSTEM_FFMPEG=ON                  \
    -D USE_SYSTEM_LIBPNG=ON                  \
    -D USE_SYSTEM_ZLIB=ON                    \
    -D USE_SYSTEM_CURL=ON                    \
    -D USE_SYSTEM_FLATBUFFERS=ON             \
    -D USE_SYSTEM_PUGIXML=ON                 \
    -D USE_SYSTEM_OPENCV=ON                  \
    -D USE_SDL=ON                            \
    -D USE_SYSTEM_SDL=ON                     \
    -D BUILD_LLVM=OFF                        \
    -D USE_SYSTEM_WOLFSSL=OFF                \
    -D CMAKE_LINKER=lld                      \
    -D CMAKE_SHARED_LINKER_FLAGS="$LDFLAGS -fuse-ld=lld" \
    -D CMAKE_EXE_LINKER_FLAGS="$LDFLAGS -fuse-ld=lld"

cmake --build build
DESTDIR=$1 cmake --install build
