#!/bin/sh -e

meson setup build          \
    --prefix=/usr          \
    --libexecdir=/usr/lib  \
    -Ddefault_library=both \
    -Denable-docs=false    \
    -Denable-wayland=true  \
    -Denable-x11=true      \

meson compile -C build
meson install -C build --destdir=$1

#32bit

rm -rf build
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
meson setup build                    \
      --prefix=/usr                  \
      --libdir=/usr/lib32            \
      --buildtype=release            \
      -D enable-docs=false

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
