#!/bin/sh -e

PREFIX="${CROSS_PREFIX:-/usr}"

MESON_OPTS=(
    --prefix="$PREFIX"
    --libexecdir="$PREFIX/lib"
    -D default_library=both
    -D enable-docs=false
    -D enable-wayland=true
    -D enable-x11=true
)

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    MESON_OPTS+=(--cross-file "$HOKUTO_ARCH")
fi

meson setup build "${MESON_OPTS[@]}"

meson compile -C build
meson install -C build --destdir=$1


if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
meson setup build                    \
      --prefix=/usr                  \
      --libdir=/usr/lib32            \
      --buildtype=release            \
      -D enable-docs=false

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
fi
