#!/bin/sh -e

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddefault_library=both \
    -Denable-docs=false \
    -Denable-wayland=true \
    -Denable-x11=true \
    . output

ninja -C output
DESTDIR=$1 ninja -C output install

#32bit

mkdir build
cd build
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
meson setup ..                       \
      --prefix=/usr                  \
      --libdir=/usr/lib32            \
      --buildtype=release            \
      -D enable-docs=false

ninja
DESTDIR=$PWD/DESTDIR ninja install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
