#!/bin/sh -e

mkdir build
cd build

../configure --prefix=/usr           \
             --sysconfdir=/etc       \
             --enable-elf-shlibs     \
             --disable-libblkid      \
             --disable-libuuid       \
             --disable-uuidd         \
             --disable-fsck

make
make DESTDIR=$1 install

rm -fv $1/usr/lib/{libcom_err,libe2p,libext2fs,libss}.a
