#!/bin/sh -e

cmake_options=(
    -B build
    -G Ninja
    -W no-dev
    -D CMAKE_BUILD_TYPE=Release
    -D CMAKE_INSTALL_PREFIX=/usr
    -D MI_BUILD_OBJECT=OFF
    -D MI_INSTALL_TOPLEVEL=ON
  )

cmake "${cmake_options[@]}"
cmake --build build
DESTDIR="${1}" cmake --install build
