#!/bin/sh -e


sed -i '/echo "Done!" || echo "Failed!!!"/a \
ln -sf /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/certs/ca-bundle.crt' make-ca

make DESTDIR=$1 install
install -vdm755 $1/etc/ssl/local

# sauzeros binary repo cert + initial certdata.txt
install -Dm644 <(xz -dc certdata.txt.xz) "$1/etc/ssl/certdata.txt"
install -Dm644 <(xz -dc caddy_local_root.pem.xz) "$1/etc/ssl/local/caddy_local_root.pem"
