#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --without-xmlto \
    --disable-specs \
    --disable-static

make
make DESTDIR="$1" install

