#!/bin/sh -e

sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" libiberty/configure
./configure --target=aarch64-linux-gnu \
              --with-sysroot=/usr/aarch64-linux-gnu \
              --prefix=/usr \
              --disable-gprofng \
              --disable-multilib \
              --with-gnu-as \
              --with-gnu-ld \
              --disable-nls \
              --enable-gold \
              --enable-ld=default \
              --enable-plugins \
              --enable-deterministic-archives \
              --enable-new-dtags

make
make DESTDIR="$1" install

# Remove file conflicting with host binutils and manpages for MS Windows tools
rm "$1"/usr/share/man/man1/aarch64-linux-gnu-{dlltool,windres,windmc}*
rm "$1"/usr/lib/bfd-plugins/libdep.so

# Remove info documents that conflict with host version
rm -r "$1"/usr/share/info

