#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_SHARED_LIBS=True

cmake --build   build
cmake --install build

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
export CC='gcc -m32'
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config
cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=True \
    -DCMAKE_C_FLAGS="$CFLAGS -ffat-lto-objects" \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib32
  cmake --build build -v

DESTDIR="$PWD/DESTDIR" cmake --install build
install -d $1/usr/lib32/pkgconfig
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
fi
