#!/bin/bash -e

# Use CROSS_PREFIX if set (defaults to /usr in hokuto)
PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [[ "${HOKUTO_CROSS:-0}" == "1" ]]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure \
    --prefix="$PREFIX" \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    $CROSS_OPTS

make
make DESTDIR="$1" install

if [ "$MULTILIB" = "1" ]; then
#32bit split package
make distclean
CC="gcc -m32" CXX="g++ -m32"   \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr      \
         --disable-static      \
         --libdir=/usr/lib32

make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
