#!/bin/sh -e
mkdir build-x86_64
cd    build-x86_64

../configure --prefix=/usr                                \
             --target=x86_64-w64-mingw32                  \
             --infodir=/usr/share/info/x86_64-w64-mingw32 \
             --disable-nls                                \
             --disable-werror

make
make   DESTDIR=$PWD/DESTDIR install
rm -v  DESTDIR/usr/lib/bfd-plugins/libdep.so
install -d $1/usr
cp -Rv DESTDIR/usr/* $1/usr
cd ..

#32bit

mkdir build-i686
cd    build-i686

../configure --prefix=/usr                              \
             --target=i686-w64-mingw32                  \
             --infodir=/usr/share/info/i686-w64-mingw32 \
             --disable-nls                              \
             --disable-werror

make
make   DESTDIR=$PWD/DESTDIR install
rm -v  DESTDIR/usr/lib/bfd-plugins/libdep.so
cp -Rv DESTDIR/usr/* $1/usr


