#!/bin/sh -e

./autogen.sh
./configure --prefix=/usr              \
            --with-internal-glib       \
            --disable-host-tool

make
make DESTDIR=$1 install

ln -s pkgconf $1/usr/bin/pkg-config
