#!/bin/sh -e

patch -Np1 -i unzip-6.0-consolidated_fixes-1.patch

case `uname -m` in
          i?86)
                sed -i -e 's/DASM_CRC"/DASM_CRC -DNO_LCHMOD"/' unix/Makefile
                make -f unix/Makefile linux
                ;;
        *)
                sed -i -e 's/CFLAGS="-O -Wall/& -DNO_LCHMOD/' unix/Makefile
                make -f unix/Makefile linux_noasm
                ;;
        esac

make prefix="$1/usr" MANDIR="$1/usr/share/man/man1" install
