#!/bin/bash -e

# Built per kernel: hokuto sets HOKUTO_KERNEL_DIR / HOKUTO_KERNEL_RELEASE.
: "${HOKUTO_KERNEL_DIR:?kernel module package: build it with hokuto as <name>~<kernel>}"

cd hid-xpadneo
make KERNEL_SOURCE_DIR="$HOKUTO_KERNEL_DIR"
make KERNEL_SOURCE_DIR="$HOKUTO_KERNEL_DIR" INSTALL_MOD_PATH=$1 modules_install
rm -rf $1/lib/modules/*/modules*

cd ..
install -d $1/etc/modules-load.d/
install -Dm644 xpadneo.conf $1/etc/modules-load.d/xpadneo.conf

install -d $1/etc/modprobe.d/
install -Dm644 99-xpadneo-bluetooth.conf $1/etc/modprobe.d/99-xpadneo-bluetooth.conf
