#!/bin/sh -e

meson setup build            \
      --prefix=/usr          \
      --buildtype=release    \
      --wrap-mode=nodownload

meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
meson setup build          \
    --prefix=/usr          \
    --libdir=/usr/lib32    \
    --cross-file=lib32     \
    --buildtype=release    \
    --wrap-mode=nodownload \
    -D qt5=disabled        \
    -D qt6=disabled

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
install -d $1/usr/lib32
cp -vR DESTDIR/usr/lib32/* $1/usr/lib32
fi
