#!/bin/sh -e

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_OPT="--host=${HOKUTO_ARCH}-linux-gnu"
else
    HOST_OPT=""
fi

./configure --prefix=${CROSS_PREFIX:-/usr} \
            --disable-static     \
            --enable-thread-safe \
            $HOST_OPT

make
make DESTDIR=$1 install

