#!/bin/bash -e

hokuto-meson build
meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf build
hokuto-meson-32 build
meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
_pick "$PWD/DESTDIR" lib32-$3 usr/lib32/libdisplay-info.so*
_pick "$PWD/DESTDIR" lib32-$3 usr/lib32/pkgconfig/libdisplay-info.pc
fi
