#!/bin/bash -e

export CFLAGS="${CFLAGS/_FORTIFY_SOURCE=3/_FORTIFY_SOURCE=2}"
export CXXFLAGS="${CXXFLAGS/_FORTIFY_SOURCE=3/_FORTIFY_SOURCE=2}"
export CC=clang CXX=clang++ AR=ar NM=nm
export LCMS2_LIB_DIR=/usr/lib
export ZSTD_SYS_USE_PKG_CONFIG=1
export CARGO_FEATURE_SYSTEM=1 # Use system-provided libffi

cargo fetch --target host-tuple
cargo build --frozen --release

# Install phase
install -Dm755 target/release/deno "${1}"/usr/bin/deno

install -dm755 "${1}"/usr/share/bash-completion/completions
./target/release/deno completions bash > "${1}"/usr/share/bash-completion/completions/deno
install -dm755 "${1}"/usr/share/zsh/site-functions
./target/release/deno completions zsh > "${1}"/usr/share/zsh/site-functions/_deno
install -dm755 "${1}"/usr/share/fish/vendor_completions.d
./target/release/deno completions fish > "${1}"/usr/share/fish/vendor_completions.d/deno.fish
