#!/bin/sh -e

cargo build --release

# Install phase
install -Dm755 target/release/deno "${1}"/usr/bin/deno

install -dm755 "${1}"/usr/share/bash-completion/completions
./target/release/deno completions bash > "${1}"/usr/share/bash-completion/completions/deno
install -dm755 "${1}"/usr/share/zsh/site-functions
./target/release/deno completions zsh > "${1}"/usr/share/zsh/site-functions/_deno
install -dm755 "${1}"/usr/share/fish/vendor_completions.d
./target/release/deno completions fish > "${1}"/usr/share/fish/vendor_completions.d/deno.fish
