#!/bin/sh -e

cat > config.mak <<EOF
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_NSEC=YesPlease
NO_SVN_TESTS=YesPlease
NO_SYS_POLL_H=1
NO_CROSS_DIRECTORY_HARDLINKS=1
NO_INSTALL_HARDLINKS=1
EOF

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    ac_cv_lib_curl_curl_global_init=yes \
    ac_cv_snprintf_returns_bogus=no \
    ac_cv_fread_reads_directories=yes

make
make DESTDIR="$1" install

install -d $1/etc
install -Dm 644 gitconfig $1/etc/gitconfig
