#!/bin/bash -e

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_OPT="--host=${HOKUTO_ARCH}-linux-gnu"
else
    HOST_OPT=""
fi

./configure --prefix=${CROSS_PREFIX:-/usr} \
            --sysconfdir=/etc \
            $HOST_OPT

make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make clean
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
export CC='gcc -m32'
export CXX='g++ -m32'
export PKG_CONFIG_PATH='/usr/lib32/pkgconfig'
./configure          \
  --prefix=/usr      \
  --sysconfdir=/etc  \
  --sbindir=/usr/bin \
  --disable-static   \
  --libdir=/usr/lib32

make
make DESTDIR="${pkgdir}" install
rm -rf "${pkgdir}"/{etc,usr/{bin,include,share}}
fi
