#!/bin/bash -e

# Use LTO
export CARGO_PROFILE_RELEASE_LTO=true CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1

cargo fetch --locked --target host-tuple

cargo build --release --frozen --features pcre2

install -vDm755 -t "${1}/usr/bin" target/release/rg

mkdir -vp "${1}/usr/share/zsh/site-functions"
target/release/rg --generate complete-zsh > "${1}/usr/share/zsh/site-functions/_rg"

mkdir -vp "${1}/usr/share/bash-completion/completions"
target/release/rg --generate complete-bash > "${1}/usr/share/bash-completion/completions/rg"

mkdir -vp "${1}/usr/share/fish/vendor_completions.d"
target/release/rg --generate complete-fish > "${1}/usr/share/fish/vendor_completions.d/rg.fish"

mkdir -vp "${1}/usr/share/man/man1"
target/release/rg --generate man > "${1}/usr/share/man/man1/rg.1"
