#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --disable-nls \
    --disable-introspection

make
make DESTDIR="$1" install
