#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --enable-gio-unix \
    --enable-gudev \
    --disable-debug

make
make DESTDIR="$1" install
