#!/bin/sh -e

#patch -Np1 -i coreutils-9.7-upstream_fix-1.patch
#patch -Np1 -i coreutils-9.7-i18n-1.patch

autoreconf -fv
automake -af

FORCE_UNSAFE_CONFIGURE=1 ./configure \
    --prefix=/usr            \
    --enable-no-install-program=kill,uptime

make
make DESTDIR="$1" install

