#!/bin/sh -e

autoreconf -fv
automake -af

FORCE_UNSAFE_CONFIGURE=1 ./configure \
    --prefix=/usr                    \
    --with-openssl                   \
    --enable-no-install-program=kill,uptime

make
make DESTDIR="$1" install

