#!/bin/bash -e

chmod +x Avalonia-86-for-Linux-x64-$2.AppImage
./Avalonia-86-for-Linux-x64-$2.AppImage --appimage-extract
cd squashfs-root
install -d $1/opt/avalonia86
install -d $1/usr/bin
find . -type f -exec chmod 0644 '{}' \;
cp -r usr/bin/* $1/opt/avalonia86/

chmod 0755 $1/opt/avalonia86/Avalonia86
ln -s /opt/avalonia86/Avalonia86 $1/usr/bin/Avalonia86

install -Dm 0644 Avalonia86.desktop $1/usr/share/applications/Avalonia86.desktop
install -Dm 0644 Avalonia86.png $1/usr/share/icons/Avalonia86.png
