#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

cmake -B build                 \
  -D CMAKE_INSTALL_PREFIX="$PREFIX" \
  -D BUILD_SHARED_LIBS=ON

cmake --build   build
DESTDIR=$1 cmake --install build
