#!/bin/sh -e

./autogen.sh
CFLAGS="-DWOLFSSL_NO_ASN_STRICT" ./configure --host=$LFS_TGT \
            --enable-static \
            --enable-opensslextra \
            --enable-all \
            --prefix=/usr

make
make DESTDIR=$LFS install
