#!/bin/sh -e

# Instruct the compiler to trim absolute paths in resulting binaries and instead
# change them to relative paths ($PWD/... ./...).
export RUSTFLAGS="$RUSTFLAGS --remap-path-prefix=$PWD=."

# This package mimics the download process of rust's 'x.py'
# bootstrap library to allow for the removal of the internet
# connection requirement per build.
{
    mkdir -p "${cache_dir:=build/cache/2021-11-01}"

    for tarball in *.tar.xz\?no-extract; do
        mv -f "$tarball" "$cache_dir/${tarball%%\?no-extract}"
    done
}

# Set shared linking as the default.
sed 's/\(crt_static_default = \)true/\1false/' \
    compiler/rustc_target/src/spec/linux_gnu_base.rs > _
mv -f _ compiler/rustc_target/src/spec/linux_gnu_base.rs

# Ignore checksums of files modified above.
sed 's/\("files":{\)[^}]*/\1/' \
    vendor/curl-sys/.cargo-checksum.json > _
mv -f _ vendor/curl-sys/.cargo-checksum.json

cat > config.toml <<EOF
[llvm]
link-shared = true
skip-rebuild = true

[build]
build     = "x86_64-unknown-linux-gnu"
host      = [ "x86_64-unknown-linux-gnu" ]
target    = [ "x86_64-unknown-linux-gnu" ]

docs           = false
compiler-docs  = false
extended       = true
submodules     = false
python         = "python3"
locked-deps    = true
vendor         = true
tools          = ["cargo", "rustfmt"]
sanitizers     = false
profiler       = false
full-bootstrap = false

[install]
prefix = "/usr"

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"
crt-static  = false
sanitizers  = false

[dist]
src-tarball = false

[rust]
backtrace         = false
channel           = "stable"
codegen-tests     = false
codegen-units-std = 1
codegen-units     = 0
debug             = false
debug-assertions  = false
debuginfo-level   = 0
incremental       = false
jemalloc          = false
rpath             = false
dist-src          = false
EOF

./x.py build -j "$(grep -scF 'core id' /proc/cpuinfo)"
./x.py install

rm -rf \
    "$1/usr/lib/rustlib/src/" \
    "$1/usr/share/doc" \
    "$1/usr/share/zsh" \
    "$1/usr/lib/rustlib/uninstall.sh"
