#!/bin/bash -e

hokuto-meson build               \
  --libexecdir /usr/lib/gamemode \
  -D with-examples=false

meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf build
hokuto-meson-32 build            \
  --libexecdir /usr/lib/gamemode \
  -D with-examples=false         \
  -D with-sd-bus-provider=no-daemon

meson compile -C build
DESTDIR=tmp32dir meson install -C build
cd build
rm -rf tmp32dir/{etc,usr/include}
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
cp -a tmp32dir/* $dest_dir/
fi

install -Dm644 ../gamemode.ini $1/etc/gamemode.ini
