#!/bin/sh -e

meson build  --prefix=/usr \
             --libexecdir=lib/libvirt \
            -Drunstatedir=/run \
	    -Dselinux=disabled \
            -Dapparmor=disabled \
            -Ddocs=enabled \
            -Dtests=disabled \
            -Ddriver_qemu=enabled \
            -Ddriver_remote=enabled \
            -Dfuse=enabled \
            -Dqemu_user=dbz \
            -Dqemu_group=dbz \
            -Ddriver_libvirtd=enabled

ninja -C build
DESTDIR=$1 ninja -C build install

