#!/bin/bash -e

export CFLAGS="${CFLAGS//-O2/}"
export CXXFLAGS="${CXXFLAGS//-O2/}"

autoreconf -fvi
./configure \
  --enable-prof \
  --enable-autogen \
  --disable-static \
  --prefix=/usr
make
make DESTDIR="${1}" install
