#!/bin/bash -e

install -Dm755 $3 "$1"/usr/bin/$3
install -Dm755 updater_bootstrap "$1"/usr/share/$3/updater_bootstrap
install -Dm644 $3.desktop "$1"/usr/share/applications/$3.desktop
install -Dm644 $3.png "$1"/usr/share/icons/hicolor/256x256/apps/$3.png
