#!/bin/sh -e

chmod 0755 brave
install -d "$1/opt/$3"
cp -a * "$1/opt/$3"

# allow firejail users to get the suid sandbox working
chmod 4755 "$1/opt/brave-bin/chrome-sandbox"

install -Dm 0755 "$3.sh" "$1/usr/bin/brave"
install -Dm 0644 -t "$1/usr/share/applications/" "brave-browser.desktop"
pushd "$1/usr/"
for size in 16x16 24x24 32x32 48x48 64x64 128x128 256x256; do
	install -Dm0644 "$1/opt/$3/product_logo_${size/x*/}.png" \
		"share/icons/hicolor/$size/apps/brave-desktop.png"
done
