#!/bin/sh -e

# Setup base directories.
for d in boot dev etc home mnt repo usr var opt run swap tools; do
    install -dm 755 "$LFS/$d"
done

install -dm 555  "$LFS/proc"
install -dm 555  "$LFS/sys"
install -dm 0750 "$LFS/root"
install -dm 1777 "$LFS/tmp"

# Setup /usr hierarchy.
for d in bin include lib lib32 share src; do
    install -dm 755 "$LFS/usr/$d"
done

# Setup manpages directories.
for d in 1 2 3 4 5 6 7 8; do
    install -dm 755 "$LFS/usr/share/man/man$d"
done

# Add symlinks.
ln -s usr/bin "$LFS/bin"
ln -s usr/bin "$LFS/sbin"
ln -s bin     "$LFS/usr/sbin"
ln -s usr/lib "$LFS/lib"
ln -s usr/lib32 "$LFS/lib32"
ln -s usr/lib "$LFS/lib64"
ln -s lib     "$LFS/usr/lib64"

# Setup /var.
for d in cache local opt log/old lib/misc empty service; do
    install -dm 755 "$LFS/var/$d"
done

install -dm 1777 "$LFS/var/tmp"
install -dm 1777 "$LFS/var/tmpdir"
install -dm 1777 "$LFS/var/spool/mail"

ln -s spool/mail  "$LFS/var/mail"
ln -s ../run      "$LFS/var/run"
ln -s ../run/lock "$LFS/var/lock"

# Setup /usr/local (usually for any programs installed outside package manager).
for d in bin etc games include lib man sbin share src; do
    install -dm 755 "$LFS/usr/local/$d"
done

ln -s ../man "$LFS/usr/local/share/man"

# /etc skeleton files.
for f in bashrc fstab group host.conf hosts issue inputrc locale.conf os-release \
         nanorc passwd profile resolv.conf securetty shells mime.types; do
    install -m 644 "$f" "$LFS/etc"
done

for f in crypttab ; do
    install -m 600 "$f" "$LFS/etc"
done

for f in init-repos ; do
    install -m 755 "$f" "$LFS/usr/bin"
done

ln -s /proc/self/mounts "$LFS/etc/mtab"

install -d "$LFS/etc/kiss"
install -Dm 644 kiss.conf "$LFS/etc/kiss/kiss.conf"
