#!/bin/bash -e
mkdir -p $1/usr/bin
install -Dm755 update-repology $1/usr/bin/update-repology
rm update-repology

mkdir -p $1/opt/repology/updater
rm -rf repos.d
mv repos repos.d

# tar->bsdtar in tar.py
sed -i "s/\['tar', '-x', '-z', '-f', tarpath, '-C', statedir.get_path()\]/['bsdtar', '-x', '-z', '-f', tarpath, '-C', statedir.get_path()]/" repology/fetchers/fetchers/tar.py

cp -r * $1/opt/repology/updater/
chown -R root:wheel $1/opt/repology
chmod -R g+rw $1/opt/repology
