#!/bin/bash -e

patch -Np1 -i cyrus-sasl-2.1.28-gcc15_fixes-1.patch
autoreconf -fiv
sed '/saslint/a #include <time.h>'       -i lib/saslutil.c
sed '/plugin_common/a #include <time.h>' -i plugins/cram.c

PREFIX="${CROSS_PREFIX:-/usr}"
# A cross-system build stays inside the sysroot, /etc included.
SYSCONFDIR=/etc
[ "$PREFIX" = /usr ] || SYSCONFDIR="$PREFIX/etc"

configure_options=(
  --disable-krb4
  --disable-macos-framework
  --disable-otp
  --disable-passdss
  --disable-srp
  --disable-srp-setpass
  --disable-static
  --enable-alwaystrue
  --enable-anon
  --enable-auth-sasldb
  --enable-checkapop
  --enable-cram
  --enable-digest
  --enable-login
  --enable-ntlm
  --enable-plain
  --enable-shared
  --infodir="$PREFIX/share/info"
  --mandir="$PREFIX/share/man"
  --prefix="$PREFIX"
  --sbin="$PREFIX/bin"
  --sysconfdir="$SYSCONFDIR"
  --with-dblib=gdbm
  --with-devrandom=/dev/urandom
  --with-configdir=/etc/sasl2:/etc/sasl:/usr/lib/sasl2
  --with-pam
  --with-saslauthd=/var/run/saslauthd
)
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # The GSSAPI and SQL plugins are removed below anyway: build without
    # them rather than against the target's krb5 and databases.
    configure_options+=(
      --host="$HOKUTO_ARCH-linux-gnu"
      --disable-gssapi
      --without-pgsql
      --without-sqlite3
    )
else
    configure_options+=(
      --enable-gssapi
      --with-pgsql=/usr/lib
      --with-sqlite3=/usr/lib
    )
fi

./configure "${configure_options[@]}"
# prevent excessive overlinking by libtool
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool

make -j1
make DESTDIR="${1}" install-pkgconfigDATA
for _target in include lib sasldb plugins utils; do
make DESTDIR="${1}" install
done
# remove files provided by extra/cyrus-sasl
rm -fv "${1}$PREFIX"/lib/sasl2/lib{gs2,gssapiv2,ldapdb,sql}.so*
