#!/bin/sh -e

export DESTDIR="$1"

# Don't build tests.
sed -i "/subdir('tests')/d" meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    . output

ninja -C output
ninja -C output install
