#!/bin/bash -e

make CC="${CC:-gcc} $CFLAGS -fPIC $LDFLAGS" AR="${AR:-ar}" RANLIB="${RANLIB:-ranlib}" -f Makefile-libbz2_so
make CC="${CC:-gcc} $CFLAGS -static -fPIC $LDFLAGS" AR="${AR:-ar}" RANLIB="${RANLIB:-ranlib}" bzip2

mkdir -p \
    "$1/$CROSS_PREFIX/bin" \
    "$1/$CROSS_PREFIX/lib" \
    "$1/$CROSS_PREFIX/share/man/man1" \
    "$1/$CROSS_PREFIX/include"

cp -f \
    bzip2 \
    bzdiff \
    bzgrep \
    bzmore \
    "$1/$CROSS_PREFIX/bin"

cp -f \
    libbz2.so.$2 \
    libbz2.a \
    "$1/$CROSS_PREFIX/lib"

cp -f bzip2.1 "$1/$CROSS_PREFIX/share/man/man1"
cp -f bzlib.h "$1/$CROSS_PREFIX/include"

ln -sf libbz2.so.$2 "$1/$CROSS_PREFIX/lib/libbz2.so"
ln -sf libbz2.so.$2 "$1/$CROSS_PREFIX/lib/libbz2.so.1"
ln -sf libbz2.so.$2 "$1/$CROSS_PREFIX/lib/libbz2.so.1.0"
ln -sf bzip2 "$1/$CROSS_PREFIX/bin/bunzip2"
ln -sf bzip2 "$1/$CROSS_PREFIX/bin/bzcat"

sed "s|@VERSION@|$2|" -i bzip2.pc
install -Dm644 bzip2.pc -t "$1/$CROSS_PREFIX"/lib/pkgconfig

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit split package
make clean
sed -e "s/^CC=.*/CC=gcc -m32/" -i Makefile{,-libbz2_so}
make -f Makefile-libbz2_so
make libbz2.a

dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d "$dest_dir/usr/lib32"
install -Dm755 libbz2.so.$2 $dest_dir/usr/lib32/libbz2.so.$2
ln -sf libbz2.so.$2 $dest_dir/usr/lib32/libbz2.so
ln -sf libbz2.so.$2 $dest_dir/usr/lib32/libbz2.so.1
ln -sf libbz2.so.$2 $dest_dir/usr/lib32/libbz2.so.1.0
install -Dm644 libbz2.a $dest_dir/usr/lib32/libbz2.a
fi
