#!/bin/sh -e

install -dm755 "${1}/usr/share/sounds/Smooth"
install -dm755 "${1}/usr/share/sounds/Smooth/stereo"
install -Dm644 index.theme "${1}/usr/share/sounds/Smooth"
install -Dm644 stereo/* "${1}/usr/share/sounds/Smooth/stereo"
