#!/bin/sh -e

 mkdir -p $1/usr/share/fonts/TTF
 mkdir -p $1/usr/share/fonts/OTF
 install -Dm644 *.tt[fc] -t "$1"/usr/share/fonts/TTF/
 install -Dm644 *.otf -t "$1"/usr/share/fonts/OTF/

unzip freefont*.zip
cd freefont-20120503
install -Dm644 *.tt[fc] -t "$1"/usr/share/fonts/TTF/
cd ..
unzip Cascadia*.zip
 install -Dm644 ttf/*.tt[fc] -t "$1"/usr/share/fonts/TTF/
 install -Dm644 otf/static/*.otf -t "$1"/usr/share/fonts/OTF/
rm -rf otf
rm -rf ttf

