#!/bin/bash -e

# Optimization logic for CPUFLAGS
OPT_FLAGS=""
case "$CPUFLAGS" in
  *avx2*)   OPT_FLAGS="$OPT_FLAGS --enable-avx2" ;;
  *avx*)    OPT_FLAGS="$OPT_FLAGS --enable-avx" ;;
  *sse4_2*) OPT_FLAGS="$OPT_FLAGS --enable-sse42" ;;
  *neon*)   OPT_FLAGS="$OPT_FLAGS --enable-neon" ;;
esac

  ./configure \
    --prefix=/usr \
    --disable-debug \
    --disable-static \
    --disable-stripping \
    --enable-cuda-llvm \
    --enable-lto \
    --enable-fontconfig \
    --enable-gmp \
    --enable-gnutls \
    --enable-gpl \
    --enable-libaom \
    --enable-libass \
    --enable-libdav1d \
    --enable-libdrm \
    --enable-libfreetype \
    --enable-libfribidi \
    --enable-libglslang \
    --enable-libharfbuzz \
    --enable-libjxl \
    --enable-libmodplug \
    --enable-libmp3lame \
    --enable-libopenjpeg \
    --enable-libopus \
    --enable-librsvg \
    --enable-libvorbis \
    --enable-libpulse \
    --enable-libv4l2 \
    --enable-libsoxr \
    --enable-libsrt \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxcb \
    --enable-libxml2 \
    --enable-libxvid \
    --enable-nvdec \
    --enable-nvenc \
    --enable-opengl \
    --enable-shared \
    --enable-version3 \
    --enable-vulkan \
    $OPT_FLAGS

make
gcc tools/qt-faststart.c -o tools/qt-faststart
make DESTDIR=$1 install
install -v -m755    tools/qt-faststart $1/usr/bin
rm -rf "$1/usr/share/ffmpeg/examples"

if [ "$MULTILIB" = "1" ]; then
#32bit split package
CFLAGS+=' -fno-lto'
make distclean
./configure --prefix=/usr                             \
            --libdir=/usr/lib32                       \
            --shlibdir=/usr/lib32                     \
            --cc="gcc -m32"                           \
            --pkg-config=i686-pc-linux-gnu-pkg-config \
            --enable-gpl                              \
            --enable-version3                         \
            --enable-nonfree                          \
            --disable-static                          \
            --enable-shared                           \
            --disable-debug                           \
            --enable-libaom                           \
            --enable-libfdk-aac                       \
            --enable-libfreetype                      \
            --enable-libopus                          \
            --enable-libvorbis                        \
            --enable-libvpx                           \
            --enable-libx264                          \
            --enable-libx265                          \
            --enable-vulkan                           \
            --enable-cuda-llvm                        \
            --enable-opengl                           \
            --enable-openssl

make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
