#!/bin/sh -e

patch -Np1 -i ffmpeg-*-chromium_method-1.patch

./configure \
    --cc="$CC" \
    --cxx="$CXX" \
    --prefix=/usr \
    --disable-debug \
    --disable-static \
    --enable-libass \
    --enable-libdrm \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-nonfree \
    --enable-openssl \
    --enable-shared \
    --enable-gpl \
    --x86asmexe=nasm

make
make DESTDIR=$1 install

rm -rf "$1/usr/share/ffmpeg/examples"
