#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
# A cross-system build stays inside the sysroot, /etc included.
SYSCONFDIR=/etc
[ "$PREFIX" = /usr ] || SYSCONFDIR="$PREFIX/etc"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi

./configure --prefix="$PREFIX"     \
            --sysconfdir="$SYSCONFDIR" \
            --disable-static "${CROSS_OPTS[@]}"

make
make DESTDIR=$1 install
