#!/bin/bash -e

CFLAGS+=" $CPPFLAGS -ffat-lto-objects"
make V=1
make DESTDIR="$1" install

cd bindings/python
pkgdir=$HOKUTO_SPLIT_DIR/python-capstone
python -m build --wheel --no-isolation
python -m installer --destdir="$pkgdir" dist/*.whl
