#!/bin/sh -e

git submodule init
git submodule set-url src/3rdparty "."/qtwebengine-chromium
git -c protocol.file.allow=always submodule update

git cherry-pick -n 313960be3a586969c3af27f1845ab47d9b40ac34 ae6991d950bb343accad96b96047fe605c17bcc3 # Fix flickering

# Bump chromium to head of stable branch
cd src/3rdparty
[[ -n 37b6aeaa3ef9bf7e1901aa02a317a2707557709d ]] && git checkout 37b6aeaa3ef9bf7e1901aa02a317a2707557709d || true

# Build phase
cmake -B build \
  -D CMAKE_MESSAGE_LOG_LEVEL=STATUS \
  -D CMAKE_TOOLCHAIN_FILE=/usr/lib/cmake/Qt6/qt.toolchain.cmake \
  -D QT_FEATURE_webengine_system_ffmpeg=ON \
  -D QT_FEATURE_webengine_system_icu=ON \
  -D QT_FEATURE_webengine_system_re2=ON \
  -D QT_FEATURE_webengine_system_openh264=ON \
  -D QT_FEATURE_webengine_proprietary_codecs=ON \
  -D QT_FEATURE_webengine_kerberos=ON \
  -D QT_FEATURE_webengine_webrtc_pipewire=ON

cmake --build build
DESTDIR="${1}" cmake --install build
