#!/bin/sh -e
mkdir build-x86_64-mingw-w64-static
cd    build-x86_64-mingw-w64-static

../configure --prefix=/usr               \
             --target=x86_64-w64-mingw32 \
             --with-sysriit=/usr/x86_64-w64-mingw32 \
             --disable-shared            \
             --disable-multilib          \
             --disable-threads           \
             --enable-languages=c,c++

make all-gcc
make DESTDIR=$1 install-gcc
cd ..

#32bit

mkdir build-i686-mingw-w64-static
cd    build-i686-mingw-w64-static

../configure --prefix=/usr             \
             --target=i686-w64-mingw32 \
             --with-sysroot=/usr/i686-w64-mingw32 \
             --disable-shared          \
             --disable-multilib        \
             --disable-threads         \
             --enable-languages=c,c++

make all-gcc
make DESTDIR=$1 install-gcc

# remove gcc duplicates
rm -rf $1/usr/share/{locale,info,man}

