#!/bin/sh -e

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3 ..

cmake --build .

cmake --build . --target install -- DESTDIR="$1"
