#!/bin/sh -e

meson setup build \
  --prefix=/usr \
  -D wallpaper=disabled

meson compile -C build
meson install -C build --destdir=$1

# install config for XFCE
install -Dm644 xfce-portals.conf $1/usr/share/xdg-desktop-portal/xfce-portals.conf
