#!/bin/sh -e

export BUILD_ZLIB=0
export BUILD_BZIP2=0
export LDFLAGS="$LDFLAGS -pthread"

sh Configure -des                                        \
             -D prefix=/usr                              \
             -D vendorprefix=/usr                        \
             -D privlib=/usr/lib/perl5/$2/core_perl      \
             -D archlib=/usr/lib/perl5/$2/core_perl      \
             -D sitelib=/usr/lib/perl5/$2/site_perl      \
             -D sitearch=/usr/lib/perl5/$2/site_perl     \
             -D vendorlib=/usr/lib/perl5/$2/vendor_perl  \
             -D vendorarch=/usr/lib/perl5/$2/vendor_perl \
             -D man1dir=/usr/share/man/man1              \
             -D man3dir=/usr/share/man/man3              \
             -D pager="/usr/bin/less -isR"               \
             -D useshrplib                               \
             -D usethreads

make
make DESTDIR="$1" install
