#!/bin/sh -e

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"

    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./autogen.sh
./configure \
    --prefix="$PREFIX" \
    $CROSS_OPTS

make
make DESTDIR="$1" install

# Fix incorrect paths from cross-compilation
if [ "${HOKUTO_CROSS:-0}" = "1" ] && [ "$PREFIX" = "/usr" ]; then
    if [ -d "$1$PREFIX/$HOKUTO_ARCH-linux-gnu" ]; then
        echo "Moving files from sysroot $1$PREFIX/$HOKUTO_ARCH-linux-gnu to $1$PREFIX"
        cp -rl "$1$PREFIX/$HOKUTO_ARCH-linux-gnu/"* "$1$PREFIX/"
        rm -rf "$1$PREFIX/$HOKUTO_ARCH-linux-gnu"
    fi
fi
