#!/bin/bash -e

cmake -B build                        \
  -D CMAKE_BUILD_TYPE=None            \
  -D CMAKE_INSTALL_PREFIX=/usr        \
  -D CMAKE_INSTALL_LIBDIR=/usr/lib    \
  -D CMAKE_POLICY_VERSION_MINIMUM=3.5 \
  -D BUILD_SHARED_LIBS=ON

cmake --build build
DESTDIR=$1 cmake --install build
