#!/bin/bash -e

# The lm-sensors Makefile hardcodes `CC := gcc` and `AR := ar`. A makefile
# assignment beats the environment, so the cross toolchain is only honoured if
# it is passed on the make command line.
_tools=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    _tools=(CC="$CC" AR="$AR")
fi

make "${_tools[@]}" PREFIX=/usr
make "${_tools[@]}" BUILD_STATIC_LIB=0 \
    PREFIX=/usr SBINDIR=/usr/bin MANDIR=/usr/share/man DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make clean
sed -i 's/CC := gcc/CC := gcc -m32/' Makefile
make PREFIX=/usr
make PREFIX=/usr LIBDIR=/usr/lib32 BUILD_STATIC_LIB=0 DESTDIR=$PWD/DESTDIR install
_pick "$PWD/DESTDIR" lib32-lm-sensors usr/lib32/libsensors.so*
fi
