#!/bin/sh -e

chmod +x Chatterino-x86_64-Qt6.AppImage
./Chatterino-x86_64-Qt6.AppImage --appimage-extract

mkdir -pv $1/opt/chatterino/usr/{bin,lib}
mkdir -pv $1/usr/bin
mv squashfs-root/usr/lib/libicu* $1/opt/chatterino/usr/lib
mv squashfs-root/usr/share $1/usr/
mv squashfs-root/usr/bin/chatterino $1/opt/chatterino/usr/bin
ln -s /opt/chatterino/usr/bin/chatterino $1/usr/bin/chatterino
