#!/bin/sh -e

# fix build with qt6
patch -Np1 -i uefitool-0.28.0-qt6-cli.patch

_tools=(UEFIPatch UEFIReplace)

for _tool in "${_tools[@]}"; do
cd "${_tool}"
qmake6
make
cd ..
done

for tool in "${_tools[@]}"; do
  install -Dm755 "${tool}/${tool}" "${1}/usr/bin/${tool,,}"
done
# Install patches.txt
install -Dm644 UEFIPatch/patches.txt "${1}/usr/share/${3}/patches.txt"
