#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

# Build fails with clang due to -Werror (forced on) and
# -Wunused-command-line-argument which is triggered by.
# the below CFLAGS.
export CFLAGS="-Wno-unused-command-line-argument $CFLAGS"

meson setup build         \
  --prefix=/usr           \
  --sysconfdir=/etc       \
  --mandir=/usr/share/man \
  --libexecdir=/usr/lib   \
  -D default_library=both \
  -D debug-gui=false      \
  -D documentation=false  \
  -D tests=false          \
  -D libwacom=false

meson compile -C build
meson install -C build --destdir=$1
