#!/bin/bash -e

./configure --prefix=/usr    \
            --disable-static \
            --disable-tests

make
make DESTDIR=$1 install

if [ "$MULTILIB" = "1" ]; then
#32bit split package
make clean
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --disable-tests          \
            --disable-static

make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/{lib32,include}
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
cp -vr DESTDIR/usr/include/libunwind-x86.h $dest_dir/usr/include/
fi
