#!/bin/sh -e

./configure --prefix=/usr    \
            --disable-static \
            --disable-tests

make
make DESTDIR=$1 install

#32bit

make clean
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --disable-tests          \
            --disable-static

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/{lib32,include}
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
cp -vr DESTDIR/usr/include/libunwind-x86.h $1/usr/include/
