#!/bin/sh -e

sed -i '/install -m.*STA/d' libcap/Makefile

mk() {
    make \
        GOLANG=no \
        PREFIX=/usr \
        SBINDIR=/usr/bin \
        LIBDIR=/usr/lib \
        PKGCONFIGDIR=/usr/lib/pkgconfig \
        RAISE_SETFCAP=no \
        INDENT=" " \
        "$@"
}

mk
mk DESTDIR="$1" install

if [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
make CC="gcc -m32 -march=i686"
make CC="gcc -m32 -march=i686" lib=lib32 prefix=$PWD/DESTDIR/usr -C libcap install
install -d $1/usr/lib32/pkgconfig
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
sed -e "s|^libdir=.*|libdir=/usr/lib32|" -i $1/usr/lib32/pkgconfig/lib{cap,psx}.pc
chmod -v 755 $1/usr/lib32/libcap.so.$2
fi
