#!/bin/sh -e

./autogen.sh
./configure --prefix=/usr --with-gtk3

make
make -j1 DESTDIR=$1 install

rm -rf $1/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/client.h
rm -rf $1/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/dbusmenu-glib.h
rm -rf $1/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/enum-types.h
rm -rf $1/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/menuitem.h
rm -rf $1/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/menuitem-proxy.h
rm -rf $1/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/server.h
rm -rf $1/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/types.h
rm -rf $1/usr/include/libdbusmenu-gtk3-0.4/libdbusmenu-gtk/client.h
rm -rf $1/usr/include/libdbusmenu-gtk3-0.4/libdbusmenu-gtk/dbusmenu-gtk.h
rm -rf $1/usr/include/libdbusmenu-gtk3-0.4/libdbusmenu-gtk/menu.h
rm -rf $1/usr/include/libdbusmenu-gtk3-0.4/libdbusmenu-gtk/menuitem.h
rm -rf $1/usr/include/libdbusmenu-gtk3-0.4/libdbusmenu-gtk/parser.h
rm -rf $1/usr/libexec/dbusmenu-bench
rm -rf $1/usr/lib/girepository-1.0/Dbusmenu-0.4.typelib
rm -rf $1/usr/lib/girepository-1.0/DbusmenuGtk3-0.4.typelib
rm -rf $1/usr/lib/libdbusmenu-glib.so
rm -rf $1/usr/lib/libdbusmenu-glib.so.4
rm -rf $1/usr/lib/libdbusmenu-glib.so.4.0.12
rm -rf $1/usr/lib/libdbusmenu-gtk3.so
rm -rf $1/usr/lib/libdbusmenu-gtk3.so.4
rm -rf $1/usr/lib/libdbusmenu-gtk3.so.4.0.12
rm -rf $1/usr/lib/pkgconfig/dbusmenu-glib-0.4.pc
rm -rf $1/usr/lib/pkgconfig/dbusmenu-gtk3-0.4.pc
rm -rf $1/usr/share/doc/libdbusmenu/README.dbusmenu-bench
rm -rf $1/usr/share/gir-1.0/Dbusmenu-0.4.gir
rm -rf $1/usr/share/gir-1.0/DbusmenuGtk3-0.4.gir
rm -rf $1/usr/share/vala/vapi/Dbusmenu-0.4.vapi
rm -rf $1/usr/share/vala/vapi/DbusmenuGtk3-0.4.vapi