#!/bin/sh -e

cmake -B build                            \
      -D CMAKE_INSTALL_PREFIX=/usr        \
      -D CMAKE_BUILD_TYPE=Release         \
      -D ENABLE_CXX11=ON                  \
      -D BUILD_PERF_TESTS=OFF             \
      -D WITH_XINE=ON                     \
      -D BUILD_TESTS=OFF                  \
      -D ENABLE_PRECOMPILED_HEADERS=OFF   \
      -D CMAKE_SKIP_INSTALL_RPATH=ON      \
      -D BUILD_WITH_DEBUG_INFO=OFF        \
      -D OPENCV_GENERATE_PKGCONFIG=ON     \
      -D CMAKE_POLICY_VERSION_MINIMUM=3.5 \
      -W no-dev

cmake --build build
DESTDIR=$1 cmake --install build
