#!/bin/sh -e

cmake -S . -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_INSTALL_LIBDIR=/usr/lib \
    -D BUILD_SHARED_LIBS=ON \
    -D CMAKE_POLICY_VERSION_MINIMUM=3.5
cmake --build build

DESTDIR=$1 cmake --install build
