#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Degl=yes \
    -Dtests=false \
    . output

ninja -C output
DESTDIR=$1 ninja -C output install
