#!/bin/sh -e

patch -Np1 -i libaom-$2-nasm3-1.patch

mkdir aom-build
cd    aom-build

cmake -D CMAKE_INSTALL_PREFIX=/usr \
      -D CMAKE_BUILD_TYPE=Release  \
      -D BUILD_SHARED_LIBS=1       \
      -D ENABLE_DOCS=no            \
      -D CMAKE_AR=$(which gcc-ar)  \
      -D CMAKE_RANLIB=$(which gcc-ranlib) \
      -D CMAKE_NM=$(which gcc-nm)  \
      -G Ninja ..

ninja
DESTDIR=$1 ninja install

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf *
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
cmake -D CMAKE_INSTALL_PREFIX=/usr   \
      -D CMAKE_INSTALL_LIBDIR=lib32  \
      -D CMAKE_BUILD_TYPE=Release    \
      -D BUILD_SHARED_LIBS=1         \
      -D ENABLE_DOCS=no              \
      -D CMAKE_AR=$(which gcc-ar)    \
      -D CMAKE_RANLIB=$(which gcc-ranlib) \
      -D CMAKE_NM=$(which gcc-nm)    \
      -G Ninja ..

ninja
DESTDIR=$PWD/DESTDIR ninja install
install -d $1/usr/lib32
cp -vR DESTDIR/usr/lib32/* $1/usr/lib32
fi
