#!/bin/bash -e

# A cross build installs into the target sysroot, never the host's /usr.
# CMAKE_INSTALL_LIBDIR must stay relative so CMake joins it with the prefix;
# an absolute value is taken verbatim and escapes the sysroot.

cmake -B aom-build                 \
      -D CMAKE_INSTALL_PREFIX="${CROSS_PREFIX:-/usr}" \
      -D CMAKE_INSTALL_LIBDIR=lib \
      -D CMAKE_BUILD_TYPE=Release  \
      -D BUILD_SHARED_LIBS=1       \
      -D ENABLE_DOCS=no            \
      -D CMAKE_AR=$(which gcc-ar)  \
      -D CMAKE_RANLIB=$(which gcc-ranlib) \
      -D CMAKE_NM=$(which gcc-nm)

cmake --build aom-build
DESTDIR=$1 cmake --install aom-build

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf aom-build
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
cmake -B aom-build                   \
      -D CMAKE_INSTALL_PREFIX=/usr   \
      -D CMAKE_INSTALL_LIBDIR=lib32  \
      -D CMAKE_BUILD_TYPE=Release    \
      -D BUILD_SHARED_LIBS=1         \
      -D ENABLE_DOCS=no              \
      -D CMAKE_AR=$(which gcc-ar)    \
      -D CMAKE_RANLIB=$(which gcc-ranlib) \
      -D CMAKE_NM=$(which gcc-nm)

cmake --build aom-build
DESTDIR=$PWD/DESTDIR cmake --install aom-build
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vR DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
