#!/bin/bash -e

export CFLAGS="$CFLAGS -Wno-error -static"

PREFIX="${CROSS_PREFIX:-/usr}"

# triplet for --host
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"

    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure \
    --prefix="$PREFIX" \
    --libdir="$PREFIX/lib" \
    --sysconfdir=/etc \
    --datarootdir="$PREFIX/share" \
    $CROSS_OPTS

make
make DESTDIR=$1 install
