#!/bin/sh -e

_DATE=$(git log -1 --pretty=%ct) # get commit date to make it REPRODUCABLE
_BUILDINFO="-X 'github.com/dundee/gdu/v5/build.Version=${2}' \
               -X 'github.com/dundee/gdu/v5/build.User=${PACKAGER}' \
               -X 'github.com/dundee/gdu/v5/build.Time=${_DATE}'"

go build \
  -buildmode=pie \
  -mod=readonly \
  -modcacherw \
  -pgo=default.pgo \
  -ldflags "-compressdwarf=false -linkmode external -extldflags \"${LDFLAGS}\" ${_BUILDINFO}" \
  -o dist/gdu \
  github.com/dundee/gdu/v5/cmd/gdu

install -Dm755 dist/${3} "${1}/usr/bin/${3}"
install -Dm644 gdu.1    "${1}/usr/share/man/man1/${3}.1"
