#!/bin/sh -e

go build \
  -buildmode=pie \
  -mod=readonly \
  -modcacherw \
  -pgo=default.pgo \
  -ldflags "-compressdwarf=false -linkmode external -extldflags \"${LDFLAGS}\" " \
  -o dist/gdu \
  github.com/dundee/gdu/v5/cmd/gdu

install -Dm755 dist/gdu "${1}/usr/bin/gdu"
install -Dm644 gdu.1    "${1}/usr/share/man/man1/gdu.1"
