#!/bin/sh -e

go build \
  -buildmode=pie \
  -mod=readonly \
  -modcacherw \
  -pgo=default.pgo \
  -ldflags "-compressdwarf=false -linkmode external -extldflags \"${LDFLAGS}\" " \
  -o dist/gdu \
  github.com/dundee/gdu/v5/cmd/gdu

install -Dm755 dist/${3} "${1}/usr/bin/${3}"
install -Dm644 gdu.1    "${1}/usr/share/man/man1/${3}.1"
