#!/bin/sh -e

patch -Np1 -i rpmlib-filesystem-check.patch

	./configure \
		--prefix=/usr  \
		--sysconfdir=/etc  \
		--localstatedir=/var \
		--enable-python \
		--with-external-db \
		--with-lua \
		--with-cap \
		CPPFLAGS="`pkg-config --cflags nss`" \
		PYTHON=python
make
make DESTDIR=$1 install
