#!/bin/sh -e

patch -Np1 -i fix-sequoia-off.patch

cmake -B builddir                 \
    -D WITH_AUDIT=OFF             \
    -D WITH_SELINUX=OFF           \
    -D WITH_SEQUOIA=OFF           \
    -D WITH_FAPOLICYD=OFF         \
    -D CMAKE_INSTALL_PREFIX=/usr  \
    -D CMAKE_BUILD_TYPE=Release

cmake --build builddir
DESTDIR=$1 cmake --install builddir
