#!/bin/sh -e

CPPFLAGS="-I/usr/include/tirpc"            \
LDFLAGS="-ltirpc"                          \
./configure                                \
    --prefix=/usr                          \
    --sysconfdir=/etc                      \
    --localstatedir=/var                   \
    --with-piddir=/run/samba               \
    --with-pammodulesdir=/usr/lib/security \
    --enable-fhs                           \
    --without-ldap			   \
    --without-ads                          \
    --without-ad-dc

make
make DESTDIR=$1 install

mkdir -pv $1/usr/lib/systemd/system/
mkdir -pv $1/usr/lib/tmpfiles.d/

install -m644 samba.conf $1/usr/lib/tmpfiles.d/
install -m644 nmbd.service $1/usr/lib/systemd/system/
install -m644 samba.service $1/usr/lib/systemd/system/
install -m644 smbd.service $1/usr/lib/systemd/system/
install -m644 smbdat.service $1/usr/lib/systemd/system/smbd@.service
install -m644 smbd.socket $1/usr/lib/systemd/system/
