#!/bin/bash -e

CPPFLAGS="-I/usr/include/tirpc"            \
LDFLAGS="-ltirpc"                          \
./configure                                \
    --prefix=/usr                          \
    --sysconfdir=/etc                      \
    --localstatedir=/var                   \
    --with-piddir=/run/samba               \
    --with-pammodulesdir=/usr/lib/security \
    --enable-fhs                           \
    --without-ldap			   \
    --without-ads                          \
    --without-ad-dc

make
make DESTDIR=$1 install

mkdir -pv $1/usr/lib/systemd/system/
mkdir -pv $1/usr/lib/tmpfiles.d/

install -m644 samba.conf $1/usr/lib/tmpfiles.d/
install -m644 nmbd.service $1/usr/lib/systemd/system/
install -m644 samba.service $1/usr/lib/systemd/system/
install -m644 smbd.service $1/usr/lib/systemd/system/
install -m644 smbdat.service $1/usr/lib/systemd/system/smbd@.service
install -m644 smbd.socket $1/usr/lib/systemd/system/

# smbclient split package

_pick "$1" smbclient usr/bin/net
_pick "$1" smbclient usr/bin/nmblookup
_pick "$1" smbclient usr/bin/rpcclient
_pick "$1" smbclient usr/bin/smbcacls
_pick "$1" smbclient usr/bin/smbclient
_pick "$1" smbclient usr/bin/smbcquotas
_pick "$1" smbclient usr/bin/smbget
_pick "$1" smbclient usr/bin/smbspool
_pick "$1" smbclient usr/bin/smbtar
_pick "$1" smbclient usr/bin/smbtree
_pick "$1" smbclient usr/include/samba-4.0/libsmbclient.h
_pick "$1" smbclient usr/include/samba-4.0/netapi.h
_pick "$1" smbclient usr/lib/cups/backend/smb
_pick "$1" smbclient usr/lib/libdcerpc-binding.*
_pick "$1" smbclient usr/lib/libdcerpc-samr.*
_pick "$1" smbclient usr/lib/libdcerpc-server-core.*
_pick "$1" smbclient usr/lib/libdcerpc-server.*
_pick "$1" smbclient usr/lib/libdcerpc.*
_pick "$1" smbclient usr/lib/libndr-krb5pac.*
_pick "$1" smbclient usr/lib/libndr-nbt.*
_pick "$1" smbclient usr/lib/libndr-standard.*
_pick "$1" smbclient usr/lib/libndr.*
_pick "$1" smbclient usr/lib/libnetapi.*
_pick "$1" smbclient usr/lib/libnss_winbind.so.*
_pick "$1" smbclient usr/lib/libnss_wins.so.*
_pick "$1" smbclient usr/lib/libsamba-credentials.*
_pick "$1" smbclient usr/lib/libsamba-errors.*
_pick "$1" smbclient usr/lib/libsamba-hostconfig.*
_pick "$1" smbclient usr/lib/libsamba-passdb.*
_pick "$1" smbclient usr/lib/libsamba-policy.*
_pick "$1" smbclient usr/lib/libsamba-util.*
_pick "$1" smbclient usr/lib/libsamdb.*
_pick "$1" smbclient usr/lib/libsmbclient.*
_pick "$1" smbclient usr/lib/libsmbconf.*
_pick "$1" smbclient usr/lib/libsmbldap.*
_pick "$1" smbclient usr/lib/libtevent-util.*
_pick "$1" smbclient usr/lib/pkgconfig/netapi.pc
_pick "$1" smbclient usr/lib/pkgconfig/smbclient.pc
_pick "$1" smbclient usr/lib/samba/libCHARSET3-private-samba.so
_pick "$1" smbclient usr/lib/samba/libHDB-SAMBA4-private-samba.so
_pick "$1" smbclient usr/lib/samba/libLIBWBCLIENT-OLD-private-samba.so
_pick "$1" smbclient usr/lib/samba/libMESSAGING-SEND-private-samba.so
_pick "$1" smbclient usr/lib/samba/libMESSAGING-private-samba.so
_pick "$1" smbclient usr/lib/samba/libREG-FULL-private-samba.so
_pick "$1" smbclient usr/lib/samba/libRPC-SERVER-LOOP-private-samba.so
_pick "$1" smbclient usr/lib/samba/libRPC-WORKER-private-samba.so
_pick "$1" smbclient usr/lib/samba/libad-claims-private-samba.so
_pick "$1" smbclient usr/lib/samba/libaddns-private-samba.so
_pick "$1" smbclient usr/lib/samba/libads-private-samba.so
_pick "$1" smbclient usr/lib/samba/libasn1-private-samba.so
_pick "$1" smbclient usr/lib/samba/libasn1util-private-samba.so
_pick "$1" smbclient usr/lib/samba/libauth-private-samba.so
_pick "$1" smbclient usr/lib/samba/libauth-unix-token-private-samba.so
_pick "$1" smbclient usr/lib/samba/libauth4-private-samba.so
_pick "$1" smbclient usr/lib/samba/libauthkrb5-private-samba.so
_pick "$1" smbclient usr/lib/samba/libauthn-policy-util-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcli-cldap-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcli-ldap-common-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcli-ldap-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcli-nbt-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcli-smb-common-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcli-spoolss-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcliauth-private-samba.so
_pick "$1" smbclient usr/lib/samba/libclidns-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcluster-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcmdline-contexts-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcmdline-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcmocka-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcom-err-private-samba.so
_pick "$1" smbclient usr/lib/samba/libcommon-auth-private-samba.so
_pick "$1" smbclient usr/lib/samba/libdb-glue-private-samba.so
_pick "$1" smbclient usr/lib/samba/libdbwrap-private-samba.so
_pick "$1" smbclient usr/lib/samba/libdcerpc-pkt-auth-private-samba.so
_pick "$1" smbclient usr/lib/samba/libdcerpc-samba-private-samba.so
_pick "$1" smbclient usr/lib/samba/libdcerpc-samba4-private-samba.so
_pick "$1" smbclient usr/lib/samba/libdfs-server-ad-private-samba.so
_pick "$1" smbclient usr/lib/samba/libdlz-bind9-for-torture-private-samba.so
_pick "$1" smbclient usr/lib/samba/libdnsserver-common-private-samba.so
_pick "$1" smbclient usr/lib/samba/libdsdb-garbage-collect-tombstones-private-samba.so
_pick "$1" smbclient usr/lib/samba/libdsdb-module-private-samba.so
_pick "$1" smbclient usr/lib/samba/libevents-private-samba.so
_pick "$1" smbclient usr/lib/samba/libflag-mapping-private-samba.so
_pick "$1" smbclient usr/lib/samba/libgenrand-private-samba.so
_pick "$1" smbclient usr/lib/samba/libgensec-private-samba.so
_pick "$1" smbclient usr/lib/samba/libgpext-private-samba.so
_pick "$1" smbclient usr/lib/samba/libgpo-private-samba.so
_pick "$1" smbclient usr/lib/samba/libgse-private-samba.so
_pick "$1" smbclient usr/lib/samba/libgss-preauth-private-samba.so
_pick "$1" smbclient usr/lib/samba/libgssapi-private-samba.so
_pick "$1" smbclient usr/lib/samba/libhcrypto-private-samba.so
_pick "$1" smbclient usr/lib/samba/libhdb-private-samba.so
_pick "$1" smbclient usr/lib/samba/libheimbase-private-samba.so
_pick "$1" smbclient usr/lib/samba/libheimntlm-private-samba.so
_pick "$1" smbclient usr/lib/samba/libhttp-private-samba.so
_pick "$1" smbclient usr/lib/samba/libhx509-private-samba.so
_pick "$1" smbclient usr/lib/samba/libidmap-private-samba.so
_pick "$1" smbclient usr/lib/samba/libinterfaces-private-samba.so
_pick "$1" smbclient usr/lib/samba/libiov-buf-private-samba.so
_pick "$1" smbclient usr/lib/samba/libkdc-private-samba.so
_pick "$1" smbclient usr/lib/samba/libkrb5-private-samba.so
_pick "$1" smbclient usr/lib/samba/libkrb5samba-private-samba.so
_pick "$1" smbclient usr/lib/samba/libldb-cmdline-private-samba.so
_pick "$1" smbclient usr/lib/samba/libldb-key-value-private-samba.so
_pick "$1" smbclient usr/lib/samba/libldb-mdb-int-private-samba.so
_pick "$1" smbclient usr/lib/samba/libldb-tdb-err-map-private-samba.so
_pick "$1" smbclient usr/lib/samba/libldb-tdb-int-private-samba.so
_pick "$1" smbclient usr/lib/samba/libldbsamba-private-samba.so
_pick "$1" smbclient usr/lib/samba/liblibcli-lsa3-private-samba.so
_pick "$1" smbclient usr/lib/samba/liblibcli-netlogon3-private-samba.so
_pick "$1" smbclient usr/lib/samba/liblibsmb-private-samba.so
_pick "$1" smbclient usr/lib/samba/libmessages-dgm-private-samba.so
_pick "$1" smbclient usr/lib/samba/libmessages-util-private-samba.so
_pick "$1" smbclient usr/lib/samba/libmscat-private-samba.so
_pick "$1" smbclient usr/lib/samba/libmsghdr-private-samba.so
_pick "$1" smbclient usr/lib/samba/libmsrpc3-private-samba.so
_pick "$1" smbclient usr/lib/samba/libndr-samba-private-samba.so
_pick "$1" smbclient usr/lib/samba/libndr-samba4-private-samba.so
_pick "$1" smbclient usr/lib/samba/libnet-keytab-private-samba.so
_pick "$1" smbclient usr/lib/samba/libnetif-private-samba.so
_pick "$1" smbclient usr/lib/samba/libnpa-tstream-private-samba.so
_pick "$1" smbclient usr/lib/samba/libnss-info-private-samba.so
_pick "$1" smbclient usr/lib/samba/libpac-private-samba.so
_pick "$1" smbclient usr/lib/samba/libposix-eadb-private-samba.so
_pick "$1" smbclient usr/lib/samba/libprinter-driver-private-samba.so
_pick "$1" smbclient usr/lib/samba/libprinting-migrate-private-samba.so
_pick "$1" smbclient usr/lib/samba/libprocess-model-private-samba.so
_pick "$1" smbclient usr/lib/samba/libpyldb-util.cpython-314-x86-64-linux-gnu-private-samba.so
_pick "$1" smbclient usr/lib/samba/libquic-private-samba.so
_pick "$1" smbclient usr/lib/samba/libregistry-private-samba.so
_pick "$1" smbclient usr/lib/samba/libreplace-private-samba.so
_pick "$1" smbclient usr/lib/samba/libroken-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamba-cluster-support-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamba-debug-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamba-modules-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamba-net-join.cpython-314-x86-64-linux-gnu-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamba-net-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamba-python.cpython-314-x86-64-linux-gnu-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamba-security-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamba-security-trusts-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamba-sockets-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamba3-util-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsamdb-common-private-samba.so
_pick "$1" smbclient usr/lib/samba/libscavenge-dns-records-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsecrets3-private-samba.so
_pick "$1" smbclient usr/lib/samba/libserver-id-db-private-samba.so
_pick "$1" smbclient usr/lib/samba/libserver-role-private-samba.so
_pick "$1" smbclient usr/lib/samba/libservice-private-samba.so
_pick "$1" smbclient usr/lib/samba/libshares-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsmbclient-raw-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsmbd-base-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsmbd-shim-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsmbldaphelper-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsmbpasswdparser-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsocket-blocking-private-samba.so
_pick "$1" smbclient usr/lib/samba/libstable-sort-private-samba.so
_pick "$1" smbclient usr/lib/samba/libsys-rw-private-samba.so
_pick "$1" smbclient usr/lib/samba/libtalloc-report-printf-private-samba.so
_pick "$1" smbclient usr/lib/samba/libtalloc-report-private-samba.so
_pick "$1" smbclient usr/lib/samba/libtdb-wrap-private-samba.so
_pick "$1" smbclient usr/lib/samba/libtime-basic-private-samba.so
_pick "$1" smbclient usr/lib/samba/libtorture-private-samba.so
_pick "$1" smbclient usr/lib/samba/libutil-crypt-private-samba.so
_pick "$1" smbclient usr/lib/samba/libutil-reg-private-samba.so
_pick "$1" smbclient usr/lib/samba/libutil-setid-private-samba.so
_pick "$1" smbclient usr/lib/samba/libutil-tdb-private-samba.so
_pick "$1" smbclient usr/lib/samba/libwind-private-samba.so
_pick "$1" smbclient usr/lib/samba/libxattr-tdb-private-samba.so
_pick "$1" smbclient usr/share/man/man1/nmblookup.1.gz
_pick "$1" smbclient usr/share/man/man1/rpcclient.1.gz
_pick "$1" smbclient usr/share/man/man1/smbcacls.1.gz
_pick "$1" smbclient usr/share/man/man1/smbclient.1.gz
_pick "$1" smbclient usr/share/man/man1/smbcquotas.1.gz
_pick "$1" smbclient usr/share/man/man1/smbget.1.gz
_pick "$1" smbclient usr/share/man/man1/smbtar.1.gz
_pick "$1" smbclient usr/share/man/man1/smbtree.1.gz
_pick "$1" smbclient usr/share/man/man7/libsmbclient.7.gz
_pick "$1" smbclient usr/share/man/man8/net.8.gz
_pick "$1" smbclient usr/share/man/man8/smbspool.8.gz

# libwbclient split package

_pick "$1" libwbclient usr/include/samba-4.0/wbclient.h
_pick "$1" libwbclient usr/lib/libwbclient.*
_pick "$1" libwbclient usr/lib/pkgconfig/wbclient.pc
