#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    cmake -B build \
        -D CMAKE_SYSTEM_NAME=Linux \
        -D CMAKE_SYSTEM_PROCESSOR=aarch64 \
        -D CMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
        -D CMAKE_INSTALL_PREFIX=/usr/aarch64-linux-gnu \
        -D ZLIB_COMPAT=ON \
        -D ZLIB_ENABLE_TESTS=OFF
    cd build
else
    # Detection logic for CPUFLAGS
    CONF_ARGS="--prefix=/usr --zlib-compat"
    case "$CPUFLAGS" in
        *avx2*)   CONF_ARGS="$CONF_ARGS --x86-avx2" ;;
        *sse4_2*) CONF_ARGS="$CONF_ARGS --x86-sse42" ;;
        *neon*)   CONF_ARGS="$CONF_ARGS --arm-neon" ;;
    esac
    ./configure $CONF_ARGS
fi
make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit zlib
make distclean
CFLAGS+=" -m32" CXXFLAGS+=" -m32" \
./configure --prefix=/usr \
    --zlib-compat         \
    --libdir=/usr/lib32
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32/
fi
