#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    cmake -B build \
        -D CMAKE_SYSTEM_NAME=Linux \
        -D CMAKE_SYSTEM_PROCESSOR=aarch64 \
        -D CMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
        -D CMAKE_INSTALL_PREFIX=$CROSS_PREFIX \
        -D ZLIB_COMPAT=ON \
        -D ZLIB_ENABLE_TESTS=OFF
    cd build
else
    CONF_ARGS="--prefix=/usr --zlib-compat"
    ./configure $CONF_ARGS
fi
make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit zlib
make distclean
CFLAGS+=" -m32" CXXFLAGS+=" -m32" \
./configure --prefix=/usr \
    --zlib-compat         \
    --libdir=/usr/lib32
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32/
fi
