#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # gobject-introspection scans the just-built library, and the sysroot's
    # GLib has no .gir.
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu" --disable-introspection)
fi

./configure --prefix="$PREFIX" "${CROSS_OPTS[@]}"

make
make DESTDIR=$1 install
