#!/bin/sh -e

mkdir -v gcc-build
cd gcc-build

echo "slibdir=/usr/lib" >> configparms
echo "rtlddir=/usr/lib" >> configparms
echo "sbindir=/usr/bin" >> configparms
echo "rootsbindir=/usr/bin" >> configparms

../configure --prefix=/usr \
    --disable-werror \
    --enable-kernel=6.8 \
    --enable-stack-protector=strong \
    --libdir=/usr/lib \
    --libexecdir=/usr/lib \
    --with-headers=/usr/include \
    --disable-nscd \
    libc_cv_slibdir=/lib

make
make DESTDIR="$1" install
make DESTDIR="$1" localedata/install-locales
rm -rf $1/usr/share/info 

cd ..

mkdir -pv "$1"/etc
mkdir -pv "$1"/var/cache/nscd
cp -v nsswitch.conf "$1"/etc/nsswitch.conf
cp -v ld.so.conf "$1"/etc/ld.so.conf
