#!/bin/sh -e

cmake -B build -D CMAKE_INSTALL_PREFIX=/usr \
      -D CMAKE_POLICY_VERSION_MINIMUM=3.5   \
      -D BUILD_SHARED_LIBS=ON               \
      -D BUILD_TESTING=ON

cmake --build build
DESTDIR=$1 cmake --install build
