#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

cmake -B build -G Ninja \
      -D CMAKE_INSTALL_PREFIX="$PREFIX" \
      -D ENABLE_THUMBNAILER=ON

cmake --build build
DESTDIR=$1 cmake --install build
