#!/bin/sh -e

DESTDIR=build zig build \
  --summary all \
  --prefix "/usr" \
  -Doptimize=ReleaseFast \
  -Dgtk-x11=true \
  -Dcpu=baseline \
  -Dpie=true \
  -Dversion-string="$2-sauzerOS"

cp -a build/* "$1/"
