#!/bin/sh -e

# fix bug
patch -Np1 -i 0001-Fix-a-null-pointer-dereference-when-computing-a-patt.patch

meson setup build \
  --prefix=/usr   \
  --buildtype=release

meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
meson setup build               \
            --prefix=/usr       \
            --libdir=/usr/lib32 \
            --cross-file=lib32  \
            --buildtype=release \

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
fi
