#!/bin/sh -e

mkdir build
cd    build

meson setup --prefix=/usr --buildtype=release ..
ninja
DESTDIR=$1 ninja install

#32bit

rm -rf *
meson setup --prefix=/usr       \
            --libdir=/usr/lib32 \
            --cross-file=lib32  \
            --buildtype=release \
            ..

ninja
DESTDIR=$PWD/DESTDIR ninja install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32
