#!/bin/bash -e

patch -Np1 -i 7d13bb959c7b55bbaebdc09b7e71311e0cf78f77.patch
patch -Np1 -i fontconfig-2.18.2-cache11.patch

hokuto-meson build
meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf build

hokuto-meson-32 build
meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
