#!/bin/sh -e

CONF_ARGS="--prefix=$CROSS_PREFIX \
           --disable-static  \
           --enable-lib-only"

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CONF_ARGS="$CONF_ARGS --host=$HOKUTO_ARCH-linux-gnu"
fi

./configure $CONF_ARGS

make
make DESTDIR=$1 install
