#!/bin/bash -e

patch -Np1 -i 0001-Use-importlib-instead-of-pkg_resources-on-recent-pyt.patch
# PyWeakref_GetObject was removed in python 3.15.
patch -Np1 -i 0002-PyWeakref_GetObject-python-3.15.patch
python -m build --wheel --no-isolation
python -m installer --destdir="${1}" dist/*.whl
