#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
fi

./autogen.sh
./configure --prefix="$PREFIX" \
    --disable-static \
    "${CROSS_OPTS[@]}"

make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make distclean
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
export CC='gcc -m32'
export CXX='g++ -m32'
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config

./configure \
  --prefix=/usr \
  --libdir=/usr/lib32 \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --disable-examples
 
make
make DESTDIR="$pkgdir" install
rm -r "$pkgdir"/usr/{include,share}
fi
