#!/bin/bash -e

./autogen.sh
./configure --prefix=/usr \
    --disable-static

make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make distclean
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
export CC='gcc -m32'
export CXX='g++ -m32'
export PKG_CONFIG=i686-pc-linux-gnu-pkg-config

./configure \
  --prefix=/usr \
  --libdir=/usr/lib32 \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --disable-examples
 
make
make DESTDIR="$pkgdir" install
rm -r "$pkgdir"/usr/{include,share}
fi
