#!/bin/bash -e

# Use CROSS_PREFIX if set (defaults to /usr in hokuto)
PREFIX="${CROSS_PREFIX:-/usr}"
SYSCONF_DIR="${PREFIX}/etc"
LOCALSTATE_DIR="${PREFIX}/var"

[ "$PREFIX" = "/usr" ] && SYSCONF_DIR="/etc" && LOCALSTATE_DIR="/var"

# enable man-pages if docbook-xsl is installed
hokuto check docbook-xsl && manvalue="enabled" || manvalue="disabled"

MESON_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    if [ "$PREFIX" = "/usr" ]; then
        MESON_OPTS+=(
            --cross-file "${HOKUTO_ARCH}"
            -Dgnutls=disabled
            -Dqrencode=disabled
        )
    else
        MESON_OPTS+=(--cross-file "$HOKUTO_ARCH")
        if [ "$PREFIX" != "/usr" ]; then
            export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PREFIX/share/pkgconfig"
        fi

        if ! hokuto check "${HOKUTO_ARCH}-cryptsetup"; then
        MESON_OPTS+=("-Dlibcryptsetup=disabled")
        fi

        if ! hokuto check "${HOKUTO_ARCH}-gnutls"; then
        MESON_OPTS+=("-Dgnutls=disabled")
        fi
        MESON_OPTS+=("-Dqrencode=disabled")
    fi
fi

LANG=en_US.UTF-8 \
meson setup build                  \
      --prefix="$PREFIX"           \
      --sysconfdir="$SYSCONF_DIR"   \
      --localstatedir="$LOCALSTATE_DIR" \
      "${MESON_OPTS[@]}"                  \
      -D blkid=enabled              \
      -D buildtype=release          \
      -D default-dnssec=no          \
      -D default-kill-user-processes=false \
      -D default-dns-over-tls=yes   \
      -D firstboot=false            \
      -D install-tests=false        \
      -D ldconfig=false             \
      -D libidn2=enabled            \
      -D sysusers=true              \
      -D b_lto=true                 \
      -D homed=disabled             \
      -D userdb=false               \
      -D dns-servers=""             \
      -D mode=release               \
      -D man=$manvalue              \
      -D oomd=true                  \
      -D pamconfdir="$SYSCONF_DIR/pam.d" \
      -D bootloader=enabled         \
      -D sbat-distro-url="https://sauzeros.github.io"

LANG=en_US.UTF-8 meson compile -C build
LANG=en_US.UTF-8 meson install -C build --destdir=$1

# Fix incorrect paths from cross-compilation
if [ "${HOKUTO_CROSS:-0}" = "1" ] && [ "$PREFIX" = "/usr" ]; then
    if [ -d "$1$PREFIX/$HOKUTO_ARCH-linux-gnu" ]; then
        echo "Moving files from sysroot $1$PREFIX/$HOKUTO_ARCH-linux-gnu to $1$PREFIX"
        cp -rl "$1$PREFIX/$HOKUTO_ARCH-linux-gnu/"* "$1$PREFIX/"
        rm -rf "$1$PREFIX/$HOKUTO_ARCH-linux-gnu"
    fi
fi

if [ "$PREFIX" = "/usr" ]; then
# overwrite the systemd-user PAM configuration with our own
install -D -m0644 systemd-user.pam "$1/lib/pam.d/systemd-user"
# install custom config files
install -v -m755 -d "$1/etc/systemd/network"
install -v -m644 20-wired.network "$1/etc/systemd/network/20-wired.network"
install -v -m644 25-wireless.network "$1/etc/systemd/network/25-wireless.network"
install -v -m755 -d "$1/etc/systemd/resolved.conf.d"
install -v -m644 dns_servers.conf "$1/etc/systemd/resolved.conf.d/dns_servers.conf"
install -v -m644 10-sauzeros.conf "$1/usr/lib/sysctl.d/10-sauzeros.conf"
fi

# systemd-libs
_pick "$1" systemd-libs usr/include/libudev.h
_pick "$1" systemd-libs usr/include/systemd/_sd-common.h
_pick "$1" systemd-libs usr/include/systemd/sd-*
_pick "$1" systemd-libs usr/lib/libnss_*
_pick "$1" systemd-libs usr/lib/libsystemd.so*
_pick "$1" systemd-libs usr/lib/libudev.so*
_pick "$1" systemd-libs usr/lib/pkgconfig/libsystemd.pc
_pick "$1" systemd-libs usr/lib/pkgconfig/libudev.pc
_pick "$1" systemd-libs usr/share/man/man3/SD_*
_pick "$1" systemd-libs usr/share/man/man3/libsystemd.3.gz
_pick "$1" systemd-libs usr/share/man/man3/libudev.3.gz
_pick "$1" systemd-libs usr/share/man/man3/sd-*
_pick "$1" systemd-libs usr/share/man/man3/sd_*

# systemd-resolvconf
pkgdir=$HOKUTO_SPLIT_DIR/systemd-resolvconf
install -d $pkgdir
install -d -m0755 "$pkgdir"/usr/bin
install -d -m0755 "$pkgdir"/usr/share/man/man1
ln -s resolvectl "$pkgdir"/usr/bin/resolvconf
ln -s resolvectl.1.gz "$pkgdir"/usr/share/man/man1/resolvconf.1.gz

# systemd-ukify
_pick "$1" systemd-ukify usr/bin/ukify systemd-ukify/bin/
_pick "$1" systemd-ukify usr/lib/systemd/ukify systemd-ukify/systemd/
_pick "$1" systemd-ukify usr/share/man/man1/ukify.1 systemd-ukify/man1/
_pick "$1" systemd-ukify usr/lib/kernel/install.d/60-ukify.install

if [ "$PREFIX" != "/usr" ]; then
# remove conflicting files
rm -rf $1/etc
fi

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf build
meson setup build                    \
      --cross-file lib32             \
      --prefix=/usr                  \
      --libdir=/usr/lib32            \
      --buildtype=release            \
      -D default-dnssec=no           \
      -D firstboot=false             \
      -D install-tests=false         \
      -D ldconfig=false              \
      -D sysusers=true               \
      -D rpmmacrosdir=no             \
      -D homed=disabled              \
      -D userdb=false                \
      -D man=disabled                \
      -D sbat-distro-url="https://sauzeros.github.io" \
      -D mode=release

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32/pkgconfig
cp -vR DESTDIR/usr/lib32/security       $dest_dir/usr/lib32
cp -va DESTDIR/usr/lib32/libsystemd.so* $dest_dir/usr/lib32
cp -va DESTDIR/usr/lib32/libudev.so*    $dest_dir/usr/lib32
cp -v  DESTDIR/usr/lib32/pkgconfig/*    $dest_dir/usr/lib32/pkgconfig
fi
