#!/bin/bash -e

meson setup build        \
    --prefix=/usr        \
    -D udev=true         \
    -D tests=false       \
    -D valgrind=disabled

meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit split package
rm -rf build
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
meson setup build                    \
            --prefix=/usr            \
            --buildtype=release      \
            --libdir=/usr/lib32      \
            -D tests=false           \
            -D udev=true             \
            -D valgrind=disabled

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
dest_dir=$HOKUTO_SPLIT_DIR/lib32-$3
install -d "$dest_dir/usr/lib32"
install -d $dest_dir/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
