#!/bin/sh -e

if hokuto list cmake; then
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_USE_SYSTEM_CURL=True \
        -DCMAKE_USE_SYSTEM_EXPAT=True \
        -DCMAKE_USE_SYSTEM_ZLIB=True \
        -DCMAKE_USE_SYSTEM_BZIP2=True \
        -DCMAKE_AR=$(which gcc-ar) \
        -DCMAKE_RANLIB=$(which gcc-ranlib) \
        -DCMAKE_NM=$(which gcc-nm) \
        -DBUILD_TESTING=OFF

    cmake --build   build
DESTDIR=$1 cmake --install build

else

        ./configure \
        --prefix=/usr \
        --system-curl \
        --system-expat \
        --system-zlib \
        --system-bzip2

    make
    make DESTDIR=$1 install
fi

rm -rf \
    "$1/usr/doc" \
    "$1/usr/share/cmake"*/Help \
    "$1/usr/share/bash-completion"
