#!/bin/sh -e
_build_copts='-DHAVE_DNSSEC -DHAVE_DBUS -DHAVE_NFTSET'

  make \
    CFLAGS="$CPPFLAGS $CFLAGS" \
    LDFLAGS="$LDFLAGS" \
    COPTS="$_build_copts" \
    PREFIX=/usr \
    BINDIR=/usr/bin \
    all-i18n

  cd "contrib/lease-tools"

  make \
    CFLAGS="$CPPFLAGS $CFLAGS" \
    LDFLAGS="$LDFLAGS" \
    COPTS="$_build_copts" \
    all
  cd ../..
  # need to pass COPTS here to avoid rebuilding the binary.
  make \
    COPTS="$_build_copts" \
    PREFIX=/usr \
    BINDIR=/usr/bin \
    DESTDIR="$1" \
    install-i18n

  install -Dm0644 "dbus/dnsmasq.conf" "$1"/usr/share/dbus-1/system.d/dnsmasq.conf
  install -Dm0644 "dnsmasq.conf.example" "$1"/etc/dnsmasq.conf
  install -Dm0644 dnsmasq.service "$1"/usr/lib/systemd/system/dnsmasq.service
  install -Dm0644 dnsmasq.sysusers "$1"/usr/lib/sysusers.d/dnsmasq.conf

  # DNSSEC setup
  sed -i 's,%%PREFIX%%,/usr,' "$1"/etc/dnsmasq.conf
  install -Dm0644 "trust-anchors.conf" "$1"/usr/share/dnsmasq/trust-anchors.conf

  install -Dm0755 -t "$1"/usr/bin/ 'contrib/lease-tools/dhcp_'{release{,6},lease_time}
  install -Dm0644 -t "$1"/usr/share/man/man1 'contrib/lease-tools/dhcp_'{release{,6},lease_time}.1
