#!/bin/sh -e

./configure --prefix=/usr           \
            --sysconfdir=/etc       \
            --with-initscriptdir=no \
            --with-libsystemd=yes   \
            --docdir=/usr/share/doc/smartmontools-$2

make
make DESTDIR=$1 install
