#!/bin/sh -e

./configure \
   --prefix=/usr \
   --localstatedir=/var/lib/vim \
   --with-features=huge \
   --with-compiledby='sauzerOS' \
   --with-wayland=no \
   --enable-acl \
   --with-x=no \
   --disable-gui \
   --enable-multibyte \
   --enable-perlinterp=dynamic \
   --enable-python3interp=dynamic \
   --enable-rubyinterp=dynamic \
   --enable-luainterp=dynamic \
   --enable-tclinterp=dynamic \
   --disable-canberra

make
make DESTDIR=$1 install


