#!/bin/sh -e

mkdir build
cd    build

meson --prefix=/usr       \
      --buildtype=release \
      -Ddatabase=gdbm     \
      -Ddoxygen=false     \
      -Dtests=false       \
      -Dbluez5=disabled
ninja
DESTDIR=$1 ninja install

# Remove systemwide conf
rm -f "$1/etc/dbus-1/system.d/pulseaudio-system.conf"
