#!/bin/sh -e
set +h
umask 022

sed 's/\[\[__nodiscard__]]//' -i lib/config.hin

./configure --prefix=/usr   \
            --host=$LFS_TGT \
            --build=$(build-aux/config.guess)
make
make DESTDIR=$LFS install
