#!/bin/sh -e

./autogen.sh
./configure --prefix=/usr \
            --enable-sdl2 \
            --enable-avcodec \
            --enable-core-inline

#make -j$(($(nproc)+2))
make
make DESTDIR="$1" install

