#!/bin/sh -e

mkdir build
cd    build

meson setup --prefix=/usr          \
            --buildtype=release    \
            --wrap-mode=nofallback \
            ..
ninja
DESTDIR=$1 ninja -j1 install
