timeout: 5
default_entry: 3
remember_last_entry: yes
wallpaper: boot():/EFI/limine/splash.jpg
interface_resolution: 2560x1440
interface_help_hidden
term_font_scale: 2x2
interface_branding: sauzerOS
interface_branding_color: 3
term_foreground: FAE309
term_foreground_bright: FFC300
term_margin: 1
term_margin_gradient: 0

/UEFI Shell
    protocol: efi
    image_path: boot():/EFI/tools/shell.efi

/UEFI Shell (minimal)
    protocol: efi
    image_path: boot():/EFI/tools/shellm.efi
