#!/bin/sh -e

cmake -B build \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_INSTALL_LIBDIR=lib \
    -D WITH_XC_UPDATECHECK=OFF \
    -D WITH_GUI_TESTS=OFF \
    -D WITH_XC_DOCS=OFF \
    -D WITH_XC_NETWORKING=OFF \
    -D WITH_XC_SSHAGENT=ON \
    -D WITH_XC_BROWSER=ON \
    -D WITH_QT6=ON \
    -D WITH_QT5=OFF \
    -D WITH_TESTS=OFF \
    -D CMAKE_AR=$(which gcc-ar) \
    -D CMAKE_RANLIB=$(which gcc-ranlib) \
    -D CMAKE_NM=$(which gcc-nm)


cmake --build   build
DESTDIR=$1 cmake --install build

#install -Dm644 org.keepassxc.KeePassXC.desktop $1/usr/share/applications/
