#!/bin/sh -e

export DESTDIR="$1"

patch -Np1 -i keepassxc-2.7.10-qt6-support-v2.patch

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DWITH_XC_UPDATECHECK=OFF \
    -DWITH_GUI_TESTS=OFF \
    -DWITH_XC_DOCS=OFF \
    -DWITH_XC_NETWORKING=OFF \
    -DWITH_XC_SSHAGENT=ON \
    -DWITH_XC_BROWSER=ON \
    -DWITH_QT6=ON \
    -DWITH_QT5=OFF \
    -DWITH_TESTS=OFF


cmake --build   build
cmake --install build

#install -Dm644 org.keepassxc.KeePassXC.desktop $1/usr/share/applications/
