#!/bin/sh -e

#echo "BUILD AS ROOT"

sed -i '/^udev/,$ s/^/#/' util/meson.build
mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..
ninja
DESTDIR=$1 ninja install

rm -rf $1/dev
rm -rf $1/etc/init.d

#fusermount needs +s to work
chmod +s $1/usr/bin/fusermount3
