#!/bin/sh -e

sed -i '/^udev/,$ s/^/#/' util/meson.build

meson setup build --prefix=/usr \
    --buildtype=release
meson compile -C build
meson install -C build --destdir=$1

rm -rf $1/dev
rm -rf $1/etc/init.d

#fusermount needs +s to work
chmod +s $1/usr/bin/fusermount3
#symlink
ln -s fusermount3 $1/usr/bin/fusermount
