#!/bin/sh -e

sed '20,$ d' -i trust/trust-extract-compat

cat >> trust/trust-extract-compat << "EOF"
# Copy existing anchor modifications to /etc/ssl/local
/usr/libexec/make-ca/copy-trust-modifications

# Update trust stores
/usr/sbin/make-ca -r
EOF

PREFIX="${CROSS_PREFIX:-/usr}"

meson_options=(
      --prefix="$PREFIX"       \
      --buildtype=release \
      -D trust_paths=/etc/pki/anchors
)

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    if [ "$PREFIX" = "/usr" ]; then
        meson_options+=(
           --cross-file "${HOKUTO_ARCH}"
        )
    else
        meson_options+=(--cross-file "$HOKUTO_ARCH")
    fi
fi

meson setup p11-build "${meson_options[@]}"

meson compile -C p11-build
DESTDIR=$1 meson install -C p11-build

# Fix incorrect paths from cross-compilation
if [ "${HOKUTO_CROSS:-0}" = "1" ] && [ "$PREFIX" = "/usr" ]; then
    if [ -d "$1$PREFIX/$HOKUTO_ARCH-linux-gnu" ]; then
        echo "Moving files from sysroot $1$PREFIX/$HOKUTO_ARCH-linux-gnu to $1$PREFIX"
        cp -rl "$1$PREFIX/$HOKUTO_ARCH-linux-gnu/"* "$1$PREFIX/"
        rm -rf "$1$PREFIX/$HOKUTO_ARCH-linux-gnu"
    fi
fi

ln -sfv "$PREFIX/libexec/p11-kit/trust-extract-compat" \
        "$1$PREFIX/bin/update-ca-certificates"

ln -sfv ./pkcs11/p11-kit-trust.so "$1$PREFIX/lib/libnssckbi.so"


