#!/bin/sh -e

sed '20,$ d' -i trust/trust-extract-compat

cat >> trust/trust-extract-compat << "EOF"
# Copy existing anchor modifications to /etc/ssl/local
/usr/libexec/make-ca/copy-trust-modifications

# Update trust stores
/usr/sbin/make-ca -r
EOF

PREFIX="${CROSS_PREFIX:-/usr}"

meson_options=(
      --prefix="$PREFIX"       \
      --buildtype=release \
      -D trust_paths=/etc/pki/anchors
)

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    meson_options+=(--cross-file "$HOKUTO_ARCH")
fi

meson setup p11-build "${meson_options[@]}"

meson compile -C p11-build
DESTDIR=$1 meson install -C p11-build

ln -sfv "$PREFIX/libexec/p11-kit/trust-extract-compat" \
        "$1$PREFIX/bin/update-ca-certificates"

ln -sfv ./pkcs11/p11-kit-trust.so "$1$PREFIX/lib/libnssckbi.so"


