#!/bin/sh -e

make PREFIX=/usr PARSER_URL=https://github.com/tree-sitter/tree-sitter-bash

install -d "${1}"/usr/lib/tree_sitter
  ln -s /usr/lib/lib${3}.so \
    "${1}"/usr/lib/tree_sitter/bash.so

make DESTDIR="${1}" PREFIX=/usr install
