#!/bin/bash -e

install -dm755 "$1/opt/Antigravity"
cp -a * "$1/opt/Antigravity/"

install -dm755 "$1/usr/bin"
install -Dm755 antigravity-ide.sh "$1/usr/bin/antigravity-ide"

install -Dm644 antigravity-ide.desktop \
  "$1/usr/share/applications/antigravity-ide.desktop"
install -Dm644 antigravity-url-handler.desktop \
  "$1/usr/share/applications/antigravity-url-handler.desktop"

install -dm755 "$1/usr/share/pixmaps"
ln -s /opt/Antigravity/resources/app/resources/linux/code.png \
  "$1/usr/share/pixmaps/antigravity.png"
