#!/bin/sh -e

#gcc 15 fix
sed -i '/output.h/i #include <cstdint>' src/woff2_out.cc


cmake -B build                            \
      -D CMAKE_INSTALL_PREFIX=/usr        \
      -D CMAKE_BUILD_TYPE=Release         \
      -D CMAKE_POLICY_VERSION_MINIMUM=3.5 \
      -D CMAKE_SKIP_INSTALL_RPATH=ON

cmake --build build
DESTDIR=$1 cmake --install build
