#!/bin/sh -e

sed -i 's/-Werror=/-W/g;s/-Werror//g' CMakeLists.txt

cmake -B build                       \
    -D CMAKE_INSTALL_PREFIX=/usr     \
    -D FLATBUFFERS_BUILD_FLATLIB=OFF \
    -D FLATBUFFERS_BUILD_SHAREDLIB=ON

cmake --build build
DESTDIR=$1 cmake --install build
