#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure         \
  --prefix=$PREFIX  \
  --sysconfdir=/etc \
  $CROSS_OPTS

make
make DESTDIR=$1 install

# bash-completion is sourced in /etc/bash.bashrc so that non-bash shell don't source it
rm "${1}/etc/profile.d/bash_completion.sh"
