#!/bin/bash -e

./configure --prefix=/usr \
  --sysconfdir=/etc

make
make DESTDIR=$1 install

# bash-completion is sourced in /etc/bash.bashrc so that non-bash shell don't source it
rm "${1}/etc/profile.d/bash_completion.sh"
