#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
SYSCONFDIR=/etc
CROSS_OPTS=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS+=(--host="$HOKUTO_ARCH-linux-gnu")
    [ "$PREFIX" != /usr ] && SYSCONFDIR="$PREFIX/etc"
fi

./configure --prefix="$PREFIX"         \
            --sysconfdir="$SYSCONFDIR" \
            --localstatedir=/var       \
            --disable-static "${CROSS_OPTS[@]}"

make
make DESTDIR=$1 install
