#!/bin/bash -e

destdir=$1
pkgver=$2
pkgname=$3
headersdir=$HOKUTO_SPLIT_DIR/linux-headers

# apply config
zcat config.gz > .config
make olddefconfig

# patch umip default value
patch -Np0 -i umip-dummy-limit.patch

#while true; do
#    read -p "Save updated kernel config to repo package? [yes/no]: " answer
#    case "${answer,,}" in
#        yes)
#           gzip -c .config > "/repo/sauzeros/core/$pkgname/files/config.gz"
#            echo "Kernel config saved to repo package."
#            break
#            ;;
#        no)
#            echo "Skipping kernel config save."
#            break
#            ;;
#        *)
#            echo "Please type 'yes' or 'no'."
#            ;;
#    esac
#done

make all
make -C tools/bpf/bpftool vmlinux.h feature-clang-bpf-co-re=1

krel=$(make -s kernelrelease)
echo "Kernel release: $krel"

# install kernel with versioned boot artifacts so multiple kernels can coexist
install -d "$destdir/boot"
install -Dm644 arch/x86/boot/bzImage "$destdir/boot/vmlinuz-$krel"
install -Dm644 System.map "$destdir/boot/System.map-$krel"
install -Dm644 .config "$destdir/boot/config-$krel"

# install modules
ZSTD_CLEVEL=19 make INSTALL_MOD_PATH="$destdir/usr" INSTALL_MOD_STRIP=1 \
    DEPMOD=/doesnt/exist modules_install

# remove build link from the kernel package; linux-headers owns the build tree
rm -f "$destdir/usr/lib/modules/$krel/build"

# install headers into split package
builddir="$headersdir/usr/lib/modules/$krel/build"
install -d "$builddir"

install -Dt "$builddir" -m644 .config Makefile Module.symvers System.map \
  vmlinux tools/bpf/bpftool/vmlinux.h
install -Dt "$builddir/kernel" -m644 kernel/Makefile
install -Dt "$builddir/arch/x86" -m644 arch/x86/Makefile
cp -t "$builddir" -a scripts
ln -srt "$builddir" "$builddir/scripts/gdb/vmlinux-gdb.py"

# required when STACK_VALIDATION is enabled
install -Dt "$builddir/tools/objtool" tools/objtool/objtool

# required when DEBUG_INFO_BTF_MODULES is enabled
install -Dt "$builddir/tools/bpf/resolve_btfids" tools/bpf/resolve_btfids/resolve_btfids

echo "Installing headers"
cp -t "$builddir" -a include
cp -t "$builddir/arch/x86" -a arch/x86/include
install -Dt "$builddir/arch/x86/kernel" -m644 arch/x86/kernel/asm-offsets.s

install -Dt "$builddir/drivers/md" -m644 drivers/md/*.h
install -Dt "$builddir/net/mac80211" -m644 net/mac80211/*.h

# https://bugs.archlinux.org/task/13146
install -Dt "$builddir/drivers/media/i2c" -m644 drivers/media/i2c/msp3400-driver.h

# https://bugs.archlinux.org/task/20402
install -Dt "$builddir/drivers/media/usb/dvb-usb" -m644 drivers/media/usb/dvb-usb/*.h
install -Dt "$builddir/drivers/media/dvb-frontends" -m644 drivers/media/dvb-frontends/*.h
install -Dt "$builddir/drivers/media/tuners" -m644 drivers/media/tuners/*.h

# https://bugs.archlinux.org/task/71392
install -Dt "$builddir/drivers/iio/common/hid-sensors" -m644 drivers/iio/common/hid-sensors/*.h

echo "Installing KConfig files"
find . -name 'Kconfig*' -exec install -Dm644 {} "$builddir/{}" \;

echo "Installing Rust files"
install -Dt "$builddir/rust" -m644 rust/*.rmeta || true
install -Dt "$builddir/rust" rust/*.so || true

echo "Installing unstripped VDSO"
make INSTALL_MOD_PATH="$headersdir/usr" vdso_install link=

echo "Removing unneeded architectures"
for arch in "$builddir"/arch/*/; do
    [[ $arch = */x86/ ]] && continue
    echo "Removing $(basename "$arch")"
    rm -r "$arch"
done

echo "Removing documentation"
rm -rf "$builddir/Documentation"

echo "Removing broken symlinks"
find -L "$builddir" -type l -printf 'Removing %P\n' -delete

echo "Removing loose objects"
find "$builddir" -type f -name '*.o' -printf 'Removing %P\n' -delete

echo "Stripping build tools"
while IFS= read -r -d '' file; do
    case "$(file -Sib "$file")" in
      application/x-sharedlib\;*)      strip -v $STRIP_SHARED "$file" ;;
      application/x-archive\;*)        strip -v $STRIP_STATIC "$file" ;;
      application/x-executable\;*)     strip -v $STRIP_BINARIES "$file" ;;
      application/x-pie-executable\;*) strip -v $STRIP_SHARED "$file" ;;
    esac
done < <(find "$builddir" -type f -perm -u+x ! -name vmlinux -print0)

echo "Stripping vmlinux"
strip -v $STRIP_STATIC "$builddir/vmlinux"

echo "Adding linux headers symlink"
mkdir -p "$headersdir/usr/src"
ln -sr "$builddir" "$headersdir/usr/src/linux"
