#!/bin/bash -e

rm -rf src/lib/{liblame,libx264,libffmpeg}

# Find Bluetooth controllers too: they have no /dev/input/by-id link.
patch -Np1 -i vice-evdev-scan.patch
sed -i 's/lib64/lib/g' configure.ac
autoreconf -fi

export CFLAGS="$CFLAGS -Wl,--allow-multiple-definition -w"

PKG_CONFIG_PATH='/usr/lib/ffmpeg/pkgconfig' ./configure \
  --disable-ffmpeg \
  --disable-sdl2ui \
  --enable-gtk3ui \
  --enable-x64 \
  --with-libcurl \
  --with-mpg123 \
  --with-gif \
  --libdir=/usr/lib \
  --prefix=/usr

make
make DESTDIR="$1" realdocdir=/usr/share/doc/vice install

install -d $1/usr/share/applications
install -d $1/usr/share/vice/common
cp *.desktop $1/usr/share/applications/
cp *.svg $1/usr/share/vice/common/
