#!/bin/sh -e

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --with-python3    \
            --without-gtk-doc \
            --without-nvdimm

make
make DESTDIR=$1 install
