#!/bin/bash -e

export CFLAGS="${CFLAGS} -Wno-error=discarded-qualifiers"

echo ':: cpupower'
pushd tools/power/cpupower
pkgdir=$HOKUTO_SPLIT_DIR/cpupower
make VERSION=${2}
make \
    DESTDIR="$pkgdir" \
    confdir='/etc/default/' \
    sbindir='/usr/bin' \
    libdir='/usr/lib' \
    libexecdir='/usr/lib/systemd/scripts' \
    mandir='/usr/share/man' \
    docdir='/usr/share/doc/cpupower' \
    install install-man
popd

echo ':: x86_energy_perf_policy'
pushd tools/power/x86/x86_energy_perf_policy
pkgdir=$HOKUTO_SPLIT_DIR/x86_energy_perf_policy
make
install -Dm 755 x86_energy_perf_policy "$pkgdir/usr/bin/x86_energy_perf_policy"
install -Dm 644 x86_energy_perf_policy.8 "$pkgdir/usr/share/man/man8/x86_energy_perf_policy.8"
popd

echo ':: usbip'
pushd tools/usb/usbip
pkgdir=$HOKUTO_SPLIT_DIR/usbip
# Fix gcc compilation
sed -i 's,-Wall -Werror -Wextra,-fcommon,' configure.ac
./autogen.sh
./configure --prefix=/usr --sbindir=/usr/bin
make
make install DESTDIR="$pkgdir"
popd
# module loading
install -Dm 644 /dev/null "$pkgdir/usr/lib/modules-load.d/usbip.conf"
printf 'usbip-core\nusbip-host\n' > "$pkgdir/usr/lib/modules-load.d/usbip.conf"
# systemd
install -Dm 644 usbipd.service "$pkgdir/usr/lib/systemd/system/usbipd.service"

echo ':: tmon'
pushd tools/thermal/tmon
pkgdir=$HOKUTO_SPLIT_DIR/tmon
make
make install INSTALL_ROOT="$pkgdir"
popd

echo ':: turbostat'
pushd tools/power/x86/turbostat
pkgdir=$HOKUTO_SPLIT_DIR/turbostat
make
make install DESTDIR="$pkgdir"
popd

echo ':: hv'
pushd tools/hv
pkgdir=$HOKUTO_SPLIT_DIR/hv
CFLAGS+=' -DKVP_SCRIPTS_PATH=\"/usr/lib/hypervkvpd/\"' make
make install DESTDIR="$pkgdir" sbindir=/usr/bin libexecdir=/usr/lib
for _p in hv_kvp_daemon hv_vss_daemon; do
  install -Dm644 "../../$_p.service" "$pkgdir/usr/lib/systemd/system/$_p.service"
done
popd

echo ':: bpf'
pushd tools/bpf
pkgdir=$HOKUTO_SPLIT_DIR/bpf
# doesn't compile when we don't first compile bpftool in its own directory and
# man pages require to be also launch from the subdirectory
# -j1 added to check for potential repro issues
make -j1 -C bpftool all doc
# runqslower, require kernel binary path to build, skip it
make -W runqslower
make -W runqslower_install install prefix=/usr DESTDIR="$pkgdir"
# fix bpftool hard written path
mv "$pkgdir"/usr/sbin/bpftool "$pkgdir"/usr/bin/bpftool
rmdir "$pkgdir"/usr/sbin
# install man pages
make -C bpftool doc-install prefix=/usr/share DESTDIR="$pkgdir"
popd

echo ':: bootconfig'
pushd tools/bootconfig
pkgdir=$HOKUTO_SPLIT_DIR/bootconfig
make
install -dm755 "$pkgdir/usr/bin"
make install DESTDIR="$pkgdir"
popd

echo ':: intel-speed-select'
pushd tools/power/x86/intel-speed-select
pkgdir=$HOKUTO_SPLIT_DIR/intel-speed-select
make
make install DESTDIR="$pkgdir"
popd

echo ':: kcpuid'
pushd tools/arch/x86/kcpuid
pkgdir=$HOKUTO_SPLIT_DIR/kcpuid
make
make BINDIR=/usr/bin HWDATADIR="/usr/share/misc" DESTDIR="$pkgdir" install
popd
