#!/bin/sh -e

./configure --prefix=/usr                 \
            --libexecdir=/usr/lib/lightdm \
            --localstatedir=/var          \
            --sbindir=/usr/bin            \
            --sysconfdir=/etc             \
            --disable-static              \
            --disable-tests               \
            --with-greeter-user=lightdm   \
            --with-greeter-session=lightdm-gtk-greeter

make
make DESTDIR=$1 install

mkdir -p $1/usr/bin
cp tests/src/lightdm-session $1/usr/bin
sed -i '1 s/sh/bash --login/' $1/usr/bin/lightdm-session
rm -rf $1/etc/init

mkdir -p $1/usr/lib/systemd/system
install -m 644 lightdm.service $1/usr/lib/systemd/system/
