#!/bin/sh

groupadd -g 65 lightdm
useradd  -c "Lightdm Daemon" \
         -d /var/lib/lightdm \
         -u 65 -g lightdm    \
         -s /bin/false lightdm

install -v -dm755 -o lightdm -g lightdm /var/lib/lightdm
install -v -dm755 -o lightdm -g lightdm /var/lib/lightdm-data
install -v -dm755 -o lightdm -g lightdm /var/cache/lightdm
install -v -dm770 -o lightdm -g lightdm /var/log/lightdm

echo "Add /usr/bin/systemd-session-fix to xfce autostart to fix xdg-desktop-portal"
read -p "Press Enter to continue" < /dev/tty
