#!/bin/sh -e

cmake -B build \
  -D CMAKE_INSTALL_PREFIX=/usr \
  -D CMAKE_BUILD_TYPE=RelWithDebInfo \
  -D INSTALL_BINDIR=lib/qt6/bin \
  -D INSTALL_PUBLICBINDIR=usr/bin \
  -D INSTALL_LIBEXECDIR=lib/qt6 \
  -D INSTALL_DOCDIR=share/doc/qt6 \
  -D INSTALL_ARCHDATADIR=lib/qt6 \
  -D INSTALL_DATADIR=share/qt6 \
  -D INSTALL_INCLUDEDIR=include/qt6 \
  -D INSTALL_MKSPECSDIR=lib/qt6/mkspecs \
  -D INSTALL_EXAMPLESDIR=share/doc/qt6/examples \
  -D FEATURE_journald=ON \
  -D FEATURE_libproxy=ON \
  -D FEATURE_openssl_linked=ON \
  -D FEATURE_system_sqlite=ON \
  -D FEATURE_system_xcb_xinput=ON \
  -D FEATURE_no_direct_extern_access=ON \
  -D CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
  -D CMAKE_MESSAGE_LOG_LEVEL=STATUS

cmake --build build
DESTDIR=$1 cmake --install build

install -d -m755 "$1"/usr/include/qt6xcb-private/gl_integrations
cp -r src/plugins/platforms/xcb/*.h "$1"/usr/include/qt6xcb-private/
cp -r src/plugins/platforms/xcb/gl_integrations/*.h "$1"/usr/include/qt6xcb-private/gl_integrations/
