#!/bin/sh -e

scripts/config.py set MBEDTLS_HAVE_SSE2
scripts/config.py set MBEDTLS_THREADING_C
scripts/config.py set MBEDTLS_THREADING_PTHREAD

export CFLAGS+=' -ffat-lto-objects'
cmake -B build \
   -D CMAKE_BUILD_TYPE=None \
   -D CMAKE_INSTALL_PREFIX=/usr \
   -D CMAKE_SKIP_RPATH=ON \
   -D USE_SHARED_MBEDTLS_LIBRARY=ON \
   -D USE_STATIC_MBEDTLS_LIBRARY=ON \
   -Wno-dev

cmake --build build
DESTDIR=$1 cmake --install build
