#!/bin/sh -e

cp -a /usr/lib/lazarus ./
sed -e 's/LIB_SUFFIX=.*/LIB_SUFFIX=/g' -i install/linux/install.sh
sed -e "s@=\$(which lazbuild)@=\"\$(which lazbuild) --lazarusdir=$HOKUTO_BUILD_DIR/lazarus\"@" -i build.sh
sed -e '/doublecmd.zdli/d' -i install/linux/install.sh

./build.sh components qt6
./build.sh plugins qt6
./build.sh doublecmd qt6
./install/linux/install.sh --install-prefix="$1"
