#!/bin/bash -e

hokuto-meson build
meson compile -C build
meson install -C build --destdir=$1

if [ "$MULTILIB" = "1" ]; then
#32bit
rm -rf build
hokuto-meson-32 build \
      -D tests=disabled

meson compile -C build
meson install -C build --destdir=$PWD/DESTDIR
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
