#!/bin/sh

# Add polkit group and user.
sudo /usr/bin/groupadd -fg 27 polkitd

sudo /usr/bin/useradd -c "PolicyKit Daemon Owner" -d /etc/polkit-1 -u 27 \
    -g polkitd -s /bin/false polkitd

mkdir build
cd    build

meson --prefix=/usr                       \
      --buildtype=release                 \
      -Dman=false                         \
      -Dsession_tracking=libsystemd-login \
      -Dtests=false                       \
      -Djs_engine=duktape                 \
      -Dintrospection=false               \
      ..

ninja
DESTDIR=$1 ninja install
