#!/bin/sh -e

meson setup build --prefix=/usr  \
      --buildtype=release        \
      -D os_type=lfs             \
      -D man=false               \
      -D session_tracking=logind \
      -D tests=false

meson compile -C build
meson install -C build --destdir=$1

install -Dm 644 polkit-1 $1/usr/lib/pam.d/polkit-1
install -Dm 644 10-udisks2-mount.rules $1/etc/polkit-1/rules.d/10-udisks2-mount.rules
install -Dm 644 20-my-auth-keep.rules $1/etc/polkit-1/rules.d/20-my-auth-keep.rules
install -Dm 644 49-allow-passwordless-printer-admin.rules $1/etc/polkit-1/rules.d/49-allow-passwordless-printer-admin.rules
install -Dm 644 50-logs.rules $1/etc/polkit-1/rules.d/50-logs.rules
