#!/bin/sh

# Add polkit group and user.
if ! getent group polkitd >/dev/null; then
    groupadd -fg 27 polkitd
fi

if ! id -u polkitd >/dev/null 2>&1; then
    useradd -c "PolicyKit Daemon Owner" -d /etc/polkit-1 -u 27 \
        -g polkitd -s /bin/false polkitd
fi

chmod +s /usr/lib/polkit-1/polkit-agent-helper-1
chmod +s /bin/pkexec
