#!/bin/bash -e

#fix gcc 14 build
sed -i 's/def HAVE_TERMCAP_TGETENT/ 1/' telnet/telnet.c

PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./configure            \
  --prefix="$PREFIX"   \
  --localstatedir=/var \
  --disable-logger     \
  --disable-whois      \
  --disable-rcp        \
  --disable-rexec      \
  --disable-rlogin     \
  --disable-rsh        \
  --disable-servers    \
  $CROSS_OPTS

make
make DESTDIR="$1" install

chmod 755 "$1/usr/bin/ping"
chmod 755 "$1/usr/bin/ping6"
