#!/bin/sh -e

#fix gcc 14 build
sed -i 's/def HAVE_TERMCAP_TGETENT/ 1/' telnet/telnet.c

./configure --prefix=/usr \
    --localstatedir=/var \
    --disable-logger     \
    --disable-whois      \
    --disable-rcp        \
    --disable-rexec      \
    --disable-rlogin     \
    --disable-rsh        \
    --disable-servers

make
make DESTDIR="$1" install

rm -rf $1/usr/share/info

chmod 755 "$1/usr/bin/ping"
chmod 755 "$1/usr/bin/ping6"
