#!/bin/sh -e

./configure --prefix=/usr \
    --localstatedir=/var \
    --disable-logger     \
    --disable-whois      \
    --disable-rcp        \
    --disable-rexec      \
    --disable-rlogin     \
    --disable-rsh        \
    --disable-servers

make
make DESTDIR="$1" install

chmod 755 "$1/usr/bin/ping"
chmod 755 "$1/usr/bin/ping6"
