#!/bin/sh -e

CFLAGS="$CFLAGS -fno-lto"
CXXFLAGS=$CFLAGS

./configure \
    --prefix=/usr \
    --shared-libuv \
    --shared-zlib \
    --shared-openssl \
    --shared-brotli \
    --with-intl=system-icu

make
make DESTDIR=$1 install
