#!/bin/sh -e

# uninstall xmlto for the build
if hokuto check xmlto; then
hokuto uninstall -f -y xmlto

meson setup build --prefix=/usr \
    --buildtype=release         \
    -Dupdate-mimedb=false

meson compile -C build
meson install -C build --destdir=$1

hokuto install -y xmlto

else

meson setup build --prefix=/usr \
    --buildtype=release         \
    -Dupdate-mimedb=false

meson compile -C build
meson install -C build --destdir=$1
fi
