#!/bin/bash -e

# build-spec renders the HTML specification with xmlto, which "install" then
# ignores, so it only ever costs us xmlto and docbook-xsl as build deps.
hokuto-meson build         \
    -D update-mimedb=false \
    -D build-tests=false   \
    -D build-spec=false

meson compile -C build
meson install -C build --destdir=$1
