#!/bin/sh -e

# uninstall xmlto for the build
if hokuto check xmlto; then
hokuto uninstall -f -y xmlto

meson setup build --prefix=/usr \
    --buildtype=release \
    -Dupdate-mimedb=false

ninja -C build
DESTDIR=$1 ninja install -C build

hokuto install -y xmlto

else

meson setup build --prefix=/usr \
    --buildtype=release \
    -Dupdate-mimedb=false

fi
