#!/bin/sh -e

CFLAGS="$CFLAGS -fno-lto"

PREFIX="${CROSS_PREFIX:-/usr}"

if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # Cross-compilation
    make prefix="$PREFIX" libdir="$PREFIX/lib" CC="${CC:-gcc}" AR="${AR:-ar}" RANLIB="${RANLIB:-ranlib}"
    make prefix="$PREFIX" libdir="$PREFIX/lib" DESTDIR="$1" install
else
    # Native build
    make prefix=/usr
    make prefix=/usr DESTDIR="$1" install
fi
