#!/bin/sh -e

make mrproper

if [ "$HOKUTO_ARCH" = "aarch64" ]; then
make ARCH=arm64 headers_install INSTALL_HDR_PATH=$1/usr

else
make ARCH=x86_64 headers_install INSTALL_HDR_PATH=$1/usr
fi

# Cleanup hidden files
find $1/usr/include -name '.*' -delete
