#!/bin/sh -e

make mrproper

if [ "$HOKUTO_ARCH" = "aarch64" ] && [ "${HOKUTO_CROSS:-0}" = "1" ]; then
# Case 1: cross=1 and arch=aarch64
mkdir -pv $1/usr/aarch64-linux-gnu/usr/{bin,include,lib,share}
ln -s usr/bin $1/usr/aarch64-linux-gnu/bin
ln -s usr/bin $1/usr/aarch64-linux-gnu/sbin
ln -s usr/bin $1/usr/aarch64-linux-gnu/usr/sbin
ln -s usr/lib $1/usr/aarch64-linux-gnu/lib
ln -s usr/lib $1/usr/aarch64-linux-gnu/lib64
ln -s usr/lib $1/usr/aarch64-linux-gnu/usr/lib64
ln -s usr/include $1/usr/aarch64-linux-gnu/include
ln -s usr/share $1/usr/aarch64-linux-gnu/share
make INSTALL_HDR_PATH="$1/usr/aarch64-linux-gnu/usr/" ARCH=arm64 V=0 headers_install

elif [ "$HOKUTO_ARCH" = "aarch64" ] && [ "${HOKUTO_CROSS:-0}" != "1" ]; then
# Case 2: cross=0 and arch=aarch64
make ARCH=aarch64 headers_install INSTALL_HDR_PATH=$1/usr

else
# Case 3: default
make ARCH=x86_64 headers_install INSTALL_HDR_PATH=$1/usr
fi

# clean-up unnecessary files generated during install
find "$1" \( -name .install -or -name ..install.cmd \) -delete
