#!/bin/sh -e

# de-vendor libs and disable git versioning
sed '/examples/d;/third_party/d' -i CMakeLists.txt
sed '/build-version/d' -i glslc/CMakeLists.txt

cmake -B build \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_CXX_FLAGS="$CXXFLAGS -ffat-lto-objects" \
    -D SHADERC_SKIP_TESTS=ON \
    -D PYTHON_EXECUTABLE=python \
    -D glslang_SOURCE_DIR=/usr/include/glslang

cmake --build build
DESTDIR=$1 cmake --install build
