#!/bin/sh -e

autoreconf -fvi
./configure --prefix=/usr \
    --sysconfdir=/etc     \
    --localstatedir=/var  \
    --libexecdir=/usr/lib \
    --disable-static

make
make DESTDIR=$1 install install dbusservicedir=/usr/share/dbus-1/system.d
