#!/bin/bash -e

git submodule update --init

cmake_options=(
    -D CMAKE_INSTALL_PREFIX=/usr
    -D CMAKE_BUILD_TYPE=None
    -D LDAC_SOFT_FLOAT=OFF
  )

cmake -B build "${cmake_options[@]}"
cmake --build build
DESTDIR="${1}" cmake --install build
