#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"

cross_opts=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    cross_opts=(--host="${HOKUTO_ARCH}-linux-gnu")
fi

./configure --prefix="$PREFIX" \
  --disable-static \
  --disable-tester \
  "${cross_opts[@]}"

make
make DESTDIR=$1 install
