#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-swscale \
    --enable-static \
    --enable-pic \
    --enable-shared

make
make DESTDIR=$1 install

if [ "$MULTILIB" = "1" ]; then
#32bit
make distclean
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --enable-shared          \
            --disable-cli

make
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -vr DESTDIR/usr/lib32/* $1/usr/lib32
fi
