#!/bin/bash -e

# A cross-system build installs into the target sysroot rather than the host's
# /usr, and configure needs --host so it stops probing the build machine.
PREFIX="${CROSS_PREFIX:-/usr}"

CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    CROSS_OPTS="--host=${HOKUTO_ARCH}-linux-gnu"
fi

./configure           \
    --prefix="$PREFIX" \
    $CROSS_OPTS       \
    --disable-swscale \
    --enable-static   \
    --enable-pic      \
    --enable-lto      \
    --enable-shared

make
make DESTDIR=$1 install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32bit split package
make distclean
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --enable-shared          \
            --disable-cli

make
make DESTDIR=$PWD/DESTDIR install
dest_dir="$HOKUTO_SPLIT_DIR/lib32-$3"
install -d $dest_dir/usr/lib32
cp -vr DESTDIR/usr/lib32/* $dest_dir/usr/lib32
fi
