#!/bin/sh -e

patch -Np1 -i nss-standalone-1.patch

cd nss

make BUILD_OPT=1                      \
  NSPR_INCLUDE_DIR=/usr/include/nspr  \
  USE_SYSTEM_ZLIB=1                   \
  ZLIB_LIBS=-lz                       \
  NSS_ENABLE_WERROR=0                 \
  $([ $(uname -m) = x86_64 ] && echo USE_64=1) \
  $([ -f /usr/include/sqlite3.h ] && echo NSS_USE_SYSTEM_SQLITE=1)

cd ../dist

mkdir -pv $1/usr/lib
mkdir -pv $1/usr/bin
mkdir -pv $1/usr/lib/pkgconfig

install -v -m755 Linux*/lib/*.so              $1/usr/lib
install -v -m644 Linux*/lib/{*.chk,libcrmf.a} $1/usr/lib

install -v -m755 -d                           $1/usr/include/nss
cp -v -RL {public,private}/nss/*              $1/usr/include/nss

install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} $1/usr/bin

install -v -m644 Linux*/lib/pkgconfig/nss.pc  $1/usr/lib/pkgconfig
