#!/bin/sh -e

meson setuo build          \
      --prefix=/usr        \
      --buildtype=release  \
      -D http=false        \
      -D fuse=true         \
      -D gphoto2=false     \
      -D afc=false         \
      -D bluray=false      \
      -D nfs=false         \
      -D mtp=false         \
      -D smb=true          \
      -D dnssd=false       \
      -D goa=false         \
      -D gcr=false         \
      -D keyring=false     \
      -D onedrive=false    \
      -D google=false

meson compile -C build
meson install -C build --destdir=$1
