#!/bin/sh -e

mkdir build
cd build

meson --prefix=/usr       \
      --buildtype=release \
      -Dhttp=false        \
      -Dfuse=true         \
      -Dgphoto2=false     \
      -Dafc=false         \
      -Dbluray=false      \
      -Dnfs=false         \
      -Dmtp=false         \
      -Dsmb=true          \
      -Ddnssd=false       \
      -Dgoa=false         \
      -Dgcr=false         \
      -Dkeyring=false     \
      -Donedrive=false    \
      -Dgoogle=false      ..


ninja
DESTDIR=$1 ninja install
