#!/bin/bash -e

cross_opts=()
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    # gobject-introspection and vala scan the just-built library, which
    # cannot run on the build host; gpg is looked up there too.
    cross_opts+=(-D introspection=false -D vapi=false -D gpg_path=/usr/bin/gpg)
    # The sysroot's .pc files spell their directories with the sysroot
    # prefix.
    export PKG_CONFIG_P11_KIT_1_P11_SYSTEM_CONFIG_MODULES=/usr/share/p11-kit/modules
    export PKG_CONFIG_SYSTEMD_ROOT_PREFIX="${CROSS_PREFIX:-/usr}"
fi

hokuto-meson build   \
    -D gtk_doc=false "${cross_opts[@]}"

meson compile -C build
meson install -C build --destdir=$1
