#!/bin/bash -e

cmake -B build                                 \
  -D CMAKE_INSTALL_PREFIX=/usr                 \
  -D CMAKE_C_FLAGS="$CFLAGS -ffat-lto-objects" \
  -D JAS_ENABLE_OPENGL=ON                      \
  -D JAS_ENABLE_LIBJPEG=ON                     \
  -D JAS_ENABLE_AUTOMATIC_DEPENDENCIES=OFF     \
  -D CMAKE_SKIP_RPATH=ON                       \
  -D ALLOW_IN_SOURCE_BUILD=ON                  \
  -D JAS_ENABLE_SHARED=ON

cmake --build build
DESTDIR=$1 cmake --install build

