#!/bin/bash -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --with-udev-rules-dir=/usr/lib/udev/rules.d \
    --disable-alsaconf \
    --disable-bat \
    --disable-xmlto \
    --disable-nls \
    --with-curses=ncursesw

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool

make
make DESTDIR=$1 install
install -vDm 644 $3.tmpfiles "$1/usr/lib/tmpfiles.d/$3.conf"
