#!/bin/sh -e

cd mandoc-$2

# Change default pager.
sed 's,"more -s","less",g' main.c > _
mv -f _ main.c

# Use CC rather than broken default.
sed "s/CC=.*/CC=$CC/" configure > _
mv -f _ configure

cat > configure.local <<EOF
PREFIX=/usr
MANDIR=/usr/share/man
LIBDIR=/usr/lib
SBINDIR=/usr/bin
CFLAGS="$CFLAGS -fcommon"
LN="ln -sf"
EOF

sh ./configure

make
make DESTDIR=$1 -j1 base-install

chmod 755 "$1/usr/bin/"*
