#!/bin/bash -e

export HAVE_VALGRIND_TRUE='#'
export HAVE_VALGRIND_FALSE=''

NOCONFIGURE=1 ./autogen.sh
./configure --prefix=/usr \
	    --with-gtk=3 \
	    --disable-dumper \
	    --disable-static \
	    --disable-tests

make
make -j1 -C libdbusmenu-glib DESTDIR=$1 install
make -j1 -C libdbusmenu-gtk DESTDIR=$1 install
