#!/bin/sh -e

cmake -D CMAKE_INSTALL_PREFIX=/usr  \
      -D CMAKE_BUILD_TYPE=Release   \
      -D EXIV2_ENABLE_VIDEO=yes     \
      -D EXIV2_ENABLE_WEBREADY=yes  \
      -D EXIV2_ENABLE_CURL=yes      \
      -D EXIV2_BUILD_SAMPLES=no     \
      -G "Unix Makefiles" -B build

cmake --build build
DESTDIR=$1 cmake --install build
