#!/bin/sh -e

autoreconf -fvi
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --without-rcdir      \
            --disable-static     \
            --disable-avahi
make
make DESTDIR=$1 install
