#!/bin/sh -e

cmake -B build                   \
    -D CMAKE_BUILD_TYPE=Release  \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_SKIP_RPATH=ON       \
    -D PORT=GTK                  \
    -D LIB_INSTALL_DIR=/usr/lib  \
    -D USE_LIBBACKTRACE=OFF      \
    -D USE_LIBHYPHEN=OFF         \
    -D ENABLE_GAMEPAD=OFF        \
    -D ENABLE_MINIBROWSER=ON     \
    -D ENABLE_DOCUMENTATION=OFF  \
    -D ENABLE_WEBDRIVER=ON       \
    -D ENABLE_SPELLCHECK=OFF     \
    -D ENABLE_SPEECH_SYNTHESIS=OFF \
    -D USE_JPEGXL=OFF            \
    -D USE_AVIF=OFF              \
    -D USE_GSTREAMER_TRANSCODER=ON \
    -D USE_WOFF2=ON              \
    -D USE_GTK4=OFF              \
    -D ENABLE_BUBBLEWRAP_SANDBOX=ON \
    -D USE_SYSTEM_SYSPROF_CAPTURE=NO \
    -Wno-dev -G Ninja

cmake --build build
DESTDIR=$1 cmake --install build
