#!/bin/sh -e

mkdir build
cd build

cmake -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_SKIP_RPATH=ON       \
      -DPORT=GTK                  \
      -DLIB_INSTALL_DIR=/usr/lib  \
      -DUSE_LIBBACKTRACE=OFF      \
      -DUSE_LIBHYPHEN=OFF         \
      -DENABLE_GAMEPAD=OFF        \
      -DENABLE_MINIBROWSER=ON     \
      -DENABLE_DOCUMENTATION=OFF  \
      -DENABLE_WEBDRIVER=ON       \
      -DENABLE_SPELLCHECK=OFF     \
      -DENABLE_SPEECH_SYNTHESIS=OFF \
      -DUSE_JPEGXL=OFF            \
      -DUSE_AVIF=OFF              \
      -DUSE_GSTREAMER_TRANSCODER=ON \
      -DUSE_WOFF2=ON             \
      -DUSE_GTK4=OFF               \
      -DENABLE_BUBBLEWRAP_SANDBOX=ON \
      -DUSE_SYSTEM_SYSPROF_CAPTURE=NO \
      -Wno-dev -G Ninja ..

ninja -j10
DESTDIR=$1 ninja install
