#!/bin/bash -e

PREFIX="${CROSS_PREFIX:-/usr}"
CROSS_OPTS=""
if [ "${HOKUTO_CROSS:-0}" = "1" ]; then
    HOST_TRIPLET="${HOKUTO_ARCH}-linux-gnu"
    [ "$HOKUTO_ARCH" = "x86_64" ] && HOST_TRIPLET="x86_64-linux-gnu"
    [ "$HOKUTO_ARCH" = "aarch64" ] && HOST_TRIPLET="aarch64-linux-gnu"
    CROSS_OPTS="--host=$HOST_TRIPLET"
fi

./autogen.sh
./configure \
    --prefix="$PREFIX" \
    --disable-static   \
    $CROSS_OPTS

make
make DESTDIR="${1}" install

if [ "${HOKUTO_CROSS:-0}" != "1" ] && [ "$MULTILIB" = "1" ]; then
#32 bit split package
make distclean
pkgdir=$HOKUTO_SPLIT_DIR/lib32-$3
export CC='gcc -m32'
export CXX='g++ -m32'
export PKG_CONFIG_PATH='/usr/lib32/pkg-config'

./configure  --prefix=/usr \
  --libdir=/usr/lib32      \
  --disable-static

make
make DESTDIR="$pkgdir" install
rm -rf "$pkgdir"/usr/include
fi

