#!/bin/bash -e

cmake_options=(
    -B build
    -D CMAKE_INSTALL_PREFIX=/usr
    -D CMAKE_BUILD_TYPE=None
    -D CMAKE_POLICY_VERSION_MINIMUM=3.5
    -D BUILD_SHARED_LIBS=ON
    -Wno-dev
)

cmake "${cmake_options[@]}"
cmake --build build --verbose
DESTDIR="${1}" cmake --install build
