#!/bin/sh -e

patch -Np1 -i kbd-*-backspace-1.patch

sed -i 's/\(RESIZECONS_PROGS=\)yes/\1no/g' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

./configure \
    --prefix=/usr \
    --disable-vlock

make
make DESTDIR="$1" install
