#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"


./configure --prefix=/usr

make
make DESTDIR=$1 install

#also build minizip for keepassxc

cd contrib/minizip
autoreconf -fvi
./configure --prefix=/usr
make
make DESTDIR=$1 install

#32bit minizip
make distclean
CFLAGS+=" -m32" CXXFLAGS+=" -m32" \
./configure --prefix=/usr \
    --libdir=/usr/lib32
make DESTDIR=$PWD/DESTDIR install
install -d $1/usr/lib32
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32/

#32bit zlib
cd ../..
make distclean
CFLAGS+=" -m32" CXXFLAGS+=" -m32" \
./configure --prefix=/usr \
    --libdir=/usr/lib32
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32/

