#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

./configure --prefix=/usr --zlib-compat

make
make DESTDIR=$1 install

#32bit zlib
#make distclean
#CFLAGS+=" -m32" CXXFLAGS+=" -m32" \
#./configure --prefix=/usr \
#    --zlib-compat         \
#    --libdir=/usr/lib32
#make DESTDIR=$PWD/DESTDIR install
#install -d $1/usr/lib32
#cp -Rv DESTDIR/usr/lib32/* $1/usr/lib32/

